/* New English File Pre-Intermediate 5th edition — Unit 2
   ======================================================

   The third unit from this book, authored from the photographed pages of 2A,
   2B and 2C. Each lesson carries its whole spread — the vocabulary, the grammar
   focus, the pronunciation point and the functional language — because the
   grammar and pronunciation pages are the ones authoring drifts away from.

   2A "Lost… and found?" is the past simple, regular and irregular, with holiday
   vocabulary, the three -ed sounds, Ryan's story of the phone in the jacket
   pocket, and the phrases for showing interest. 2B "On top of the world" is the
   past continuous, at/in/on for time and place, the weak forms of was and were,
   and Christopher's photo on the swing at Baños. 2C "One dark October evening"
   is time sequencers and the connectors so / because / although, the verb
   phrases of Hannah and Jamie's story, and word stress in two-syllable words.

   **Rounds are in every game that can host one**, on the same pattern as Unit 1:
   Jeopardy gets a column of every round per lesson beside four read-out columns,
   Blockbusters mixes round hexagons in with the ordinary ones, and Millionaire's
   whole bank becomes Multiple Choice when a rung opens. 2D is one Connections
   4×4 column built from the whole unit's words.

   The Holidays and Prepositions vocabulary banks (pp.160–161) were not among the
   photographed pages; their items here are the standard sets those banks teach
   and the phrases the lesson pages themselves use. */
window.UNITS.push({
  id: 'nef-2',
  label: 'New English File 5th ed · Unit 2 · Holidays & Stories',
  card: { num:'Unit 2', title:'Holidays & Stories',
          blurb:'Past simple & continuous, holidays, at/in/on, time sequencers and connectors, verb phrases (2A–2C). Rounds throughout.',
          sections:'2A–2C' },
  intro: "Choose a template. You'll pick the content next — mix and match 2A, 2B and 2C.",

  jeopardySectionLabels: {
    '2A': '2A · Lost… and found? — holidays, past simple, -ed endings',
    '2B': '2B · On top of the world — past continuous, at / in / on',
    '2C': '2C · One dark October evening — sequencers, connectors, verb phrases',
    '2D': '2D · Sort the whole field — four groups of four'
  },

  topicNames: {
    '2A-vocab':   '2A · Holidays',
    '2A-grammar': '2A · Past simple & -ed endings',
    '2B-vocab':   '2B · The swing & at / in / on',
    '2B-grammar': '2B · Past continuous',
    '2C-vocab':   '2C · Verb phrases & word stress',
    '2C-grammar': '2C · Sequencers & connectors'
  },

  /* Jeopardy — categories stay grouped by section in array order, or the content
     screen prints a section heading twice. Every category carries all five values:
     a category short of one is not a narrower column, it is a crash. */
  jeopardyCategories: [
    /* ================= 2A · Lost… and found? ================= */
    { id:'nef2-holiday-words', section:'2A', name:'Holiday Words', clues:[
      {v:100, q:"Lie on the beach until you go brown: to ___.", a:"sunbathe"},
      {v:200, q:"Visit the famous buildings and museums of a city: go ___.", a:"sightseeing"},
      {v:300, q:"A holiday in a tent: go ___.", a:"camping"},
      {v:400, q:"Which does NOT belong: hire a car / rent a car / book a car", a:"book a car — you book a hotel or a flight, you hire or rent a car", type:"oddoneout"},
      {v:500, q:"Correct it: We *made* lots of photos of the sea from the top.", a:"took", type:"errorfix"},
    ]},
    { id:'nef2-irregular-past', section:'2A', name:'Irregular Past', clues:[
      {v:100, q:"Correct it: Last year I *goed* on holiday with a group of friends.", a:"went", type:"errorfix"},
      {v:200, q:"'It ___ (take) two hours to get to the top.'", a:"took"},
      {v:300, q:"'I ___ (can) not find my phone anywhere.' — one word.", a:"couldn't"},
      {v:400, q:"The past simple of think, spend and feel — all three.", a:"thought, spent, felt"},
      {v:500, q:"Which does NOT belong: sat / let / got / decided", a:"decided — the only regular one; the others are irregular", type:"oddoneout"},
    ]},
    { id:'nef2-ryans-story', section:'2A', name:"Ryan's Story", clues:[
      {v:100, q:"Which city is Ryan from?", a:"Dublin"},
      {v:200, q:"Ryan went on holiday with his family. True or false?", a:"false — with a group of friends"},
      {v:300, q:"How long did it take them to get to the top of the mountain?", a:"two hours"},
      {v:400, q:"Why couldn't Ryan call his phone to find it?", a:"it was on silent"},
      {v:500, q:"Where was the phone in the end?", a:"in his jacket pocket"},
    ]},
    { id:'nef2-showing-interest', section:'2A', name:'Showing Interest', clues:[
      {v:100, q:"'I went to New York last week.' 'Oh, ___ lovely! Did you like it?'", a:"how"},
      {v:200, q:"'The weather was terrible.' 'Oh, what a ___! What did you do?'", a:"shame (or pity)"},
      {v:300, q:"'I lost my phone on the first day.' 'Oh ___! How did you lose it?'", a:"no"},
      {v:400, q:"Correct it: 'We went to a musical on Broadway.' '*What* amazing!'", a:"How", type:"errorfix"},
      {v:500, q:"Make the question with 'did': 'You had a good time.'", a:"Did you have a good time?"},
    ]},
    { id:'nef2-connections-2a', section:'2A', clues:[
      {v:100, q:"Four of these are regular past forms. Find the four.",
        group:{ pick:["asked","called","checked","happened"],
                with:["said","spent","sat","thought"] }},
      {v:200, q:"Four of these end in an extra syllable, /ɪd/. Find the four.",
        group:{ pick:["wanted","decided","started","needed"],
                with:["booked","stopped","phoned","lived"] }},
      {v:300, q:"Four of these end in a /t/ sound. Find the four.",
        group:{ pick:["booked","missed","asked","stopped"],
                with:["arrived","phoned","called","happened"] }},
      {v:400, q:"Four of these follow 'go' on holiday. Find the four.",
        group:{ pick:["sightseeing","camping","abroad","cycling"],
                with:["photos","souvenirs","postcards","tickets"] }},
      {v:500, q:"Four of these complete 'What a ___!' Find the four.",
        group:{ pick:["shame","pity","nightmare","surprise"],
                with:["lovely","amazing","awful","interesting"] }},
    ]},
    { id:'nef2-thermometer-2a', section:'2A', clues:[
      {v:100, q:"Put Ryan's day in order — first thing first.",
        order:{ scale:["climbed","lunch","lost","searched","found"],
                low:"the start of the day", high:"late afternoon",
                gloss:{ climbed:"two hours to the top of the mountain.",
                        lunch:"at the top, where he thought he left it.",
                        lost:"back at the car — no phone in the bag.",
                        searched:"half an hour at the top again, nothing.",
                        found:"in his jacket pocket all along." } }},
      {v:200, q:"Put a trip in order — what you do first.",
        order:{ scale:["book","pack","fly","check in","unpack"],
                low:"weeks before", high:"you have arrived",
                gloss:{ book:"reserve the hotel or the flight.",
                        pack:"put everything in your bag.",
                        fly:"the journey itself.",
                        "check in":"give your name at the hotel desk.",
                        unpack:"take everything out again." } }},
      {v:300, q:"Put these in order — shortest stay first.",
        order:{ scale:["night","weekend","week","fortnight","month"],
                low:"one sleep", high:"thirty days",
                gloss:{ night:"you leave the next morning.",
                        weekend:"Friday to Sunday.",
                        week:"seven days.",
                        fortnight:"two weeks — a British word.",
                        month:"four weeks or more." } }},
      {v:400, q:"Put these in order — coldest first.",
        order:{ scale:["freezing","cold","cool","warm","hot"],
                low:"ice on the ground", high:"you need the shade",
                gloss:{ freezing:"below zero.",
                        cold:"you need a coat.",
                        cool:"pleasant, a little cold.",
                        warm:"pleasant, a little hot — Ryan hoped it would get this.",
                        hot:"sunbathing weather." } }},
      {v:500, q:"Put these in order — how Ryan felt, worst first.",
        order:{ scale:["terrible","bad","OK","good","fantastic"],
                low:"how he felt about the phone", high:"how the view was",
                gloss:{ terrible:"really awful — his word for the phone.",
                        bad:"not good.",
                        OK:"fine, nothing special.",
                        good:"a pleasant day.",
                        fantastic:"amazing — the view from the top." } }},
    ]},
    /* Drag the Letters needs a word with no space or hyphen in it and a clue that
       does not contain the answer — the round checks both. */
    { id:'nef2-drag-letters-2a', section:'2A', clues:[
      {v:100, q:"Sleeping in a tent on holiday.",
        anagram:{ word:"camping" }},
      {v:200, q:"Lie in the sun to get brown.",
        anagram:{ word:"sunbathe" }},
      {v:300, q:"The little book you show at the airport to leave the country.",
        anagram:{ word:"passport" }},
      {v:400, q:"Things you buy on holiday to remember it by.",
        anagram:{ word:"souvenirs" }},
      {v:500, q:"Walking round a city to look at its famous buildings.",
        anagram:{ word:"sightseeing" }},
    ]},
    { id:'nef2-drag-words-2a', section:'2A', clues:[
      {v:100, q:"Put the words in order — a question about a holiday.",
        scramble:{ sentence:"Where did you go on your last holiday" }},
      {v:200, q:"Put the words in order — from Ryan's story.",
        scramble:{ sentence:"It took two hours to get to the top" }},
      {v:300, q:"Put the words in order — the moment he noticed.",
        scramble:{ sentence:"I could not find my phone anywhere" }},
      {v:400, q:"Put the words in order — what his friends said.",
        scramble:{ sentence:"You can not go up there on your own" }},
      {v:500, q:"Put the words in order — how it ended.",
        scramble:{ sentence:"My friends were very nice but they never let me forget it" }},
    ]},
    { id:'nef2-choice-2a', section:'2A', clues:[
      {v:100, q:"Which past form is irregular?",
        choice:{ options:["went","wanted","decided","started"], answer:"went" }},
      {v:200, q:"Which -ed ending is pronounced /ɪd/, with an extra syllable?",
        choice:{ options:["wanted","booked","phoned","missed"], answer:"wanted" }},
      {v:300, q:"Which negative sentence is correct?",
        choice:{ options:["I didn't want to leave my phone.","I didn't wanted to leave my phone.",
                          "I not wanted to leave my phone.","I didn't want leave my phone."],
                 answer:"I didn't want to leave my phone." }},
      {v:400, q:"Which question is correct?",
        choice:{ options:["Where did you go?","Where you went?","Where did you went?","Where went you?"],
                 answer:"Where did you go?" }},
      {v:500, q:"A friend says 'It rained every day.' Which reply shows interest?",
        choice:{ options:["Oh, what a shame!","Oh, what a lovely!","Oh, how shame!","Oh, what lovely!"],
                 answer:"Oh, what a shame!" }},
    ]},
    /* Information Gap — each phone on a team is dealt the sentence with a
       different starred word hidden. Targets are single words with no apostrophes. */
    { id:'nef2-infogap-2a', section:'2A', clues:[
      {v:100, q:"How the story starts — ask your team for your missing words.",
        infogap:{ sentence:"Last *year* I went on *holiday* with a group of *friends*" }},
      {v:200, q:"The climb — ask your team for your missing words.",
        infogap:{ sentence:"It took two *hours* to get to the *top* of the *mountain*" }},
      {v:300, q:"Back at the car — ask your team for your missing words.",
        infogap:{ sentence:"I *wanted* to take another *photo* but I could not find my *phone*" }},
      {v:400, q:"The ending — ask your team for your missing words.",
        infogap:{ sentence:"My phone was in my *jacket* pocket and I felt really *stupid*" }},
      {v:500, q:"Planning a trip — ask your team for your missing words.",
        infogap:{ sentence:"We *booked* a hotel online and *rented* a car at the *airport*" }},
    ]},

    /* ================= 2B · On top of the world ================= */
    { id:'nef2-was-or-were-doing', section:'2B', name:'Was or Were Doing', clues:[
      {v:100, q:"'At eight o'clock last night I ___ (watch) TV.'", a:"was watching"},
      {v:200, q:"'What ___ you ___ (do) when I called?'", a:"were / doing"},
      {v:300, q:"Correct it: They *was* riding up the mountain when they saw their friends.", a:"were", type:"errorfix"},
      {v:400, q:"'We ___ (not / expect) the volcano to erupt that day.'", a:"weren't expecting"},
      {v:500, q:"Which does NOT belong: I was looking / she was surfing / we were watching / he watched", a:"he watched — past simple, the others are past continuous", type:"oddoneout"},
    ]},
    { id:'nef2-at-in-on', section:'2B', name:'At, In or On', clues:[
      {v:100, q:"'___ 2014, I was studying acting at university.'", a:"In"},
      {v:200, q:"'Some time later, I was ___ a doctor's waiting room.'", a:"in"},
      {v:300, q:"'We were riding up the mountain ___ our bikes.'", a:"on"},
      {v:400, q:"Correct it: I saw the photo *in* the weekend.", a:"at", type:"errorfix"},
      {v:500, q:"Which does NOT belong: at night / at the weekend / at Christmas / at the morning", a:"at the morning — it is 'in the morning'", type:"oddoneout"},
    ]},
    { id:'nef2-the-swing', section:'2B', name:'The Swing at Baños', clues:[
      {v:100, q:"Which country is Baños in?", a:"Ecuador"},
      {v:200, q:"What was Christopher studying at university?", a:"acting"},
      {v:300, q:"What did they rent to ride up to the swing?", a:"quad bikes"},
      {v:400, q:"What is the name of the volcano you can see from the swing?", a:"Mount Tungurahua"},
      {v:500, q:"Where did Christopher see the photo again, some time later?", a:"in a National Geographic magazine, in a doctor's waiting room"},
    ]},
    { id:'nef2-simple-or-continuous', section:'2B', name:'Simple or Continuous?', clues:[
      {v:100, q:"'I ___ (look) through a magazine when I ___ (see) the photo.'", a:"was looking / saw"},
      {v:200, q:"The situation, not an action: 'It ___ (rain) and it was dark.'", a:"was raining"},
      {v:300, q:"A finished action: 'Suddenly the cloud ___ (cover) the sky.'", a:"covered"},
      {v:400, q:"Correct it: She *surfed* when she saw the shark.", a:"was surfing", type:"errorfix"},
      {v:500, q:"What is the difference? 'When I arrived, they left.' / 'When I arrived, they were leaving.'", a:"first: they left after I arrived; second: they were in the middle of leaving"},
    ]},
    { id:'nef2-connections-2b', section:'2B', clues:[
      {v:100, q:"Four of these follow 'at' when you say when. Find the four.",
        group:{ pick:["night","midnight","noon","Christmas"],
                with:["morning","April","summer","2014"] }},
      {v:200, q:"Four of these follow 'on' when you say where. Find the four.",
        group:{ pick:["the beach","the bus","the wall","the floor"],
                with:["the car","bed","Ecuador","the kitchen"] }},
      {v:300, q:"Four of these describe an action in progress. Find the four.",
        group:{ pick:["was riding","were watching","was looking","were swinging"],
                with:["rode","watched","looked","swung"] }},
      {v:400, q:"Four of these came out of the volcano. Find the four.",
        group:{ pick:["smoke","ash","cloud","noise"],
                with:["swing","treehouse","ropes","seat"] }},
      {v:500, q:"Four of these mean frightened. Find the four.",
        group:{ pick:["terrified","scared","afraid","frightened"],
                with:["relaxed","calm","cool","happy"] }},
    ]},
    { id:'nef2-thermometer-2b', section:'2B', clues:[
      {v:100, q:"Put Christopher's story in order — first thing first.",
        order:{ scale:["university","town","bikes","swing","magazine"],
                low:"2014, before the trip", high:"some time later",
                gloss:{ university:"studying acting, before he went to Ecuador.",
                        town:"one weekend in Baños with some friends.",
                        bikes:"quad bikes up the mountain.",
                        swing:"twenty minutes in the air, watching the smoke.",
                        magazine:"the photo, months later, at the doctor's." } }},
      {v:200, q:"Put these in order — smallest place first.",
        order:{ scale:["room","building","town","country","continent"],
                low:"in a room", high:"in South America",
                gloss:{ room:"the waiting room he was sitting in.",
                        building:"the doctor's, the university.",
                        town:"Baños.",
                        country:"Ecuador.",
                        continent:"South America." } }},
      {v:300, q:"Put these in order — calmest first.",
        order:{ scale:["relaxed","nervous","worried","scared","terrified"],
                low:"how he looks in the photo", high:"how he really felt",
                gloss:{ relaxed:"no worries at all — the photo face.",
                        nervous:"a little uneasy.",
                        worried:"thinking something could go wrong.",
                        scared:"frightened.",
                        terrified:"extremely frightened — his own word." } }},
      {v:400, q:"Put the afternoon on the swing in order — first thing first.",
        order:{ scale:["sunshine","smoke","noise","cloud","leave"],
                low:"clear skies", high:"time to go",
                gloss:{ sunshine:"beautiful weather when they set off.",
                        smoke:"coming from the volcano as they swung.",
                        noise:"loud noises after twenty minutes.",
                        cloud:"an enormous cloud of ash covering the sky.",
                        leave:"the local people said 'We have to go'." } }},
      {v:500, q:"Put these in order — lowest first.",
        order:{ scale:["floor","chair","roof","clouds","space"],
                low:"on the ground", high:"far above the sky",
                gloss:{ floor:"on the floor — feet on the ground.",
                        chair:"on a chair.",
                        roof:"on the roof.",
                        clouds:"in the clouds — high up in the air.",
                        space:"in space — above everything." } }},
    ]},
    { id:'nef2-drag-letters-2b', section:'2B', clues:[
      {v:100, q:"It sends out smoke and ash — Tungurahua is one.",
        anagram:{ word:"volcano" }},
      {v:200, q:"Christopher rode up this on a quad bike.",
        anagram:{ word:"mountain" }},
      {v:300, q:"National Geographic is one.",
        anagram:{ word:"magazine" }},
      {v:400, q:"Not relaxed at all, whatever the photo says.",
        anagram:{ word:"terrified" }},
      {v:500, q:"Beautiful weather — this and clear skies when they set off.",
        anagram:{ word:"sunshine" }},
    ]},
    { id:'nef2-drag-words-2b', section:'2B', clues:[
      {v:100, q:"Put the words in order — a question about last night.",
        scramble:{ sentence:"What were you doing at eight last night" }},
      {v:200, q:"Put the words in order — from the article.",
        scramble:{ sentence:"We were riding up the mountain on our bikes" }},
      {v:300, q:"Put the words in order — the background to a story.",
        scramble:{ sentence:"It was raining when we arrived at the airport" }},
      {v:400, q:"Put the words in order — how he found the photo.",
        scramble:{ sentence:"I was looking through a magazine when I saw the photo" }},
      {v:500, q:"Put the words in order — two things at the same time.",
        scramble:{ sentence:"While we were swinging the volcano was sending out smoke" }},
    ]},
    { id:'nef2-choice-2b', section:'2B', clues:[
      {v:100, q:"Which sentence describes an action in progress in the past?",
        choice:{ options:["I was looking through a magazine.","I looked through a magazine.",
                          "I look through magazines.","I have looked through a magazine."],
                 answer:"I was looking through a magazine." }},
      {v:200, q:"'___ 2014, I was studying in Ecuador.' Which fits?",
        choice:{ options:["In","At","On","By"], answer:"In" }},
      {v:300, q:"'I was ___ university at the time.' Which fits?",
        choice:{ options:["at","in","on","by"], answer:"at" }},
      {v:400, q:"'She took this photo when we were ___ holiday.' Which fits?",
        choice:{ options:["on","in","at","by"], answer:"on" }},
      {v:500, q:"In which sentence is 'was' unstressed, said as /wəz/?",
        choice:{ options:["I was looking through a magazine.","Yes, I was.",
                          "No, I wasn't.","Was he? Really?"],
                 answer:"I was looking through a magazine." }},
    ]},
    { id:'nef2-infogap-2b', section:'2B', clues:[
      {v:100, q:"How it started — ask your team for your missing words.",
        infogap:{ sentence:"One *weekend* I visited a small *town* in Ecuador with some *friends*" }},
      {v:200, q:"Getting there — ask your team for your missing words.",
        infogap:{ sentence:"We *rented* quad *bikes* to ride up to the *swing*" }},
      {v:300, q:"The view — ask your team for your missing words.",
        infogap:{ sentence:"We could see an enormous *cloud* of *ash* in the *sky*" }},
      {v:400, q:"Anya's photo — ask your team for your missing words.",
        infogap:{ sentence:"We were *drinking* champagne because Roz was *celebrating* all the hard *work*" }},
      {v:500, q:"The surprise — ask your team for your missing words.",
        infogap:{ sentence:"Sean *won* a *prize* in a travel photo *competition*" }},
    ]},

    /* ================= 2C · One dark October evening ================= */
    { id:'nef2-verb-phrases', section:'2C', name:'Verb Phrases', clues:[
      {v:100, q:"'___ somebody to dinner.' — ask them to come.", a:"invite"},
      {v:200, q:"'Give somebody your phone ___.'", a:"number"},
      {v:300, q:"Which does NOT belong: drive along / run across / wait for / have a hurry", a:"have a hurry — it is 'be in a hurry'", type:"oddoneout"},
      {v:400, q:"Correct it: He *made* her to a very romantic restaurant.", a:"took", type:"errorfix"},
      {v:500, q:"Three things you can 'have' in 2C: a ___, a ___ and a great ___.", a:"coffee, dinner, time"},
    ]},
    { id:'nef2-so-because-although', section:'2C', name:'So, Because or Although', clues:[
      {v:100, q:"'They didn't like the music, ___ Hannah went to speak to the DJ.'", a:"so"},
      {v:200, q:"'She ran to her car ___ she was late.'", a:"because"},
      {v:300, q:"'___ it was raining, they walked to the coffee bar.'", a:"Although"},
      {v:400, q:"Correct it: *Because* the food wasn't very good, they had a wonderful time.", a:"Although", type:"errorfix"},
      {v:500, q:"Which does NOT belong: so / because / although / suddenly", a:"suddenly — a time sequencer, not a connector", type:"oddoneout"},
    ]},
    { id:'nef2-time-sequencers', section:'2C', name:'Time Sequencers', clues:[
      {v:100, q:"'___ minutes later, he played a song for her.'", a:"Two"},
      {v:200, q:"'The ___ day, Jamie phoned Hannah.'", a:"next"},
      {v:300, q:"Something nobody expected: '___, a man ran across the road.'", a:"Suddenly"},
      {v:400, q:"'___ that, they saw each other every day.'", a:"After"},
      {v:500, q:"Correct it: *One evening in the October*, Hannah was at work.", a:"One evening in October", type:"errorfix"},
    ]},
    { id:'nef2-word-stress', section:'2C', name:'Word Stress', clues:[
      {v:100, q:"'evening' — is the stress on the first or the second syllable?", a:"the first"},
      {v:200, q:"The verb: 'INvite' or 'inVITE'?", a:"inVITE"},
      {v:300, q:"Which does NOT belong: after / awful / because / birthday", a:"because — stressed on the second syllable", type:"oddoneout"},
      {v:400, q:"Most two-syllable nouns and adjectives are stressed on the ___ syllable.", a:"first"},
      {v:500, q:"across, perfect, again — which one is stressed on the first syllable?", a:"perfect"},
    ]},
    { id:'nef2-connections-2c', section:'2C', clues:[
      {v:100, q:"Four of these are stressed on the first syllable. Find the four.",
        group:{ pick:["after","awful","birthday","evening"],
                with:["across","again","because","invite"] }},
      {v:200, q:"Four of these can follow 'have a'. Find the four.",
        group:{ pick:["coffee","dinner","drink","break"],
                with:["song","road","street","club"] }},
      {v:300, q:"Four of these are verbs from the story's phrases. Find the four.",
        group:{ pick:["invite","drive","wait","leave"],
                with:["dinner","number","restaurant","brake"] }},
      {v:400, q:"Four of these tell you WHEN something happened. Find the four.",
        group:{ pick:["suddenly","later","then","when"],
                with:["so","because","although","but"] }},
      {v:500, q:"Four of these are places in the story. Find the four.",
        group:{ pick:["club","restaurant","bar","street"],
                with:["watch","coat","song","brake"] }},
    ]},
    { id:'nef2-thermometer-2c', section:'2C', clues:[
      {v:100, q:"Put how they met in order — first thing first.",
        order:{ scale:["club","song","number","dinner","every day"],
                low:"Hannah's birthday", high:"madly in love",
                gloss:{ club:"her birthday night out with friends.",
                        song:"the DJ played one for the girl in the pink dress.",
                        number:"she gave him her phone number at the door.",
                        dinner:"the romantic French restaurant.",
                        "every day":"they met at 5.30 in the coffee bar." } }},
      {v:200, q:"Put these in order — shortest time first.",
        order:{ scale:["seconds","minutes","hours","days","months"],
                low:"'Suddenly…'", high:"'Two months later…'",
                gloss:{ seconds:"'Suddenly' — no time at all.",
                        minutes:"'Two minutes later, he said…'",
                        hours:"'They talked all evening.'",
                        days:"'The next day, Jamie phoned.'",
                        months:"'Two months later…' — 'After that' can be this long." } }},
      {v:300, q:"Put an evening out in order — first thing first.",
        order:{ scale:["invite","meet","restaurant","talk","goodbye"],
                low:"the phone call", high:"the end of the night",
                gloss:{ invite:"invite somebody to dinner.",
                        meet:"meet them at the door.",
                        restaurant:"take them to a restaurant.",
                        talk:"talk all evening.",
                        goodbye:"leave, very late." } }},
      {v:400, q:"Put these in order — earliest first.",
        order:{ scale:["early","on time","a bit late","late","very late"],
                low:"before 5.30", high:"long after 5.30",
                gloss:{ early:"before the time you agreed.",
                        "on time":"exactly when you said.",
                        "a bit late":"a few minutes after — 5.35.",
                        late:"they have been waiting a while.",
                        "very late":"they have probably gone home." } }},
      {v:500, q:"Put these in order — weakest feeling first.",
        order:{ scale:["hate","dislike","like","love","adore"],
                low:"'This music is awful'", high:"madly in love",
                gloss:{ hate:"Hannah and the music at the club.",
                        dislike:"not keen, politely.",
                        like:"the plain word.",
                        love:"Hannah and Jamie by October.",
                        adore:"love, said as strongly as possible." } }},
    ]},
    { id:'nef2-drag-letters-2c', section:'2C', clues:[
      {v:100, q:"Hannah was in one, so she was driving very fast.",
        anagram:{ word:"hurry" }},
      {v:200, q:"The reason Hannah and her friends went to the club that night.",
        anagram:{ word:"birthday" }},
      {v:300, q:"Perfect for a first date — the French place was very this.",
        anagram:{ word:"romantic" }},
      {v:400, q:"The time sequencer for something nobody expected.",
        anagram:{ word:"suddenly" }},
      {v:500, q:"Where you go for a romantic dinner out.",
        anagram:{ word:"restaurant" }},
    ]},
    { id:'nef2-drag-words-2c', section:'2C', clues:[
      {v:100, q:"Put the words in order — two minutes later.",
        scramble:{ sentence:"Two minutes later he played a song for her" }},
      {v:200, q:"Put the words in order — the next day.",
        scramble:{ sentence:"The next day Jamie phoned Hannah and invited her to dinner" }},
      {v:300, q:"Put the words in order — a reason.",
        scramble:{ sentence:"She was going very fast because she was in a hurry" }},
      {v:400, q:"Put the words in order — a result.",
        scramble:{ sentence:"He was wearing a dark coat so Hannah did not see him" }},
      {v:500, q:"Put the words in order — a contrast.",
        scramble:{ sentence:"Although the food was not very good they had a wonderful time" }},
    ]},
    { id:'nef2-choice-2c', section:'2C', clues:[
      {v:100, q:"'She was going very fast ___ she was in a hurry.' Which fits?",
        choice:{ options:["because","so","although","when"], answer:"because" }},
      {v:200, q:"'He was wearing a dark coat, ___ Hannah didn't see him.' Which fits?",
        choice:{ options:["so","because","although","when"], answer:"so" }},
      {v:300, q:"'___ the food wasn't very good, they had a wonderful time.' Which fits?",
        choice:{ options:["Although","Because","So","Suddenly"], answer:"Although" }},
      {v:400, q:"inVITE, BIRTHday, EVEning, PERfect — which one has its stress on the second syllable?",
        choice:{ options:["invite","birthday","evening","perfect"], answer:"invite" }},
      {v:500, q:"Which verb phrase is correct?",
        choice:{ options:["wait for somebody","wait somebody","wait to somebody","wait by somebody"],
                 answer:"wait for somebody" }},
    ]},
    { id:'nef2-infogap-2c', section:'2C', clues:[
      {v:100, q:"The night they met — ask your team for your missing words.",
        infogap:{ sentence:"It was her *birthday* so she and her *friends* went to a *club*" }},
      {v:200, q:"Leaving the club — ask your team for your missing words.",
        infogap:{ sentence:"The DJ was *waiting* for her at the *door* when they left" }},
      {v:300, q:"The first date — ask your team for your missing words.",
        infogap:{ sentence:"He took her to a very *romantic* French *restaurant* and they *talked* all evening" }},
      {v:400, q:"Every evening — ask your team for your missing words.",
        infogap:{ sentence:"Every *evening* they met in a *coffee* bar in the high *street*" }},
      {v:500, q:"The accident — ask your team for your missing words.",
        infogap:{ sentence:"Suddenly a *man* ran across the *road* wearing a dark *coat*" }},
    ]},

    /* ================= 2D · Connections 4×4 — sort the whole field =================
       Sixteen words, four hidden groups of four, built from 2A–2C's own words so
       the puzzle is revision. Each group sits in the same field as its neighbours
       — regular against irregular, sequencer against connector — so the sort is a
       discrimination. Its own section so the lesson columns keep their length. */
    { id:'nef2-connections4', section:'2D', clues:[
      {v:100, q:"Little words from all three lessons — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Regular past forms",   words:["wanted","decided","started","climbed"] },
          { label:"Irregular past forms", words:["went","took","could","felt"] },
          { label:"Time sequencers",      words:["suddenly","later","then","when"] },
          { label:"Connectors",           words:["so","because","although","but"] } ] }},
      {v:200, q:"Which little word goes in front? Sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"After 'at'",          words:["night","home","work","midnight"] },
          { label:"After 'in'",          words:["April","summer","bed","Ecuador"] },
          { label:"After 'on'",          words:["Monday","holiday","foot","Sunday"] },
          { label:"Things you take or buy on holiday", words:["photos","souvenirs","tickets","passport"] } ] }},
      {v:300, q:"All from Hannah and Jamie's story — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Stressed on the first syllable",  words:["after","awful","birthday","evening"] },
          { label:"Stressed on the second syllable", words:["across","again","along","because"] },
          { label:"Verbs from the phrases",          words:["invite","drive","wait","leave"] },
          { label:"Places in the story",             words:["club","restaurant","street","door"] } ] }},
      {v:400, q:"Sixteen words that end in a t or d sound — sort them into four groups.",
        connections:{ groups:[
          { label:"-ed said /ɪd/",   words:["wanted","needed","decided","started"] },
          { label:"-ed said /t/",    words:["booked","missed","asked","stopped"] },
          { label:"-ed said /d/",    words:["arrived","phoned","called","lived"] },
          { label:"Nouns ending in -et", words:["jacket","pocket","ticket","market"] } ] }},
      {v:500, q:"Bits of all three stories — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Ways to feel scared",          words:["terrified","scared","afraid","frightened"] },
          { label:"What Ryan took up the mountain", words:["phone","jacket","bag","lunch"] },
          { label:"From the volcano",             words:["smoke","ash","cloud","noise"] },
          { label:"Where Hannah and Jamie went",  words:["club","restaurant","bar","car"] } ] }},
    ]},
  ],

  /* Blockbusters — an ordinary hexagon needs a one-word answer beginning with its
     letter. A round hexagon still carries a letter and no answer. They are filed in
     with the ordinary ones on purpose — a hexagon does not announce what it holds. */
  blockbustersBank: [
    {section:'2A', topic:'2A-vocab', letter:'S', clue:"Lie in the sun to get a tan.", answer:"Sunbathe"},
    {section:'2A', topic:'2A-vocab', letter:'C', clue:"A holiday under canvas, with a tent.", answer:"Camping"},
    {section:'2A', topic:'2A-vocab', letter:'A', clue:"Go to another country: go ___.", answer:"Abroad"},
    {section:'2A', topic:'2A-vocab', letter:'P', clue:"The document you need to leave the country.", answer:"Passport"},
    {section:'2A', topic:'2A-vocab', letter:'H', clue:"Pay to use a car for a week: ___ a car.", answer:"Hire"},
    {section:'2A', topic:'2A-vocab', letter:'R', clue:"Pay to use an apartment for a week: ___ an apartment.", answer:"Rent"},
    {section:'2A', topic:'2A-vocab', type:'anagram', letter:'S', clue:"Unscramble: things you buy to remember a holiday.", answer:"Souvenirs"},
    {section:'2A', topic:'2A-grammar', letter:'W', clue:"The past simple of 'go'.", answer:"Went"},
    {section:'2A', topic:'2A-grammar', letter:'T', clue:"The past simple of 'take'.", answer:"Took"},
    {section:'2A', topic:'2A-grammar', letter:'F', clue:"The past simple of 'feel'.", answer:"Felt"},
    {section:'2A', topic:'2A-vocab', letter:'D', clue:"The city Ryan is from.", answer:"Dublin"},
    {section:'2A', topic:'2A-vocab', letter:'J', clue:"Where Ryan's phone was in the end: in his ___ pocket.", answer:"Jacket"},
    {section:'2A', topic:'2A-vocab', letter:'M', clue:"What Ryan and his friends climbed.", answer:"Mountain"},
    {section:'2A', topic:'2A-vocab', letter:'S', clue:"Ryan's phone was on this setting, so nobody could hear it ring.", answer:"Silent"},
    {section:'2A', topic:'2A-grammar', letter:'E', clue:"Four of these are said with an extra syllable at the end. Find the four.",
      group:{ pick:["rented","visited","ended","waited"], with:["booked","phoned","thanked","happened"] }},
    {section:'2A', topic:'2A-grammar', letter:'T', clue:"Put these in order — most recent first.",
      order:{ scale:["yesterday","last week","last month","last year","ten years ago"],
              low:"the day before today", high:"a long time ago",
              gloss:{ yesterday:"the day before today.",
                      "last week":"the week before this one.",
                      "last month":"the month before this one.",
                      "last year":"when Ryan went on holiday.",
                      "ten years ago":"a decade back." } }},
    {section:'2A', topic:'2A-vocab', letter:'I', clue:"On holiday — ask your team for the missing words.",
      infogap:{ sentence:"We *stayed* in a small *hotel* near the *beach*" }},

    {section:'2B', topic:'2B-vocab', letter:'V', clue:"A mountain that can erupt.", answer:"Volcano"},
    {section:'2B', topic:'2B-vocab', letter:'E', clue:"The country where Baños is.", answer:"Ecuador"},
    {section:'2B', topic:'2B-vocab', letter:'S', clue:"What Christopher was sitting on, hanging from a treehouse.", answer:"Swing"},
    {section:'2B', topic:'2B-vocab', letter:'A', clue:"The grey cloud from the volcano was made of this.", answer:"Ash"},
    {section:'2B', topic:'2B-vocab', letter:'R', clue:"The swing hangs from two old ones.", answer:"Ropes"},
    {section:'2B', topic:'2B-vocab', letter:'T', clue:"Extremely frightened — how Christopher really felt.", answer:"Terrified"},
    {section:'2B', topic:'2B-vocab', letter:'M', clue:"Christopher saw his photo in a National Geographic ___.", answer:"Magazine"},
    {section:'2B', topic:'2B-vocab', letter:'P', clue:"Sean won this in a travel photo competition.", answer:"Prize"},
    {section:'2B', topic:'2B-grammar', letter:'W', clue:"The weak form of this word sounds like /wəz/.", answer:"Was"},
    {section:'2B', topic:'2B-vocab', letter:'U', clue:"Where Christopher was studying acting: at ___.", answer:"University"},
    {section:'2B', topic:'2B-grammar', letter:'B', clue:"'I was in ___ when the phone rang.' — no 'the'.", answer:"Bed"},
    {section:'2B', topic:'2B-grammar', letter:'N', clue:"'At ___' — the opposite of 'in the day'.", answer:"Night"},
    {section:'2B', topic:'2B-vocab', letter:'C', clue:"Roz and Anya were drinking this to celebrate.", answer:"Champagne"},
    {section:'2B', topic:'2B-grammar', letter:'P', clue:"Four of these follow 'in'. Find the four.",
      group:{ pick:["April","summer","2014","bed"], with:["Monday","Friday","holiday","foot"] }},
    {section:'2B', topic:'2B-grammar', letter:'T', clue:"Put these in order — earliest in the day first.",
      order:{ scale:["morning","midday","afternoon","evening","night"],
              low:"in the morning", high:"at night",
              gloss:{ morning:"in the morning — until twelve.",
                      midday:"at midday — twelve o'clock.",
                      afternoon:"in the afternoon — after lunch.",
                      evening:"in the evening — after work.",
                      night:"at night — when it is dark." } }},
    {section:'2B', topic:'2B-vocab', letter:'D', clue:"Describing a photo — ask your team for the missing words.",
      infogap:{ sentence:"In this *photo* we were *sitting* on the *beach* at *sunset*" }},

    {section:'2C', topic:'2C-vocab', letter:'I', clue:"Ask somebody to come to dinner with you: ___ them.", answer:"Invite"},
    {section:'2C', topic:'2C-vocab', letter:'H', clue:"Be in a ___ — you have no time.", answer:"Hurry"},
    {section:'2C', topic:'2C-vocab', letter:'B', clue:"The day you were born, celebrated every year.", answer:"Birthday"},
    {section:'2C', topic:'2C-vocab', letter:'D', clue:"The person who plays the music in a club.", answer:"DJ"},
    {section:'2C', topic:'2C-vocab', letter:'P', clue:"The singer of 'Get the Party Started'.", answer:"Pink"},
    {section:'2C', topic:'2C-vocab', letter:'R', clue:"Jamie took Hannah to a French one.", answer:"Restaurant"},
    {section:'2C', topic:'2C-vocab', letter:'C', clue:"Every evening they met in a ___ bar.", answer:"Coffee"},
    {section:'2C', topic:'2C-grammar', letter:'S', clue:"'It was raining, ___ she drove carefully.' — the result word.", answer:"So"},
    {section:'2C', topic:'2C-grammar', letter:'A', clue:"'___ it was raining, they went for a walk.' — the contrast word.", answer:"Although"},
    {section:'2C', topic:'2C-grammar', letter:'B', clue:"'She was late ___ she left work at 5.20.' — the reason word.", answer:"Because"},
    {section:'2C', topic:'2C-grammar', letter:'W', clue:"'___ they left the club, the DJ was waiting.'", answer:"When"},
    {section:'2C', topic:'2C-vocab', letter:'E', clue:"The part of the day after work — stressed on the first syllable.", answer:"Evening"},
    {section:'2C', topic:'2C-vocab', letter:'A', clue:"The opposite of 'wonderful' — how Hannah described the music.", answer:"Awful"},
    {section:'2C', topic:'2C-vocab', letter:'S', clue:"Four of these are stressed on the second syllable. Find the four.",
      group:{ pick:["invite","because","arrive","before"], with:["quickly","perfect","mother","happy"] }},
    {section:'2C', topic:'2C-grammar', letter:'W', clue:"Put Hannah's evening in order — first thing first.",
      order:{ scale:["work","watch","car","street","brake"],
              low:"5.20", high:"5.25 and after",
              gloss:{ work:"she was at work, as usual.",
                      watch:"she looked at her watch — 5.20!",
                      car:"she ran to her car and got in.",
                      street:"driving along the high street, very fast.",
                      brake:"a man ran across the road — foot on the brake." } }},
    {section:'2C', topic:'2C-vocab', letter:'N', clue:"A first date — ask your team for the missing words.",
      infogap:{ sentence:"He *invited* her to *dinner* and they *talked* all *evening*" }},
  ],

  blockbustersSectionNames: {
    '2A': '2A · Holidays & the past simple (17 clues)',
    '2B': '2B · The swing, past continuous & at / in / on (16 clues)',
    '2C': '2C · Hannah & Jamie — phrases, connectors & stress (16 clues)'
  },

  /* Race — the answers become tiles on the board, so every one is a single word and
     no two are the same. Gapped sentences, the shape this game suits. */
  raceBank: [
    {section:'2A', topic:'2A-grammar', prompt:"Last year I ___ on holiday with a group of friends.", answer:"Went"},
    {section:'2A', topic:'2A-grammar', prompt:"One day we ___ a mountain — well, it wasn't really a climb.", answer:"Climbed"},
    {section:'2A', topic:'2A-grammar', prompt:"It ___ us two hours to get to the top.", answer:"Took"},
    {section:'2A', topic:'2A-grammar', prompt:"I ___ find my phone anywhere.", answer:"Couldn't"},
    {section:'2A', topic:'2A-grammar', prompt:"We ___ half an hour looking for it.", answer:"Spent"},
    {section:'2A', topic:'2A-grammar', prompt:"I ___ terrible, and really stupid.", answer:"Felt"},
    {section:'2A', topic:'2A-vocab', prompt:"Did you ___ a good time on holiday?", answer:"Have"},
    {section:'2A', topic:'2A-vocab', prompt:"We ___ a hotel online before we left.", answer:"Booked"},

    {section:'2B', topic:'2B-grammar', prompt:"In 2014 I ___ studying acting at university.", answer:"Was"},
    {section:'2B', topic:'2B-grammar', prompt:"We ___ riding up the mountain when we saw our friends.", answer:"Were"},
    {section:'2B', topic:'2B-grammar', prompt:"I was reading a magazine ___ I saw the photo.", answer:"When"},
    {section:'2B', topic:'2B-vocab', prompt:"We were sitting ___ an old wooden seat.", answer:"On"},
    {section:'2B', topic:'2B-vocab', prompt:"I was studying ___ university at the time.", answer:"At"},
    {section:'2B', topic:'2B-vocab', prompt:"She took this photo ___ the Easter holidays.", answer:"In"},
    {section:'2B', topic:'2B-vocab', prompt:"There was an enormous cloud of ___ in the sky.", answer:"Ash"},
    {section:'2B', topic:'2B-vocab', prompt:"The ___ was active that day, so we had to leave.", answer:"Volcano"},

    {section:'2C', topic:'2C-grammar', prompt:"The music was awful, ___ she went to complain to the DJ.", answer:"So"},
    {section:'2C', topic:'2C-grammar', prompt:"She didn't see the man ___ he was wearing a dark coat.", answer:"Because"},
    {section:'2C', topic:'2C-grammar', prompt:"___ the food wasn't very good, they had a wonderful time.", answer:"Although"},
    {section:'2C', topic:'2C-grammar', prompt:"The next ___, Jamie phoned Hannah.", answer:"Day"},
    {section:'2C', topic:'2C-grammar', prompt:"Two minutes ___, he played a song for her.", answer:"Later"},
    {section:'2C', topic:'2C-grammar', prompt:"___, a man ran across the road.", answer:"Suddenly"},
    {section:'2C', topic:'2C-vocab', prompt:"He was ___ a dark coat, so she didn't see him at first.", answer:"Wearing"},
    {section:'2C', topic:'2C-vocab', prompt:"She was in a ___, so she was going very fast.", answer:"Hurry"},
  ],

  raceSectionNames: {
    '2A': '2A · Holidays & the past simple (8 words)',
    '2B': '2B · Past continuous & at / in / on (8 words)',
    '2C': '2C · Sequencers, connectors & verb phrases (8 words)'
  },

  /* Millionaire — the ladder is per team and runs 1 to 8, so every section needs at
     least two questions at every rung. Every one becomes a Multiple Choice round
     when its rung opens; the game builds it from {answer, distractors}. */
  millionaireBank: [
    {section:'2A', topic:'2A-grammar', level:1, prompt:"What is the past simple of 'go'?", answer:"went", distractors:["goed","gone","going"]},
    {section:'2A', topic:'2A-vocab', level:1, prompt:"Which one is a holiday activity?", answer:"sunbathe", distractors:["sunrise","sunlight","sunny"]},
    {section:'2A', topic:'2A-grammar', level:2, prompt:"How is the -ed in 'booked' pronounced?", answer:"/t/", distractors:["/d/","/ɪd/","/ed/"]},
    {section:'2A', topic:'2A-vocab', level:2, prompt:"Where did Ryan and his friends go on the day he lost his phone?", answer:"up a mountain", distractors:["to the beach","into the city","to the airport"]},
    {section:'2A', topic:'2A-grammar', level:3, prompt:"Which past form is regular?", answer:"decided", distractors:["thought","said","felt"]},
    {section:'2A', topic:'2A-grammar', level:3, prompt:"Which -ed ending has an extra syllable, /ɪd/?", answer:"wanted", distractors:["stopped","phoned","thanked"]},
    {section:'2A', topic:'2A-grammar', level:4, prompt:"Which negative is correct?", answer:"I didn't want to go.", distractors:["I didn't wanted to go.","I not wanted to go.","I didn't to want go."]},
    {section:'2A', topic:'2A-grammar', level:4, prompt:"Which question about a holiday is correct?", answer:"Where did you stay?", distractors:["Where you stayed?","Where did you stayed?","Where stayed you?"]},
    {section:'2A', topic:'2A-grammar', level:5, prompt:"'I ___ find my phone.' Which is the past of 'can't'?", answer:"couldn't", distractors:["can'ted","didn't can","wasn't can"]},
    {section:'2A', topic:'2A-vocab', level:5, prompt:"'It rained every day.' Which reply shows interest?", answer:"Oh, what a shame!", distractors:["Oh, how lovely!","How amazing!","What a great time!"]},
    {section:'2A', topic:'2A-vocab', level:6, prompt:"Why did Ryan go back up the mountain?", answer:"to look for his phone", distractors:["to take more photos","to have lunch","to find his friends"]},
    {section:'2A', topic:'2A-vocab', level:6, prompt:"Which verb goes with 'sightseeing'?", answer:"go", distractors:["do","make","take"]},
    {section:'2A', topic:'2A-grammar', level:7, prompt:"Which pair are both pronounced with /ɪd/ at the end?", answer:"rented and started", distractors:["asked and checked","called and lived","stopped and thanked"]},
    {section:'2A', topic:'2A-vocab', level:7, prompt:"Why couldn't Ryan ring his phone to find it?", answer:"it was on silent", distractors:["the battery was dead","there was no signal","his friend had it"]},
    {section:'2A', topic:'2A-grammar', level:8, prompt:"Which sentence has TWO irregular past forms?", answer:"We sat in the sun and took photos.", distractors:["We walked and talked all day.","We climbed and rested.","We wanted and needed it."]},
    {section:'2A', topic:'2A-grammar', level:8, prompt:"Which verb has the same form in the present and the past?", answer:"let", distractors:["sit","get","feel"]},

    {section:'2B', topic:'2B-grammar', level:1, prompt:"Which one is the past continuous?", answer:"I was studying", distractors:["I studied","I study","I have studied"]},
    {section:'2B', topic:'2B-vocab', level:1, prompt:"'___ 2014' — which preposition?", answer:"in", distractors:["at","on","by"]},
    {section:'2B', topic:'2B-vocab', level:2, prompt:"'I was ___ home all evening.' Which fits?", answer:"at", distractors:["in","on","to"]},
    {section:'2B', topic:'2B-vocab', level:2, prompt:"Where is the Swing at the end of the world?", answer:"Ecuador", distractors:["Spain","Peru","Mexico"]},
    {section:'2B', topic:'2B-vocab', level:3, prompt:"'We met ___ Monday morning.' Which fits?", answer:"on", distractors:["in","at","by"]},
    {section:'2B', topic:'2B-grammar', level:3, prompt:"'What ___ you doing at eight last night?' Which fits?", answer:"were", distractors:["was","did","are"]},
    {section:'2B', topic:'2B-grammar', level:4, prompt:"Which sentence uses the past continuous for the background to a story?", answer:"It was raining and it was dark.", distractors:["It rained yesterday.","It rains a lot here.","It has rained all week."]},
    {section:'2B', topic:'2B-grammar', level:4, prompt:"'She was surfing when she ___ the shark.' Which fits?", answer:"saw", distractors:["was seeing","sees","seen"]},
    {section:'2B', topic:'2B-grammar', level:5, prompt:"Which word is weak, unstressed, in 'We were watching the smoke'?", answer:"were", distractors:["watching","smoke","we"]},
    {section:'2B', topic:'2B-vocab', level:5, prompt:"'Some time later, I was ___ a doctor's waiting room.' Which fits?", answer:"in", distractors:["at","on","by"]},
    {section:'2B', topic:'2B-vocab', level:6, prompt:"What did the friends coming down the mountain say?", answer:"'The volcano is active today.'", distractors:["'The swing is closed.'","'The weather is terrible.'","'Go back to the town.'"]},
    {section:'2B', topic:'2B-vocab', level:6, prompt:"'___ the weekend' — which preposition, in British English?", answer:"at", distractors:["in","on","by"]},
    {section:'2B', topic:'2B-grammar', level:7, prompt:"Which sentence is correct?", answer:"He wasn't looking, so he didn't see it.", distractors:["He didn't looking, so he wasn't see it.","He wasn't look, so he didn't saw it.","He not was looking, so he didn't see it."]},
    {section:'2B', topic:'2B-vocab', level:7, prompt:"'Are we in danger?' — whose thought was this in the article?", answer:"one part of Christopher's mind", distractors:["Sean's, taking the photo","the local people's","the newspaper's"]},
    {section:'2B', topic:'2B-vocab', level:8, prompt:"How did Christopher find out that Sean had won a prize?", answer:"he saw the photo in a magazine", distractors:["Sean phoned him","it was on the news","he entered the competition too"]},
    {section:'2B', topic:'2B-grammar', level:8, prompt:"Which sentence means the two things happened at the same time?", answer:"While I was swinging, the volcano was smoking.", distractors:["I swung, then the volcano smoked.","After I swung, the volcano smoked.","I swung because the volcano smoked."]},

    {section:'2C', topic:'2C-vocab', level:1, prompt:"Which verb completes '___ somebody to dinner'?", answer:"invite", distractors:["give","take","wait"]},
    {section:'2C', topic:'2C-grammar', level:1, prompt:"Which word is a connector?", answer:"because", distractors:["suddenly","later","then"]},
    {section:'2C', topic:'2C-grammar', level:2, prompt:"'Two minutes ___' — which word completes the time sequencer?", answer:"later", distractors:["after","next","then"]},
    {section:'2C', topic:'2C-vocab', level:2, prompt:"Where did Hannah and Jamie first meet?", answer:"at a club", distractors:["at a restaurant","at work","in a coffee bar"]},
    {section:'2C', topic:'2C-vocab', level:3, prompt:"'She was in a ___, so she was driving very fast.' Which fits?", answer:"hurry", distractors:["speed","quick","late"]},
    {section:'2C', topic:'2C-vocab', level:3, prompt:"Which word is stressed on the second syllable?", answer:"because", distractors:["evening","perfect","awful"]},
    {section:'2C', topic:'2C-grammar', level:4, prompt:"'___ the food wasn't very good, they had a wonderful time.' Which word fits?", answer:"Although", distractors:["Because","So","When"]},
    {section:'2C', topic:'2C-grammar', level:4, prompt:"Which sentence uses the connector correctly?", answer:"He was wearing a dark coat, so Hannah didn't see him.", distractors:["He was wearing a dark coat, because Hannah didn't see him.","He was wearing a dark coat, although Hannah didn't see him.","He was wearing a dark coat, when Hannah didn't see him."]},
    {section:'2C', topic:'2C-vocab', level:5, prompt:"Which verb phrase is correct English?", answer:"wait for somebody", distractors:["wait somebody","wait to somebody","wait at somebody"]},
    {section:'2C', topic:'2C-vocab', level:5, prompt:"What was the DJ's name?", answer:"Jamie", distractors:["Sean","Ryan","Christopher"]},
    {section:'2C', topic:'2C-grammar', level:6, prompt:"Which one is a time sequencer?", answer:"The next day", distractors:["although","because","so"]},
    {section:'2C', topic:'2C-vocab', level:6, prompt:"Which word is stressed on the first syllable?", answer:"birthday", distractors:["invite","across","along"]},
    {section:'2C', topic:'2C-vocab', level:7, prompt:"Why did Hannah go and speak to the DJ?", answer:"the music was awful", distractors:["she wanted to dance with him","she knew him already","she wanted to leave"]},
    {section:'2C', topic:'2C-vocab', level:7, prompt:"Most two-syllable verbs are stressed on the ___ syllable.", answer:"second", distractors:["first","both","neither"]},
    {section:'2C', topic:'2C-grammar', level:8, prompt:"Which sentence uses 'because' correctly?", answer:"She ran to her car because she was late.", distractors:["She was late, because she ran to her car.","Because she was late, so she ran.","She ran to her car, because so she was late."]},
    {section:'2C', topic:'2C-vocab', level:8, prompt:"At 5.25, what was Hannah doing?", answer:"driving along the high street", distractors:["waiting in the coffee bar","leaving work","talking to Jamie"]},
  ],

  millionaireSectionNames: {
    '2A': '2A · Holidays & the past simple (16 questions)',
    '2B': '2B · Past continuous & at / in / on (16 questions)',
    '2C': '2C · Sequencers, connectors & verb phrases (16 questions)'
  }
});
