/* ================= Content bank — Empower C1 Unit 5: Fairness =================
   Data only. Consumed by game-hub/hub-engine.js via window.UNIT.
   Authored from material/empower-c1-unit-5/ (pp.55-66 + Grammar/Vocab Focus).

   **Jeopardy and Blockbusters are all rounds.** Every clue on those two boards is
   a question the room *plays* from their handsets — Connections, Word Thermometer,
   Multiple Choice, Drag the Letters, Drag the Words — rather than one the teacher
   reads out. The simple question-and-answer content those two banks used to hold
   is gone.

   **Race and Millionaire are untouched, for opposite reasons.** Millionaire needs
   none: its ladder already builds a Multiple Choice round out of every rung when
   the question opens, so `millionaireBank` was rounds before this was written, and
   Quickfire reads the same bank. Race cannot host one at all — its scattered words
   *are* the board, so a round would need the stage as its mount, which is on the
   build order and not built. Its bank stays gapped sentences.

   **`bingoBank` is where the old Blockbusters calls went.** A bingo call is a clue
   with one single-word answer; a round hexagon has no answer at all — a Connections
   set has four and a scale has five — so an all-rounds Blockbusters bank would have
   taken Bingo out of the unit with it. Same content, its own field. */
(window.UNITS = window.UNITS || []).push({
  id: "unit-5",
  label: "Cambridge Empower C1 · Unit 5 · Fairness",
  card: { num: "Unit 5", title: "Fairness", blurb: "Crime & justice, relative clauses, employment, obligation, recalling & speculating, opinion essays (5A–5D).", sections: "5A–5D" },
  intro: "Choose a template. You'll pick the content next — mix and match any of 5A–5D.",

  jeopardySectionLabels: {
    '5A': "5A · A place where you have to look over your shoulder",
    '5B': "5B · It's essential to have the right qualifications",
    '5C': "5C · I'd hazard a guess",
    '5D': "5D · It's a way of making the application process more efficient",
    '5E': "5E · Sort the whole field — four groups of four",
  },

  /* Every clue on this board is a **round** — a question the room plays from their
     handsets, not one the teacher reads out. Five categories per section, one per
     round type, so a teacher picking 5A gets all five dynamics and a teacher
     picking three sections gets fifteen columns of them.

     The rounds were matched to the language point rather than sprinkled: relative
     clauses are a word-order problem, so they are Drag the Words; the crime
     vocabulary is dense enough that four-that-belong-together is a real
     discrimination, so it is Connections; the certainty and obligation language is
     a scale by nature, so it is the Thermometer. */
  jeopardyCategories: [
    /* ================= 5A · crime, justice and relative clauses ================= */
    { id:'5a-connections', section:'5A', clues:[
      {v:100, q:"Four of these are people you find in a courtroom. Find the four.",
        group:{ pick:["jury","witness","defendant","judge"],
                with:["tenant","surgeon","applicant","referee"] }},
      {v:200, q:"Four of these are crimes. The others are parts of a trial. Find the crimes.",
        group:{ pick:["fraud","murder","laundering","theft"],
                with:["verdict","custody","testimony","appeal"] }},
      {v:300, q:"Four of these mean the court decided you did it. Find the four.",
        group:{ pick:["convicted","guilty","sentenced","condemned"],
                with:["acquitted","cleared","exonerated","pardoned"] }},
      {v:400, q:"Four of these are punishments. Find the four.",
        group:{ pick:["imprisonment","fine","probation","curfew"],
                with:["allegation","testimony","alibi","appeal"] }},
      {v:500, q:"Four of these happen before a trial begins. Find the four.",
        group:{ pick:["arrested","charged","remanded","questioned"],
                with:["convicted","sentenced","imprisoned","released"] }},
    ]},
    { id:'5a-thermometer', section:'5A', clues:[
      {v:100, q:"Put these in order — least certain first.",
        order:{ scale:["gossip","suspicion","allegation","charge","conviction"],
                low:"just talk", high:"proved in court",
                gloss:{ gossip:"people talking — no evidence at all.",
                        suspicion:"a feeling, held by someone official.",
                        allegation:"a claim made formally, still unproved.",
                        charge:"the state has decided to take you to court.",
                        conviction:"a court has found it proved." } }},
      {v:200, q:"Put these in order — mildest punishment first.",
        order:{ scale:["caution","fine","community","probation","imprisonment"],
                low:"a telling-off", high:"locked up",
                gloss:{ caution:"a formal warning, on your record but nothing more.",
                        fine:"you pay money and walk away.",
                        community:"unpaid work — 'a community order'.",
                        probation:"free, but supervised and reporting in.",
                        imprisonment:"you lose your liberty." } }},
      {v:300, q:"Put these in order — weakest evidence first.",
        order:{ scale:["hearsay","claim","testimony","evidence","proof"],
                low:"someone said so", high:"beyond doubt",
                gloss:{ hearsay:"what someone told someone else — usually inadmissible.",
                        claim:"an assertion, so far unsupported.",
                        testimony:"a sworn account given in court.",
                        evidence:"material the court can weigh.",
                        proof:"enough to settle the question." } }},
      {v:400, q:"Put these in order — least serious offence first.",
        order:{ scale:["littering","vandalism","theft","assault","murder"],
                low:"a small fine", high:"life in prison",
                gloss:{ littering:"dropping rubbish — a fixed penalty.",
                        vandalism:"damaging property on purpose.",
                        theft:"taking what is not yours.",
                        assault:"attacking a person.",
                        murder:"unlawful killing — the most serious of all." } }},
      {v:500, q:"Put these in order — earliest stage of a case first.",
        order:{ scale:["arrest","charge","trial","verdict","sentence"],
                low:"the very beginning", high:"the very end",
                gloss:{ arrest:"the police take you into custody.",
                        charge:"you are formally accused of a specific offence.",
                        trial:"the case is heard in court.",
                        verdict:"guilty or not guilty — the jury decides.",
                        sentence:"the judge says what the punishment is." } }},
    ]},
    /* Grammar Focus 5A (p146). A four-way choice is the right shape for relative
       pronouns because the book's own exercise b is already written as one — the
       distractors are the pronouns a C1 student actually reaches for by mistake. */
    { id:'5a-choice', section:'5A', clues:[
      {v:100, q:"'The juror ___ fell asleep during the trial was replaced.'",
        choice:{ options:["who","which","whose","whom"], answer:"who" }},
      {v:200, q:"'The elderly woman ___ bag was taken has come forward.'",
        choice:{ options:["whose","who's","which","whom"], answer:"whose" }},
      {v:300, q:"'The witness to ___ we spoke has disappeared.'",
        choice:{ options:["whom","who","which","that"], answer:"whom" }},
      {v:400, q:"Which word refers back to the whole clause? 'She lied on her form, ___ was a bad sign.'",
        choice:{ options:["which","that","what","who"], answer:"which" }},
      {v:500, q:"'The prison, the walls ___ which are covered in art, is famous.'",
        choice:{ options:["of","in","for","by"], answer:"of" }},
    ]},
    /* Only a word-order round asks the thing p146 is actually about: where the
       clause interrupts the main clause, whether the preposition fronts, and where
       the commas fall. A gap fill hands you the finished sentence. */
    { id:'5a-scramble', section:'5A', clues:[
      {v:100, q:"Put the words in order — a defining clause with 'that'.",
        scramble:{ sentence:"The law that was recently passed makes no sense" }},
      {v:200, q:"Put the words in order — the clause interrupts the main clause.",
        scramble:{ sentence:"The detective who interviewed her has now retired" }},
      {v:300, q:"Put the words in order — the preposition comes before 'whom'.",
        scramble:{ sentence:"The witness to whom we spoke has disappeared" }},
      {v:400, q:"Put the words in order — non-defining, so mind the commas.",
        scramble:{ sentence:"Halden prison, which opened in 2010, is humane" }},
      {v:500, q:"Put the words in order — 'of which' in formal writing.",
        scramble:{ sentence:"The prison, the walls of which are covered in art" }},
    ]},
    { id:'5a-anagram', section:'5A', clues:[
      {v:100, q:"the decision a jury delivers", anagram:{ word:"verdict" }},
      {v:200, q:"where you are held before your trial begins", anagram:{ word:"custody" }},
      {v:300, q:"a claim that you were somewhere else at the time", anagram:{ word:"alibi" }},
      {v:400, q:"the sworn account a witness gives in court", anagram:{ word:"testimony" }},
      {v:500, q:"the formal word for an illegal act", anagram:{ word:"offence" }},
    ]},

    /* ================= 5B · employment, pay and obligation ================= */
    { id:'5b-connections', section:'5B', clues:[
      {v:100, q:"Four of these are sectors of the economy. Find the four.",
        group:{ pick:["financial","retail","construction","agricultural"],
                with:["flexitime","sabbatical","paternity","overtime"] }},
      {v:200, q:"Four of these are benefits an employer offers. Find the four.",
        group:{ pick:["flexitime","sabbatical","paternity","pension"],
                with:["transport","energy","manufacturing","retail"] }},
      {v:300, q:"Four of these mean you have no choice. Find the four.",
        group:{ pick:["compulsory","mandatory","required","obliged"],
                with:["optional","voluntary","advisable","discretionary"] }},
      {v:400, q:"Four of these are about losing a job. Find the four.",
        group:{ pick:["redundancy","dismissal","sacking","layoffs"],
                with:["recruitment","appointment","promotion","hiring"] }},
      {v:500, q:"Four of these are qualifications. The others are pay. Find the qualifications.",
        group:{ pick:["degree","diploma","certificate","apprenticeship"],
                with:["salary","bonus","commission","wages"] }},
    ]},
    { id:'5b-thermometer', section:'5B', clues:[
      {v:100, q:"Put these in order — least obligation first.",
        order:{ scale:["optional","advisable","expected","required","compulsory"],
                low:"entirely up to you", high:"no choice at all",
                gloss:{ optional:"nobody minds either way.",
                        advisable:"a good idea, and that is all.",
                        expected:"people will notice if you do not.",
                        required:"the rules say you do it.",
                        compulsory:"there is no way out of it." } }},
      {v:200, q:"Put these in order — least permitted first.",
        order:{ scale:["forbidden","discouraged","tolerated","permitted","encouraged"],
                low:"never, under any circumstances", high:"please do",
                gloss:{ forbidden:"formally not allowed — the strongest refusal.",
                        discouraged:"allowed, but they would rather you did not.",
                        tolerated:"nobody stops you, nobody approves.",
                        permitted:"officially allowed.",
                        encouraged:"they actively want you to." } }},
      {v:300, q:"Put these in order — most junior first.",
        order:{ scale:["intern","trainee","assistant","manager","director"],
                low:"just arrived", high:"runs the place",
                gloss:{ intern:"often unpaid, and there to learn.",
                        trainee:"employed, but still being taught the job.",
                        assistant:"doing the job, supporting someone senior.",
                        manager:"responsible for other people's work.",
                        director:"sets what the organisation does." } }},
      {v:400, q:"Put these in order — shortest time off first.",
        order:{ scale:["break","day","weekend","holiday","sabbatical"],
                low:"minutes", high:"months",
                gloss:{ 'break':"ten minutes away from your desk.",
                        day:"a single day off, often at short notice.",
                        weekend:"two days, and the standard one.",
                        holiday:"a week or more of your annual leave.",
                        sabbatical:"a long paid career break, often six months." } }},
      {v:500, q:"Put these in order — least secure job first.",
        order:{ scale:["casual","temporary","probationary","permanent","tenured"],
                low:"could end today", high:"almost impossible to end",
                gloss:{ casual:"paid by the shift, with no promise of another.",
                        temporary:"a fixed end date from the start.",
                        probationary:"permanent in name, but they can still let you go.",
                        permanent:"no end date, and proper notice required.",
                        tenured:"protected by contract — you keep the post." } }},
    ]},
    /* Grammar Focus 5B (p147) — must imposes the obligation yourself, have to
       describes one somebody else imposed, and must has no past. */
    { id:'5b-choice', section:'5B', clues:[
      {v:100, q:"Which one describes a rule that somebody ELSE imposed on you?",
        choice:{ options:["have to","must","ought to","had better"], answer:"have to" }},
      {v:200, q:"'Must' has no past. Put it in the past: 'I must go on a business trip.'",
        choice:{ options:["I had to go","I musted go","I must went","I have must go"], answer:"I had to go" }},
      {v:300, q:"'You ___ be early tomorrow!' — urgent advice, two words.",
        choice:{ options:["had better","would rather","ought better","must to"], answer:"had better" }},
      {v:400, q:"'You ___ pay tax on that' — it simply is not necessary.",
        choice:{ options:["don't have to","mustn't","can't","shouldn't"], answer:"don't have to" }},
      {v:500, q:"'Visitors are ___ to bring food into the building' — a formal refusal.",
        choice:{ options:["forbidden","required","expected","obliged"], answer:"forbidden" }},
    ]},
    { id:'5b-scramble', section:'5B', clues:[
      {v:100, q:"Put the words in order — a modal takes no 'to'.",
        scramble:{ sentence:"You must wear a helmet on this site" }},
      {v:200, q:"Put the words in order — 'obliged' takes 'to'.",
        scramble:{ sentence:"She is obliged to provide safety equipment" }},
      {v:300, q:"Put the words in order — the negative of 'have to'.",
        scramble:{ sentence:"You do not have to pay tax on it" }},
      {v:400, q:"Put the words in order — 'made' plus the adjective.",
        scramble:{ sentence:"He was made redundant late last year" }},
      {v:500, q:"Put the words in order — what the rules say.",
        scramble:{ sentence:"The director is supposed to authorise all major spending" }},
    ]},
    { id:'5b-anagram', section:'5B', clues:[
      {v:100, q:"the money paid for a week's work", anagram:{ word:"wages" }},
      {v:200, q:"a long paid career break, often six months", anagram:{ word:"sabbatical" }},
      {v:300, q:"the benefit that lets you choose your own hours", anagram:{ word:"flexitime" }},
      {v:400, q:"describes something you absolutely must do", anagram:{ word:"mandatory" }},
      {v:500, q:"a duty you cannot get out of", anagram:{ word:"obligation" }},
    ]},

    /* ================= 5C · recalling and speculating ================= */
    { id:'5c-connections', section:'5C', clues:[
      {v:100, q:"Four of these are about remembering. The others are about guessing.",
        group:{ pick:["recall","remember","recollect","reminisce"],
                with:["speculate","presume","assume","suppose"] }},
      {v:200, q:"Four of these appear in expressions about memory. Find the four.",
        group:{ pick:["serves","stands","slipped","crossed"],
                with:["hazard","presume","reckon","gather"] }},
      {v:300, q:"Four of these show you are certain. Find the four.",
        group:{ pick:["definitely","certainly","undoubtedly","clearly"],
                with:["possibly","perhaps","presumably","arguably"] }},
      {v:400, q:"Four of these go with the word 'memory'. Find the four.",
        group:{ pick:["vague","vivid","painful","lasting"],
                with:["heavy","loud","narrow","steep"] }},
      {v:500, q:"Four of these are rough. The others are certain. Find the rough four.",
        group:{ pick:["guess","estimate","reckon","suppose"],
                with:["confirm","verify","prove","establish"] }},
    ]},
    { id:'5c-thermometer', section:'5C', clues:[
      {v:100, q:"Put these in order — least certain first.",
        order:{ scale:["possibly","probably","presumably","definitely","undoubtedly"],
                low:"a wild guess", high:"no doubt at all",
                gloss:{ possibly:"it might be true, and might not.",
                        probably:"more likely than not.",
                        presumably:"you assume it, without checking.",
                        definitely:"you are sure.",
                        undoubtedly:"nobody could reasonably disagree." } }},
      {v:200, q:"Put these in order — faintest memory first.",
        order:{ scale:["forgotten","hazy","vague","clear","vivid"],
                low:"gone completely", high:"as if it were yesterday",
                gloss:{ forgotten:"nothing is left of it at all.",
                        hazy:"you know it happened, and little more.",
                        vague:"the outline, none of the detail.",
                        clear:"you can describe it accurately.",
                        vivid:"you can still see and hear it." } }},
      {v:300, q:"Put these in order — least reliable source first.",
        order:{ scale:["rumour","hunch","impression","recollection","record"],
                low:"someone said so", high:"written down at the time",
                gloss:{ rumour:"passed along, from nobody in particular.",
                        hunch:"a feeling, with nothing behind it.",
                        impression:"what you took away — often wrong.",
                        recollection:"what you actually remember.",
                        record:"written down, and checkable." } }},
      {v:400, q:"Put these in order — roughest first.",
        order:{ scale:["guess","estimate","calculation","measurement","proof"],
                low:"a number off the top of your head", high:"settles the question",
                gloss:{ guess:"no working at all.",
                        estimate:"a considered approximation.",
                        calculation:"worked out from figures you have.",
                        measurement:"you went and checked it.",
                        proof:"nothing is left to argue about." } }},
      {v:500, q:"Put these in order — least committed first.",
        order:{ scale:["wondered","suspected","believed","knew","witnessed"],
                low:"the thought crossed your mind", high:"you were there",
                gloss:{ wondered:"it occurred to you as a possibility.",
                        suspected:"you leaned towards it being true.",
                        believed:"you took it to be true.",
                        knew:"you had no doubt.",
                        witnessed:"you saw it happen yourself." } }},
    ]},
    { id:'5c-choice', section:'5C', clues:[
      {v:100, q:"'If my memory ___ me correctly…'",
        choice:{ options:["serves","helps","holds","keeps"], answer:"serves" }},
      {v:200, q:"'I'd ___ a guess that she already knew.'",
        choice:{ options:["hazard","risk","throw","take"], answer:"hazard" }},
      {v:300, q:"'What ___ out in my mind is how quiet it was.'",
        choice:{ options:["stands","comes","goes","puts"], answer:"stands" }},
      {v:400, q:"'It's ___ my mind' — I have forgotten it completely.",
        choice:{ options:["slipped","dropped","fallen","lost"], answer:"slipped" }},
      {v:500, q:"Which one shows the speaker is SURE?",
        choice:{ options:["no doubt","I'd hazard a guess","roughly speaking","I'm not certain"], answer:"no doubt" }},
    ]},
    { id:'5c-scramble', section:'5C', clues:[
      {v:100, q:"Put the words in order — recalling, with slight uncertainty.",
        scramble:{ sentence:"If my memory serves me correctly we met before" }},
      {v:200, q:"Put the words in order — speculating.",
        scramble:{ sentence:"I would hazard a guess that she already knew" }},
      {v:300, q:"Put the words in order — what you remember most vividly.",
        scramble:{ sentence:"What stands out in my mind is the silence" }},
      {v:400, q:"Put the words in order — a belief that turned out wrong.",
        scramble:{ sentence:"I was under the impression that you had left" }},
      {v:500, q:"Put the words in order — admitting you forgot.",
        scramble:{ sentence:"The whole thing has completely slipped my mind" }},
    ]},
    { id:'5c-anagram', section:'5C', clues:[
      {v:100, q:"to bring a past event back to mind", anagram:{ word:"recall" }},
      {v:200, q:"a feeling about something, with no evidence behind it", anagram:{ word:"hunch" }},
      {v:300, q:"to guess about something you cannot be sure of", anagram:{ word:"speculate" }},
      {v:400, q:"a belief you were 'under', which turned out to be wrong", anagram:{ word:"impression" }},
      {v:500, q:"unclear and hazy — said of a memory", anagram:{ word:"vague" }},
    ]},

    /* ================= 5D · opinion essays and linking ================= */
    { id:'5d-connections', section:'5D', clues:[
      {v:100, q:"Four of these add a point. The others contrast. Find the four that add.",
        group:{ pick:["moreover","furthermore","besides","additionally"],
                with:["however","nevertheless","whereas","conversely"] }},
      {v:200, q:"Four of these are parts of an essay. Find the four.",
        group:{ pick:["introduction","argument","counterargument","conclusion"],
                with:["heading","footnote","caption","index"] }},
      {v:300, q:"Four of these narrow to one case. The others add a new point.",
        group:{ pick:["notably","especially","particularly","chiefly"],
                with:["moreover","besides","furthermore","additionally"] }},
      {v:400, q:"Four of these are things an employer does to check you. Find the four.",
        group:{ pick:["trawling","screening","vetting","researching"],
                with:["hiring","promoting","training","paying"] }},
      {v:500, q:"Four of these are concerns applicants raise. Find the four.",
        group:{ pick:["privacy","discrimination","transparency","fairness"],
                with:["salary","overtime","bonus","pension"] }},
    ]},
    { id:'5d-thermometer', section:'5D', clues:[
      {v:100, q:"Put these in order — first paragraph to last.",
        order:{ scale:["introduction","argument","counterargument","evaluation","conclusion"],
                low:"opens the essay", high:"closes the essay",
                gloss:{ introduction:"outlines the topic and catches the reader's interest.",
                        argument:"the case for one side, with support.",
                        counterargument:"the case for the other side, given fairly.",
                        evaluation:"weighing the two against each other.",
                        conclusion:"your balanced opinion — and no new information." } }},
      {v:200, q:"Put these in order — chattiest first, most formal last.",
        order:{ scale:["plus","and","also","moreover","furthermore"],
                low:"a text message", high:"an academic essay",
                gloss:{ plus:"spoken English only — never write it in an essay.",
                        and:"joins two things inside a sentence.",
                        also:"neutral, and fine in most writing.",
                        moreover:"formal, and starts a new sentence.",
                        furthermore:"the most formal of the four." } }},
      {v:300, q:"Put these in order — weakest claim first.",
        order:{ scale:["suggests","indicates","shows","demonstrates","proves"],
                low:"hints at it", high:"settles it",
                gloss:{ suggests:"points that way, without insisting.",
                        indicates:"the evidence leans this way.",
                        shows:"makes it visible.",
                        demonstrates:"makes it plain, step by step.",
                        proves:"leaves nothing to argue about." } }},
      {v:400, q:"Put these in order — least attention first.",
        order:{ scale:["glance","skim","read","study","scrutinise"],
                low:"barely looks", high:"goes through every line",
                gloss:{ glance:"a second, at most.",
                        skim:"picks up the gist and moves on.",
                        read:"the ordinary word — start to finish.",
                        study:"reads it in order to understand it properly.",
                        scrutinise:"examines it looking for something wrong." } }},
      {v:500, q:"Put these in order — mildest first.",
        order:{ scale:["arguably","probably","clearly","certainly","undeniably"],
                low:"you could make the case", high:"nobody could disagree",
                gloss:{ arguably:"a case can be made, and also against.",
                        probably:"more likely than not.",
                        clearly:"obvious once stated.",
                        certainly:"you are committing to it.",
                        undeniably:"the strongest of the five — use it rarely." } }},
    ]},
    { id:'5d-choice', section:'5D', clues:[
      {v:100, q:"Which paragraph gives your balanced opinion of both sides?",
        choice:{ options:["the conclusion","the introduction","paragraph two","paragraph three"], answer:"the conclusion" }},
      {v:200, q:"Which of these must NOT appear in a conclusion?",
        choice:{ options:["new information","a summary","a course of action","your opinion"], answer:"new information" }},
      {v:300, q:"Which one joins two ideas inside a SINGLE sentence?",
        choice:{ options:["as well as","in addition","moreover","furthermore"], answer:"as well as" }},
      {v:400, q:"Which phrase introduces the point you most want remembered?",
        choice:{ options:["above all","in addition","as well","what is more"], answer:"above all" }},
      {v:500, q:"'___ addition, they complain that companies go trawling.'",
        choice:{ options:["In","On","By","With"], answer:"In" }},
    ]},
    { id:'5d-scramble', section:'5D', clues:[
      {v:100, q:"Put the words in order — adding a point.",
        scramble:{ sentence:"In addition employers now routinely check social media" }},
      {v:200, q:"Put the words in order — your most important argument.",
        scramble:{ sentence:"Above all the process must be fair and transparent" }},
      {v:300, q:"Put the words in order — a formal linker opens it.",
        scramble:{ sentence:"Moreover applicants are rarely told what was actually found" }},
      {v:400, q:"Put the words in order — 'Beyond' plus the -ing form.",
        scramble:{ sentence:"Beyond researching applicants online employers also contact referees" }},
      {v:500, q:"Put the words in order — what the writer concludes.",
        scramble:{ sentence:"Clear guidelines are needed to restrict what employers research" }},
    ]},
    { id:'5d-anagram', section:'5D', clues:[
      {v:100, q:"the paragraph that closes an essay", anagram:{ word:"conclusion" }},
      {v:200, q:"the paragraph that opens one", anagram:{ word:"introduction" }},
      {v:300, q:"open, and easy for anyone to see into", anagram:{ word:"transparent" }},
      {v:400, q:"to treat someone unfairly because of their age or health", anagram:{ word:"discriminate" }},
      {v:500, q:"the one-word linker meaning 'what is more'", anagram:{ word:"moreover" }},
    ]},

    /* ================= 5E · Connections 4×4 — sort the whole field =================
       The `connections` round (sixteen words, four hidden groups of four), drawn
       from the vocabulary 5A–5D already teach so the puzzle is revision, not new
       words. Every group sits in the same semantic field as its neighbours, which
       is the trap: "sentenced" is a verdict and "imprisonment" a punishment;
       "reckon" is a guess and "recall" a memory. The label is the payoff — naming
       the category is half the lesson. Its own section so the four themed columns
       above keep their length; a teacher who wants the flick/tap physics picks it
       here. */
    { id:'5e-connections4', section:'5E', clues:[
      {v:100, q:"Crime and justice — sort the sixteen into four groups of four.",
        connections:{ groups:[
          { label:"People in a courtroom", words:["jury","witness","defendant","judge"] },
          { label:"Crimes",                words:["fraud","murder","laundering","theft"] },
          { label:"The court found you did it", words:["convicted","guilty","sentenced","condemned"] },
          { label:"Punishments",           words:["imprisonment","fine","probation","curfew"] } ] }},
      {v:200, q:"The world of work — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Sectors of work",    words:["financial","retail","construction","agricultural"] },
          { label:"Leave and benefits", words:["flexitime","sabbatical","paternity","pension"] },
          { label:"Losing your job",    words:["redundancy","dismissal","sacking","layoffs"] },
          { label:"Qualifications",     words:["degree","diploma","certificate","apprenticeship"] } ] }},
      {v:300, q:"Memory and speculation — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Ways to remember",       words:["recall","remember","recollect","reminisce"] },
          { label:"Showing you are certain",words:["definitely","certainly","undoubtedly","clearly"] },
          { label:"Describing a memory",    words:["vague","vivid","painful","lasting"] },
          { label:"Rough guessing",         words:["guess","estimate","reckon","suppose"] } ] }},
      {v:400, q:"Building an opinion essay — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Adding a point",       words:["moreover","furthermore","besides","additionally"] },
          { label:"Parts of an essay",    words:["introduction","argument","counterargument","conclusion"] },
          { label:"Narrowing to one case",words:["notably","especially","particularly","chiefly"] },
          { label:"What applicants worry about", words:["privacy","discrimination","transparency","fairness"] } ] }},
      {v:500, q:"Rights and processes — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Before a trial",         words:["arrested","charged","remanded","questioned"] },
          { label:"Ways to say “required”", words:["compulsory","mandatory","required","obliged"] },
          { label:"Checking an applicant",  words:["trawling","screening","vetting","researching"] },
          { label:"Types of workplace",     words:["office","warehouse","site","farm"] } ] }},
    ]},
  ],

  /* What a teacher can tick in Race, Blockbusters and Millionaire. Each section
     splits into the two strands the coursebook itself uses — the vocabulary and
     the grammar/skill focus — so "just the relative clauses" is now selectable.
     Counts are computed from the banks at render time, never written here. */
  topicNames: {
    '5A-grammar': '5A · Relative clauses',
    '5A-vocab': '5A · Crime & justice',
    '5B-grammar': '5B · Obligation & permission',
    '5B-vocab': '5B · Employment & pay',
    '5C-vocab': '5C · Recalling & speculating',
    '5D-grammar': '5D · Linkers',
    '5D-vocab': '5D · Essay writing',
  },

  /* ---- Bingo calls ----------------------------------------------------------
     These were the Blockbusters bank until that board went all-rounds. A bingo
     call is a clue with one single-word answer, which is exactly what a round
     hexagon is not — a Connections set has four answers and a scale has five — so
     the two could not stay one list. Bingo reads `bingoBank` when a unit has one
     and falls back to `blockbustersBank` when it does not, which is every unit
     that has not been converted.
     Fields: section, topic, letter (unused by Bingo, kept so a call can go back
     on a hexagon), clue, answer (one word). */
  bingoBank: [
    {section:'5A', topic:'5A-vocab', type:'anagram', letter:'V', clue:"Unscramble: the decision a jury delivers.", answer:"Verdict"},
    {section:'5B', topic:'5B-vocab', type:'anagram', letter:'W', clue:"Unscramble: the money paid for a week's work.", answer:"Wages"},
    {section:'5C', topic:'5C-vocab', type:'anagram', letter:'H', clue:"Unscramble: a guess based on very little evidence.", answer:"Hunch"},
    {section:'5D', topic:'5D-vocab', type:'anagram', letter:'C', clue:"Unscramble: the paragraph that closes an essay.", answer:"Conclusion"},
    {section:'5A', topic:'5A-vocab', type:'oddoneout', letter:'S', clue:"Which does NOT belong: verdict / jury / sabbatical", answer:"Sabbatical"},
    {section:'5B', topic:'5B-vocab', type:'oddoneout', letter:'T', clue:"Which does NOT belong: salary / bonus / testimony", answer:"Testimony"},
    {section:'5C', topic:'5C-vocab', type:'oddoneout', letter:'B', clue:"Which does NOT belong: reckon / suspect / burgle", answer:"Burgle"},
    {section:'5D', topic:'5D-vocab', type:'oddoneout', letter:'A', clue:"Which does NOT belong: however / moreover / arrest", answer:"Arrest"},
    {section:'5A', topic:'5A-vocab', letter:'F', clue:"A financial crime of deception for personal gain.", answer:"Fraud"},
    {section:'5A', topic:'5A-vocab', letter:'M', clue:"The most serious crime — unlawful killing.", answer:"Murder"},
    {section:'5A', topic:'5A-vocab', letter:'C', clue:"Held before trial: held in ___.", answer:"Custody"},
    {section:'5A', topic:'5A-vocab', letter:'T', clue:"'He gave ___ against his former business partner' — a witness's sworn account.", answer:"Testimony"},
    {section:'5A', topic:'5A-vocab', letter:'A', clue:"A claim that you were elsewhere when the crime happened.", answer:"Alibi"},
    {section:'5A', topic:'5A-vocab', letter:'V', clue:"The court's decision: guilty or not guilty.", answer:"Verdict"},
    {section:'5A', topic:'5A-vocab', letter:'J', clue:"The group of ordinary citizens who decide guilt.", answer:"Jury"},
    {section:'5A', topic:'5A-vocab', letter:'W', clue:"Someone who saw the crime happen.", answer:"Witness"},
    {section:'5A', topic:'5A-vocab', letter:'P', clue:"The lawyers trying to prove the accused is guilty.", answer:"Prosecution"},
    {section:'5A', topic:'5A-vocab', letter:'S', clue:"The punishment a judge hands down.", answer:"Sentence"},
    {section:'5A', topic:'5A-vocab', letter:'I', clue:"'Life ___' — being locked up for the rest of your life.", answer:"Imprisonment"},
    {section:'5A', topic:'5A-vocab', letter:'R', clue:"Helping offenders return to normal life in society.", answer:"Rehabilitation"},
    {section:'5A', topic:'5A-vocab', letter:'B', clue:"'___ from driving' — stopped from driving as a punishment.", answer:"Banned"},
    {section:'5A', topic:'5A-vocab', letter:'L', clue:"Money ___ — hiding where illegally-earned cash came from.", answer:"Laundering"},
    {section:'5A', topic:'5A-vocab', letter:'G', clue:"'Found ___ of the crime' — the opposite of innocent.", answer:"Guilty"},
    {section:'5A', topic:'5A-vocab', letter:'D', clue:"The ___ lawyer argues on behalf of the accused.", answer:"Defence"},
    {section:'5A', topic:'5A-vocab', letter:'O', clue:"The formal word for a crime or illegal act.", answer:"Offence"},
    {section:'5A', topic:'5A-vocab', letter:'S', clue:"Kept apart from all other prisoners: '___ confinement'.", answer:"Solitary"},
    {section:'5B', topic:'5B-vocab', letter:'F', clue:"Banking and investment belong to this sector.", answer:"Financial"},
    {section:'5B', topic:'5B-vocab', letter:'A', clue:"Farming belongs to this sector.", answer:"Agricultural"},
    {section:'5B', topic:'5B-vocab', letter:'C', clue:"Building houses and roads: this sector.", answer:"Construction"},
    {section:'5B', topic:'5B-vocab', letter:'R', clue:"Shops and selling to customers: this sector.", answer:"Retail"},
    {section:'5B', topic:'5B-vocab', letter:'M', clue:"Making goods in factories: this sector.", answer:"Manufacturing"},
    {section:'5B', topic:'5B-vocab', letter:'T', clue:"Moving goods and people around: this sector.", answer:"Transport"},
    {section:'5B', topic:'5B-vocab', letter:'E', clue:"Oil, gas and electricity: this sector.", answer:"Energy"},
    {section:'5B', topic:'5B-vocab', letter:'P', clue:"Government-run services: the ___ sector.", answer:"Public"},
    {section:'5B', topic:'5B-vocab', letter:'S', clue:"A distinct area of the economy.", answer:"Sector"},
    {section:'5B', topic:'5B-vocab', letter:'R', clue:"Job cuts that make workers lose their jobs.", answer:"Redundancies"},
    {section:'5B', topic:'5B-vocab', letter:'F', clue:"A benefit that lets you choose your own working hours.", answer:"Flexitime"},
    {section:'5B', topic:'5B-vocab', letter:'S', clue:"A long paid career break, often six months.", answer:"Sabbatical"},
    {section:'5B', topic:'5B-vocab', letter:'P', clue:"Leave for the new father, as opposed to maternity leave.", answer:"Paternity"},
    {section:'5B', topic:'5B-vocab', letter:'M', clue:"A ___ requirement is one you absolutely MUST meet.", answer:"Mandatory"},
    {section:'5B', topic:'5B-grammar', letter:'O', clue:"'You are ___ to wear protective clothing' — formal strong obligation (be ___).", answer:"Obliged"},
    {section:'5B', topic:'5B-vocab', letter:'Q', clue:"The training and certificates a job requires.", answer:"Qualifications"},
    {section:'5B', topic:'5B-grammar', letter:'F', clue:"'Visitors are ___ to bring food into the building' — formal refusal of permission.", answer:"Forbidden"},
    {section:'5B', topic:'5B-grammar', letter:'E', clue:"'How can she be ___ to be in two places at once?' — mild obligation.", answer:"Expected"},
    {section:'5B', topic:'5B-vocab', letter:'S', clue:"'I was ___ to read the report by today' — what the rules said I'd do.", answer:"Supposed"},
    {section:'5B', topic:'5B-vocab', letter:'A', clue:"'It is ___ to wear protective clothing' — formal advice, not an order.", answer:"Advisable"},
    {section:'5C', topic:'5C-vocab', letter:'M', clue:"'If my ___ serves me correctly…'", answer:"Memory"},
    {section:'5C', topic:'5C-vocab', letter:'I', clue:"A belief you held that turned out to be wrong — you were 'under' one.", answer:"Impression"},
    {section:'5C', topic:'5C-vocab', letter:'H', clue:"'I'd ___ a guess that…' — make a rough estimate.", answer:"Hazard"},
    {section:'5C', topic:'5C-vocab', letter:'G', clue:"'I'd hazard a ___ that…'", answer:"Guess"},
    {section:'5C', topic:'5C-vocab', letter:'S', clue:"To ___ out is to be the one detail you remember most vividly.", answer:"Stands"},
    {section:'5C', topic:'5C-vocab', letter:'P', clue:"'___ nothing goes wrong, we'll be finished by six' — assuming, without checking.", answer:"Presuming"},
    {section:'5C', topic:'5C-vocab', letter:'D', clue:"'No ___ you heard that from…' — a confident assumption.", answer:"Doubt"},
    {section:'5C', topic:'5C-vocab', letter:'R', clue:"To ___ something is to bring a past event back to mind.", answer:"Recall"},
    {section:'5C', topic:'5C-vocab', letter:'S', clue:"To ___ is to guess about something you're not sure of.", answer:"Speculate"},
    {section:'5D', topic:'5D-grammar', letter:'M', clue:"A one-word linker meaning 'in addition', used to start a new sentence.", answer:"Moreover"},
    {section:'5D', topic:'5D-grammar', letter:'F', clue:"Another one-word linker meaning 'what is more' — often the final point.", answer:"Furthermore"},
    {section:'5D', topic:'5D-grammar', letter:'B', clue:"'___, time saved is money saved' — adds a reinforcing point.", answer:"Besides"},
    {section:'5D', topic:'5D-vocab', letter:'A', clue:"'___ all' — the phrase marking your most important argument.", answer:"Above"},
    {section:'5D', topic:'5D-grammar', letter:'P', clue:"'In ___' — a linker that narrows to one specific case.", answer:"Particular"},
    {section:'5D', topic:'5D-vocab', letter:'I', clue:"The paragraph that outlines the topic and catches the reader's interest.", answer:"Introduction"},
    {section:'5D', topic:'5D-vocab', letter:'C', clue:"The final paragraph, where you give your balanced opinion.", answer:"Conclusion"},
    {section:'5D', topic:'5D-vocab', letter:'B', clue:"A good conclusion gives a ___ opinion of both arguments.", answer:"Balanced"},
    {section:'5D', topic:'5D-vocab', letter:'T', clue:"Employers going '___' are actively hunting for negative posts.", answer:"Trawling"},
    {section:'5D', topic:'5D-vocab', letter:'D', clue:"To treat someone unfairly because of their age or medical history.", answer:"Discriminate"},
    {section:'5D', topic:'5D-vocab', letter:'P', clue:"Applicants have voiced ___ concerns about social media checks.", answer:"Privacy"},
    {section:'5D', topic:'5D-vocab', letter:'S', clue:"The ___ process is how a company chooses between applicants.", answer:"Selection"},
    {section:'5D', topic:'5D-vocab', letter:'T', clue:"Checks need to be fair and ___ — open and easy to see.", answer:"Transparent"},
    {section:'5D', topic:'5D-vocab', letter:'G', clue:"'___ or laws' are needed to restrict what employers may research.", answer:"Guidelines"},
    {section:'5C', topic:'5C-vocab', letter:'M', clue:"'It's slipped my ___' — I've forgotten it.", answer:"Mind"},
    {section:'5A', topic:'5A-vocab', letter:'C', clue:"The formal record that a court has found you guilty.", answer:"Conviction"},
    {section:'5A', topic:'5A-vocab', letter:'C', clue:"The adjective in both '___ record' and '___ damage'.", answer:"Criminal"},
    {section:'5A', topic:'5A-vocab', letter:'I', clue:"The opposite of a guilty verdict.", answer:"Innocent"},
    {section:'5A', topic:'5A-vocab', letter:'A', clue:"Change the noun 'accusation' into the past participle: 'he was ___ of fraud'.", answer:"Accused"},
    {section:'5B', topic:'5B-vocab', letter:'R', clue:"Change the adjective 'redundant' into the noun for the job cuts.", answer:"Redundancy"},
    {section:'5B', topic:'5B-vocab', letter:'O', clue:"Change the verb 'oblige' into the noun for a duty you must fulfil.", answer:"Obligation"},
    {section:'5B', topic:'5B-vocab', letter:'P', clue:"Change the verb 'permit' into the noun for official approval.", answer:"Permission"},
    {section:'5B', topic:'5B-vocab', letter:'M', clue:"Give another word for 'compulsory' — something you absolutely must do.", answer:"Mandatory"},
    {section:'5C', topic:'5C-vocab', letter:'S', clue:"Change the verb 'to speculate' into the noun.", answer:"Speculation"},
    {section:'5C', topic:'5C-vocab', letter:'A', clue:"Change the verb 'assume' into the noun for something taken for granted.", answer:"Assumption"},
    {section:'5C', topic:'5C-vocab', letter:'I', clue:"Change the verb 'impress' into the noun used in 'I was under the ___'.", answer:"Impression"},
    {section:'5C', topic:'5C-vocab', letter:'V', clue:"Which adjective describes a memory that is unclear or hazy?", answer:"Vague"},
  ],

  /* Every hexagon on this board is a **round**. The letter is the hexagon's name —
     it is how a team says which square they are attacking, and it is what the
     picking vote counts — not a constraint on the answer, because a round has no
     single-word answer to match against.

     **Every question here is a different question from the Jeopardy column on the
     same language**, not the same one reworded. That is the per-game authoring
     rule (§3.2) and the content gate enforces it: the first draft of this bank
     reused the Jeopardy sets and the gate found 47 of them. Same *answer* in two
     games is spaced retrieval working; same *prompt* is the thing the rule exists
     to stop.

     Filed with each other rather than in a section of their own, and the surprise
     is the point: a Jeopardy column announces its question type in the heading, a
     hexagon does not. Eighteen per section, because eighteen is the board. */
  blockbustersBank: [
    /* ---- 5A: crime & justice ---- */
    {section:'5A', topic:'5A-vocab', letter:'P', clue:"Four of these are places a person can be held. Find the four.",
      group:{ pick:["prison","cell","custody","remand"], with:["verdict","appeal","plea","bail"] }},
    {section:'5A', topic:'5A-vocab', letter:'W', clue:"Four of these mean breaking the law. Find the four.",
      group:{ pick:["offence","crime","violation","breach"], with:["sentence","verdict","appeal","custody"] }},
    {section:'5A', topic:'5A-vocab', letter:'N', clue:"Eight punishments. Find the four that do NOT involve being locked up.",
      group:{ pick:["fine","probation","curfew","community"], with:["imprisonment","custody","confinement","detention"] }},
    {section:'5A', topic:'5A-vocab', letter:'J', clue:"Four of these argue for the accused. Find the four.",
      group:{ pick:["defence","solicitor","barrister","advocate"], with:["prosecution","plaintiff","magistrate","bailiff"] }},
    {section:'5A', topic:'5A-vocab', letter:'E', clue:"Four of these mean the court let you go. Find the four.",
      group:{ pick:["acquitted","cleared","exonerated","pardoned"], with:["convicted","sentenced","charged","remanded"] }},
    {section:'5A', topic:'5A-vocab', letter:'R', clue:"Put these in order — least free first.",
      order:{ scale:["solitary","imprisonment","custody","curfew","probation"],
              low:"no freedom at all", high:"nearly free",
              gloss:{ solitary:"alone in a cell, apart from everyone.",
                      imprisonment:"in prison with the other inmates.",
                      custody:"held, but usually short-term and before trial.",
                      curfew:"at home, but only between certain hours.",
                      probation:"out in the world, reporting to an officer." } }},
    {section:'5A', topic:'5A-vocab', letter:'D', clue:"Put these in order — least dishonest first.",
      order:{ scale:["misleading","dishonest","deceitful","fraudulent","criminal"],
              low:"careless with the truth", high:"a matter for the courts",
              gloss:{ misleading:"gives the wrong impression — may be an accident.",
                      dishonest:"not telling the truth, deliberately.",
                      deceitful:"lying as a habit, to gain something.",
                      fraudulent:"lying for money — the legal word.",
                      criminal:"the law is now involved." } }},
    {section:'5A', topic:'5A-vocab', letter:'K', clue:"Put these in order — least harm done first.",
      order:{ scale:["trespass","vandalism","burglary","robbery","murder"],
              low:"you should not be there", high:"the gravest crime of all",
              gloss:{ trespass:"being on land that is not yours.",
                      vandalism:"damaging property deliberately.",
                      burglary:"entering a building to steal.",
                      robbery:"stealing with force or the threat of it.",
                      murder:"unlawful killing." } }},
    {section:'5A', topic:'5A-grammar', letter:'H', clue:"'This is the colleague ___ I share an office.'",
      choice:{ options:["with whom","whom","who","that"], answer:"with whom" }},
    {section:'5A', topic:'5A-grammar', letter:'X', clue:"'The house ___ roof was damaged has been sold.'",
      choice:{ options:["whose","who's","which","that"], answer:"whose" }},
    {section:'5A', topic:'5A-grammar', letter:'Y', clue:"'The prison ___ he was held has now closed.'",
      choice:{ options:["where","which","who","whose"], answer:"where" }},
    {section:'5A', topic:'5A-vocab', letter:'Q', clue:"Which one is decided by the jury rather than the judge?",
      choice:{ options:["the verdict","the sentence","the appeal","the charge"], answer:"the verdict" }},
    {section:'5A', topic:'5A-grammar', letter:'Z', clue:"Put the words in order — the clause defines which one.",
      scramble:{ sentence:"The evidence that convicted him was purely circumstantial" }},
    {section:'5A', topic:'5A-grammar', letter:'U', clue:"Put the words in order — mind the commas.",
      scramble:{ sentence:"Halden prison, which opened in 2010, is humane" }},
    {section:'5A', topic:'5A-vocab', letter:'V', clue:"the person a crime was committed against", anagram:{ word:"victim" }},
    {section:'5A', topic:'5A-vocab', letter:'A', clue:"a formal claim that somebody has done wrong", anagram:{ word:"allegation" }},
    {section:'5A', topic:'5A-vocab', letter:'F', clue:"the crime of tricking people out of money", anagram:{ word:"fraud" }},
    {section:'5A', topic:'5A-vocab', letter:'S', clue:"the person the police believe did it", anagram:{ word:"suspect" }},

    /* ---- 5B: employment, pay & obligation ---- */
    {section:'5B', topic:'5B-vocab', letter:'S', clue:"Four of these name a part of the economy. Find the four.",
      group:{ pick:["retail","transport","energy","manufacturing"], with:["flexitime","sabbatical","paternity","pension"] }},
    {section:'5B', topic:'5B-vocab', letter:'B', clue:"Four of these are perks rather than industries. Find the perks.",
      group:{ pick:["flexitime","sabbatical","paternity","pension"], with:["financial","retail","construction","agricultural"] }},
    {section:'5B', topic:'5B-grammar', letter:'N', clue:"Four of these leave you no way out. Find the four.",
      group:{ pick:["compulsory","mandatory","required","obliged"], with:["optional","voluntary","advisable","discretionary"] }},
    {section:'5B', topic:'5B-vocab', letter:'L', clue:"Four of these mean your job has ended. Find the four.",
      group:{ pick:["redundancy","dismissal","sacking","layoffs"], with:["recruitment","promotion","appointment","hiring"] }},
    {section:'5B', topic:'5B-vocab', letter:'G', clue:"Four of these you earn by studying. Find the four.",
      group:{ pick:["degree","diploma","certificate","apprenticeship"], with:["salary","bonus","commission","wages"] }},
    {section:'5B', topic:'5B-grammar', letter:'O', clue:"Put these in order — starting with the one you may ignore.",
      order:{ scale:["optional","advisable","expected","required","compulsory"],
              low:"entirely up to you", high:"no choice at all",
              gloss:{ optional:"nobody minds either way.",
                      advisable:"a good idea, and that is all.",
                      expected:"people will notice if you do not.",
                      required:"the rules say you do it.",
                      compulsory:"there is no way out of it." } }},
    {section:'5B', topic:'5B-grammar', letter:'T', clue:"Put these in order — starting with what is never allowed.",
      order:{ scale:["forbidden","discouraged","tolerated","permitted","encouraged"],
              low:"never, under any circumstances", high:"please do",
              gloss:{ forbidden:"formally not allowed — the strongest refusal.",
                      discouraged:"allowed, but they would rather you did not.",
                      tolerated:"nobody stops you, nobody approves.",
                      permitted:"officially allowed.",
                      encouraged:"they actively want you to." } }},
    {section:'5B', topic:'5B-vocab', letter:'J', clue:"Put these in order — lowest position first.",
      order:{ scale:["intern","trainee","assistant","manager","director"],
              low:"just arrived", high:"runs the place",
              gloss:{ intern:"often unpaid, and there to learn.",
                      trainee:"employed, but still being taught the job.",
                      assistant:"doing the job, supporting someone senior.",
                      manager:"responsible for other people's work.",
                      director:"sets what the organisation does." } }},
    {section:'5B', topic:'5B-vocab', letter:'K', clue:"Put these in order — the job most easily lost first.",
      order:{ scale:["casual","temporary","probationary","permanent","tenured"],
              low:"could end today", high:"almost impossible to end",
              gloss:{ casual:"paid by the shift, with no promise of another.",
                      temporary:"a fixed end date from the start.",
                      probationary:"permanent in name, but they can still let you go.",
                      permanent:"no end date, and proper notice required.",
                      tenured:"protected by contract — you keep the post." } }},
    {section:'5B', topic:'5B-grammar', letter:'H', clue:"'She ___ work Saturdays — it is in her contract.'",
      choice:{ options:["has to","must","ought to","had better"], answer:"has to" }},
    {section:'5B', topic:'5B-grammar', letter:'P', clue:"'We ___ to leave early yesterday' — the past of 'must'.",
      choice:{ options:["had","must","have","ought"], answer:"had" }},
    {section:'5B', topic:'5B-grammar', letter:'X', clue:"'You ___ touch that — it is live.' Strong prohibition.",
      choice:{ options:["mustn't","don't have to","needn't","shouldn't"], answer:"mustn't" }},
    {section:'5B', topic:'5B-vocab', letter:'C', clue:"Which sector would a wind farm belong to?",
      choice:{ options:["energy","retail","financial","agricultural"], answer:"energy" }},
    {section:'5B', topic:'5B-grammar', letter:'Y', clue:"Put the words in order — the rule applies to everyone.",
      scramble:{ sentence:"All staff must complete the safety course first" }},
    {section:'5B', topic:'5B-grammar', letter:'Z', clue:"Put the words in order — no obligation at all.",
      scramble:{ sentence:"We do not have to be there until nine" }},
    {section:'5B', topic:'5B-vocab', letter:'W', clue:"everyone a company employs, taken together", anagram:{ word:"workforce" }},
    {section:'5B', topic:'5B-vocab', letter:'A', clue:"someone learning a trade while working at it", anagram:{ word:"apprentice" }},
    {section:'5B', topic:'5B-vocab', letter:'F', clue:"not allowed, in the most formal way", anagram:{ word:"forbidden" }},

    /* ---- 5C: recalling & speculating ---- */
    {section:'5C', topic:'5C-vocab', letter:'R', clue:"Four of these are about remembering. Find the four.",
      group:{ pick:["recall","remember","recollect","reminisce"], with:["speculate","presume","assume","suppose"] }},
    {section:'5C', topic:'5C-vocab', letter:'E', clue:"Four of these turn up in memory idioms. Find the four.",
      group:{ pick:["serves","stands","slipped","crossed"], with:["hazard","presume","reckon","gather"] }},
    {section:'5C', topic:'5C-vocab', letter:'C', clue:"Four of these leave no room for doubt. Find the four.",
      group:{ pick:["definitely","certainly","undoubtedly","clearly"], with:["possibly","perhaps","presumably","arguably"] }},
    {section:'5C', topic:'5C-vocab', letter:'W', clue:"Four of these can describe a memory. Find the four.",
      group:{ pick:["vague","vivid","painful","lasting"], with:["heavy","loud","narrow","steep"] }},
    {section:'5C', topic:'5C-vocab', letter:'B', clue:"Four of these settle a question. Find those four.",
      group:{ pick:["confirm","verify","prove","establish"], with:["guess","estimate","reckon","suppose"] }},
    {section:'5C', topic:'5C-vocab', letter:'O', clue:"Put these in order — starting with the biggest guess.",
      order:{ scale:["possibly","probably","presumably","definitely","undoubtedly"],
              low:"a wild guess", high:"no doubt at all",
              gloss:{ possibly:"it might be true, and might not.",
                      probably:"more likely than not.",
                      presumably:"you assume it, without checking.",
                      definitely:"you are sure.",
                      undoubtedly:"nobody could reasonably disagree." } }},
    {section:'5C', topic:'5C-vocab', letter:'F', clue:"Put these in order — the dimmest memory first.",
      order:{ scale:["forgotten","hazy","vague","clear","vivid"],
              low:"gone completely", high:"as if it were yesterday",
              gloss:{ forgotten:"nothing is left of it at all.",
                      hazy:"you know it happened, and little more.",
                      vague:"the outline, none of the detail.",
                      clear:"you can describe it accurately.",
                      vivid:"you can still see and hear it." } }},
    {section:'5C', topic:'5C-vocab', letter:'L', clue:"Put these in order — the source you would trust least first.",
      order:{ scale:["rumour","hunch","impression","recollection","record"],
              low:"someone said so", high:"written down at the time",
              gloss:{ rumour:"passed along, from nobody in particular.",
                      hunch:"a feeling, with nothing behind it.",
                      impression:"what you took away — often wrong.",
                      recollection:"what you actually remember.",
                      record:"written down, and checkable." } }},
    {section:'5C', topic:'5C-vocab', letter:'N', clue:"Put these in order — starting with the loosest hold on it.",
      order:{ scale:["wondered","suspected","believed","knew","witnessed"],
              low:"the thought crossed your mind", high:"you were there",
              gloss:{ wondered:"it occurred to you as a possibility.",
                      suspected:"you leaned towards it being true.",
                      believed:"you took it to be true.",
                      knew:"you had no doubt.",
                      witnessed:"you saw it happen yourself." } }},
    {section:'5C', topic:'5C-vocab', letter:'M', clue:"'That name doesn't ___ a bell.'",
      choice:{ options:["ring","sound","hit","knock"], answer:"ring" }},
    {section:'5C', topic:'5C-vocab', letter:'Z', clue:"'I ___ she must have known all along.'",
      choice:{ options:["reckon","count","number","tell"], answer:"reckon" }},
    {section:'5C', topic:'5C-vocab', letter:'T', clue:"'It ___ my mind that she might already know.'",
      choice:{ options:["crossed","passed","went","ran"], answer:"crossed" }},
    {section:'5C', topic:'5C-vocab', letter:'D', clue:"'___ nothing goes wrong, we finish by six.'",
      choice:{ options:["Presuming","Presumed","Presume","Presumption"], answer:"Presuming" }},
    {section:'5C', topic:'5C-vocab', letter:'Y', clue:"Put the words in order — reporting what you heard.",
      scramble:{ sentence:"I gather she had already handed in her notice" }},
    {section:'5C', topic:'5C-vocab', letter:'X', clue:"Put the words in order — the name will not come.",
      scramble:{ sentence:"Her name has completely escaped me again today" }},
    {section:'5C', topic:'5C-vocab', letter:'H', clue:"to venture a guess you are not sure of", anagram:{ word:"hazard" }},
    {section:'5C', topic:'5C-vocab', letter:'I', clue:"what you took away, though it proved wrong", anagram:{ word:"impression" }},
    {section:'5C', topic:'5C-vocab', letter:'V', clue:"sharp and detailed — said of a memory", anagram:{ word:"vivid" }},

    /* ---- 5D: opinion essays & linking ---- */
    {section:'5D', topic:'5D-grammar', letter:'A', clue:"Four of these add a point. Find the four that add.",
      group:{ pick:["moreover","furthermore","besides","additionally"], with:["however","nevertheless","whereas","conversely"] }},
    {section:'5D', topic:'5D-vocab', letter:'E', clue:"Four of these are sections of an essay. Find the four.",
      group:{ pick:["introduction","argument","counterargument","conclusion"], with:["heading","footnote","caption","index"] }},
    {section:'5D', topic:'5D-grammar', letter:'N', clue:"Four of these narrow to one case. Find the four.",
      group:{ pick:["notably","especially","particularly","chiefly"], with:["moreover","besides","furthermore","additionally"] }},
    {section:'5D', topic:'5D-vocab', letter:'K', clue:"Four of these are what a recruiter does to you. Find the four.",
      group:{ pick:["trawling","screening","vetting","researching"], with:["hiring","promoting","training","paying"] }},
    {section:'5D', topic:'5D-vocab', letter:'Q', clue:"Four of these are what applicants object to. Find the four.",
      group:{ pick:["privacy","discrimination","transparency","fairness"], with:["salary","overtime","bonus","pension"] }},
    {section:'5D', topic:'5D-vocab', letter:'P', clue:"Put these in order — the order you write them in.",
      order:{ scale:["introduction","argument","counterargument","evaluation","conclusion"],
              low:"opens the essay", high:"closes the essay",
              gloss:{ introduction:"outlines the topic and catches the reader's interest.",
                      argument:"the case for one side, with support.",
                      counterargument:"the case for the other side, given fairly.",
                      evaluation:"weighing the two against each other.",
                      conclusion:"your balanced opinion — and no new information." } }},
    {section:'5D', topic:'5D-grammar', letter:'L', clue:"Put these in order — chattiest first.",
      order:{ scale:["plus","and","also","moreover","furthermore"],
              low:"a text message", high:"an academic essay",
              gloss:{ plus:"spoken English only — never write it in an essay.",
                      and:"joins two things inside a sentence.",
                      also:"neutral, and fine in most writing.",
                      moreover:"formal, and starts a new sentence.",
                      furthermore:"the most formal of the four." } }},
    {section:'5D', topic:'5D-vocab', letter:'W', clue:"Put these in order — starting with the most cautious verb.",
      order:{ scale:["suggests","indicates","shows","demonstrates","proves"],
              low:"hints at it", high:"settles it",
              gloss:{ suggests:"points that way, without insisting.",
                      indicates:"the evidence leans this way.",
                      shows:"makes it visible.",
                      demonstrates:"makes it plain, step by step.",
                      proves:"leaves nothing to argue about." } }},
    {section:'5D', topic:'5D-vocab', letter:'G', clue:"Put these in order — the quickest look first.",
      order:{ scale:["glance","skim","read","study","scrutinise"],
              low:"barely looks", high:"goes through every line",
              gloss:{ glance:"a second, at most.",
                      skim:"picks up the gist and moves on.",
                      read:"the ordinary word — start to finish.",
                      study:"reads it in order to understand it properly.",
                      scrutinise:"examines it looking for something wrong." } }},
    {section:'5D', topic:'5D-vocab', letter:'C', clue:"Which paragraph outlines the topic and hooks the reader?",
      choice:{ options:["the introduction","the conclusion","paragraph three","the evaluation"], answer:"the introduction" }},
    {section:'5D', topic:'5D-vocab', letter:'X', clue:"Where does the writer's balanced opinion belong?",
      choice:{ options:["the last paragraph","the first paragraph","paragraph two","a footnote"], answer:"the last paragraph" }},
    {section:'5D', topic:'5D-grammar', letter:'S', clue:"Which linker is too informal for an essay?",
      choice:{ options:["plus","moreover","furthermore","in addition"], answer:"plus" }},
    {section:'5D', topic:'5D-grammar', letter:'B', clue:"Which one contrasts rather than adds?",
      choice:{ options:["nevertheless","moreover","besides","furthermore"], answer:"nevertheless" }},
    {section:'5D', topic:'5D-grammar', letter:'Y', clue:"Put the words in order — adding a further point.",
      scramble:{ sentence:"Furthermore many applicants never learn what was found" }},
    {section:'5D', topic:'5D-vocab', letter:'Z', clue:"Put the words in order — the writer's main point.",
      scramble:{ sentence:"Above all the selection process must remain transparent" }},
    {section:'5D', topic:'5D-vocab', letter:'T', clue:"actively hunting through somebody's old posts", anagram:{ word:"trawling" }},
    {section:'5D', topic:'5D-vocab', letter:'D', clue:"fair to both sides of an argument", anagram:{ word:"balanced" }},
    {section:'5D', topic:'5D-vocab', letter:'M', clue:"official advice a company is expected to follow", anagram:{ word:"guidelines" }},
  ],

  blockbustersSectionNames: {
    '5A':'5A · Crime & justice (18 rounds)',
    '5B':'5B · Employment & obligation (18 rounds)',
    '5C':'5C · Recalling & speculating (18 rounds)',
    '5D':'5D · Opinion essays & linking (18 rounds)',
  },

  /* ---- Race to the Board ----------------------------------------------------
     Gapped sentences, not definitions. The words themselves are on screen, so
     the prompt tests collocation and word form in context — a different angle on
     the same target language from Jeopardy's Q&A and Blockbusters' definitions.
     Distractors are not authored: every other word on the board is a real target
     word from the selected sections, so wrong taps are still teachable.
     Fields: section, prompt (use ___ for the gap), answer (one word). */
  raceBank: [
    {section:'5B', topic:'5B-vocab', type:'errorfix', prompt:"Correct it: 'Helmets are *compulsary* on this site.'", answer:"Compulsory"},
    /* ---- 5A: crime & justice ---- */
    {section:'5A', topic:'5A-vocab', prompt:"The jury returned a ___ of not guilty after six hours.", answer:"Verdict"},
    {section:'5A', topic:'5A-vocab', prompt:"He was held in ___ for three months before the trial began.", answer:"Custody"},
    {section:'5A', topic:'5A-vocab', prompt:"She has a solid ___ — she was at work when the robbery happened.", answer:"Alibi"},
    {section:'5A', topic:'5A-vocab', prompt:"The ___ lawyer argued there was no evidence against her client.", answer:"Defence"},
    {section:'5A', topic:'5A-vocab', prompt:"He was ___ of fraud and sentenced to two years.", answer:"Convicted"},
    {section:'5A', topic:'5A-vocab', prompt:"The judge handed down a five-year ___.", answer:"Sentence"},
    {section:'5A', topic:'5A-vocab', prompt:"The ___ called three witnesses to prove the case.", answer:"Prosecution"},
    {section:'5A', topic:'5A-vocab', prompt:"Instead of prison, he was ordered to do 200 hours of ___ service.", answer:"Community"},
    {section:'5A', topic:'5A-vocab', prompt:"The prison in Norway focuses on ___ rather than punishment.", answer:"Rehabilitation"},
    {section:'5A', topic:'5A-vocab', prompt:"Her ___ in court contradicted what she had told the police.", answer:"Testimony"},
    {section:'5A', topic:'5A-vocab', prompt:"He was ___ from driving for eighteen months.", answer:"Banned"},
    {section:'5A', topic:'5A-vocab', prompt:"Prisoners who attack staff can be put in ___ confinement.", answer:"Solitary"},

    /* Relative pronouns as board tiles — the format Grammar Focus 5A fits best of
       all four games. Every pronoun is one word and none repeats, so each gets its
       own tile and the whole set sits on the board at once: you read the sentence,
       a student has to pick the right pronoun out of the nine plausible ones.
       That is a genuinely harder discrimination than a gap fill on paper, where
       only one or two would ever be candidates. */
    {section:'5A', topic:'5A-grammar', prompt:"The officer ___ arrested him has since retired.", answer:"Who"},
    {section:'5A', topic:'5A-grammar', prompt:"The witness ___ the police interviewed has disappeared.", answer:"Whom"},
    {section:'5A', topic:'5A-grammar', prompt:"It's up to the person ___ job it is to arrange the transport.", answer:"Whose"},
    {section:'5A', topic:'5A-grammar', prompt:"She lied on her interview form, ___ was a bad sign.", answer:"Which"},
    {section:'5A', topic:'5A-grammar', prompt:"Take me somewhere ___ I can relax for a few days.", answer:"Where"},
    {section:'5A', topic:'5A-grammar', prompt:"The 1930s was the time ___ organised crime flourished.", answer:"When"},
    {section:'5A', topic:'5A-grammar', prompt:"Does anyone know the reason ___ crime is so high here?", answer:"Why"},
    {section:'5A', topic:'5A-grammar', prompt:"___ stole my lunch from the fridge is in big trouble.", answer:"Whoever"},
    {section:'5A', topic:'5A-grammar', prompt:"You're free to choose ___ position you want.", answer:"Whatever"},

    /* ---- 5B: employment, pay & obligation ---- */
    {section:'5B', topic:'5B-vocab', prompt:"After twelve years at the firm she took a six-month ___ to travel.", answer:"Sabbatical"},
    {section:'5B', topic:'5B-vocab', prompt:"___ means staff can choose when they start and finish work.", answer:"Flexitime"},
    {section:'5B', topic:'5B-vocab', prompt:"The company announced 200 ___ after a sharp fall in sales.", answer:"Redundancies"},
    {section:'5B', topic:'5B-vocab', prompt:"New fathers are entitled to two weeks' ___ leave.", answer:"Paternity"},
    {section:'5B', topic:'5B-vocab', prompt:"Safety training is ___ — every employee has to complete it.", answer:"Mandatory"},
    {section:'5B', topic:'5B-vocab', prompt:"You'll be ___ to hold a diving certificate for this role.", answer:"Required"},
    {section:'5B', topic:'5B-grammar', prompt:"Employers are legally ___ to provide protective clothing.", answer:"Obliged"},
    {section:'5B', topic:'5B-vocab', prompt:"Most of the jobs lost were in the ___ sector — factories and plants.", answer:"Manufacturing"},
    {section:'5B', topic:'5B-vocab', prompt:"Banking, insurance and investment make up the ___ sector.", answer:"Financial"},
    {section:'5B', topic:'5B-vocab', prompt:"She didn't have the right ___, so her application was rejected.", answer:"Qualifications"},
    {section:'5B', topic:'5B-vocab', prompt:"Bonuses here are ___-related — the better you do, the more you earn.", answer:"Performance"},
    {section:'5B', topic:'5B-vocab', prompt:"Schools and hospitals belong to the ___ sector.", answer:"Public"},
    /* The rest of the p147 phrase box. On the board these sit alongside 'Mandatory',
       'Required' and 'Obliged', so picking the right one is a register and strength
       judgement, not a recall test — which is exactly what the page is teaching. */
    {section:'5B', topic:'5B-grammar', prompt:"Visitors are not ___ to bring food into the building.", answer:"Permitted"},
    {section:'5B', topic:'5B-vocab', prompt:"Members of the public are ___ to go beyond this point.", answer:"Forbidden"},
    {section:'5B', topic:'5B-vocab', prompt:"Applicants are ___ to arrive ten minutes before their interview.", answer:"Expected"},
    {section:'5B', topic:'5B-vocab', prompt:"I was ___ to read the report by today, but I didn't have time.", answer:"Supposed"},
    {section:'5B', topic:'5B-vocab', prompt:"It is ___ to wear protective clothing in the workshop.", answer:"Advisable"},
    {section:'5B', topic:'5B-vocab', prompt:"It is ___ to have the right qualifications for this job.", answer:"Essential"},
    {section:'5B', topic:'5B-grammar', prompt:"We're not ___ to wear jeans to work.", answer:"Allowed"},
    {section:'5B', topic:'5B-vocab', prompt:"I have no ___ but to hand in my notice.", answer:"Choice"},

    /* ---- 5C: recalling & speculating ---- */
    {section:'5C', topic:'5C-vocab', prompt:"If my ___ serves me correctly, we met at a conference in Berlin.", answer:"Memory"},
    {section:'5C', topic:'5C-vocab', prompt:"If my memory ___ me correctly, it was a Tuesday in October.", answer:"Serves"},
    {section:'5C', topic:'5C-vocab', prompt:"I'd ___ a guess that she's about forty.", answer:"Hazard"},
    {section:'5C', topic:'5C-vocab', prompt:"I'd hazard a ___ that it cost around two thousand euros.", answer:"Guess"},
    {section:'5C', topic:'5C-vocab', prompt:"What ___ out in my mind is how quiet the room went.", answer:"Stands"},
    {section:'5C', topic:'5C-vocab', prompt:"I was under the ___ that you'd already left the company.", answer:"Impression"},
    {section:'5C', topic:'5C-vocab', prompt:"No ___ you've heard the news already.", answer:"Doubt"},
    {section:'5C', topic:'5C-vocab', prompt:"___ you're the technician, right? The server's through there.", answer:"Presuming"},
    {section:'5C', topic:'5C-vocab', prompt:"Sorry, his name has completely ___ my mind.", answer:"Slipped"},
    {section:'5C', topic:'5C-vocab', prompt:"I can't ___ exactly what she said, but it was something like that.", answer:"Recall"},
    {section:'5C', topic:'5C-vocab', prompt:"It's pointless to ___ about what might have happened.", answer:"Speculate"},
    {section:'5C', topic:'5C-vocab', prompt:"I think I ___ her saying she'd be late.", answer:"Remember"},
    /* ---- added later: transformations, opposites and collocation, so the board
           isn't only gapped sentences. Answers are deliberately new words — two
           identical tiles on one board would be unplayable. ---- */
    {section:'5A', topic:'5A-vocab', prompt:"He already had a previous ___ for fraud when he was arrested again.", answer:"Conviction"},
    {section:'5A', topic:'5A-vocab', prompt:"What is the opposite of a guilty verdict?", answer:"Innocent"},
    {section:'5A', topic:'5A-vocab', prompt:"He has no ___ record — this is his first offence.", answer:"Criminal"},
    {section:'5A', topic:'5A-vocab', prompt:"Give the formal word for a crime or illegal act.", answer:"Offence"},
    {section:'5B', topic:'5B-vocab', prompt:"Under the contract we are under no ___ to refund the deposit.", answer:"Obligation"},
    {section:'5B', topic:'5B-vocab', prompt:"You'll need written ___ from the landlord before you start work.", answer:"Permission"},
    {section:'5B', topic:'5B-vocab', prompt:"Correct the error: 'He was made redundancy last year.'", answer:"Redundant"},
    {section:'5B', topic:'5B-vocab', prompt:"Retail, transport and energy are each one of these parts of the economy.", answer:"Sector"},
    {section:'5C', topic:'5C-vocab', prompt:"The report is pure ___ — there's no evidence for any of it.", answer:"Speculation"},
    {section:'5C', topic:'5C-vocab', prompt:"The whole plan rests on the ___ that prices will keep falling.", answer:"Assumption"},
    {section:'5C', topic:'5C-vocab', prompt:"I've only a ___ memory of the meeting — it was years ago.", answer:"Vague"},
    {section:'5C', topic:'5C-vocab', prompt:"Which noun completes both 'it slipped my ___' and 'it crossed my ___'?", answer:"Mind"},

    /* ---- 5D: opinion essays & linking ----
       The linkers make good tiles for the same reason the relative pronouns did:
       one word each, none repeating, and choosing between 'Moreover' and 'Besides'
       is a real judgement rather than a recall test. */
    {section:'5D', topic:'5D-grammar', prompt:"___, social media also tells applicants about the company they're applying to.", answer:"Moreover"},
    {section:'5D', topic:'5D-grammar', prompt:"___, checks need to be made that employers' decisions are fair.", answer:"Furthermore"},
    {section:'5D', topic:'5D-grammar', prompt:"___ actively seeking negative posts, the system lets employers discriminate.", answer:"Besides"},
    {section:'5D', topic:'5D-vocab', prompt:"___ all, employers claim the process becomes more efficient.", answer:"Above"},
    {section:'5D', topic:'5D-vocab', prompt:"In ___, I understand applicants' concerns about 'trawling'.", answer:"Particular"},
    {section:'5D', topic:'5D-vocab', prompt:"___ researching applicants online, employers contact previous employers.", answer:"Beyond"},
    {section:'5D', topic:'5D-vocab', prompt:"The ___ outlines the topic and gets the reader interested.", answer:"Introduction"},
    {section:'5D', topic:'5D-vocab', prompt:"The ___ states your final, balanced opinion of both sides.", answer:"Conclusion"},
    {section:'5D', topic:'5D-vocab', prompt:"A good essay ending gives a ___ opinion rather than a one-sided one.", answer:"Balanced"},
    {section:'5D', topic:'5D-vocab', prompt:"Applicants object to employers ___ for negative information about them.", answer:"Trawling"},
    {section:'5D', topic:'5D-vocab', prompt:"Some fear that employers will ___ against them on the basis of age.", answer:"Discriminate"},
    {section:'5D', topic:'5D-vocab', prompt:"Job applicants have voiced ___ concerns about these checks.", answer:"Privacy"},
    {section:'5D', topic:'5D-vocab', prompt:"Companies examine profiles for information to use in the ___ process.", answer:"Selection"},
    {section:'5D', topic:'5D-vocab', prompt:"Employers' decisions need to be fair and ___.", answer:"Transparent"},
  ],

  /* ---- Millionaire ----------------------------------------------------------
     Four options, rising difficulty. `level` 1-8 maps to the rungs of the ladder;
     each section carries 12 so a single section fills a ladder and repeat plays
     still differ (§3.4).
     Authoring note (§4.4): the distractors are the teaching. Each wrong option is
     a mistake this class would plausibly make — a real word with the wrong
     meaning, a wrong collocation, or a form error — never obvious filler.
     Fields: section, level, prompt, answer, distractors[3]. */
  millionaireBank: [
    /* ---- typed forms: error correction, marked with *asterisks* ---- */
    {section:'5A', topic:'5A-vocab', type:'errorfix', level:3, prompt:"Correct the error: 'He was *accused for* the robbery.'",
      answer:"accused of", distractors:["accused with","accused by","accused on"]},
    {section:'5B', topic:'5B-grammar', type:'errorfix', level:4, prompt:"Correct the error: 'You *must to* wear protective clothing.'",
      answer:"must", distractors:["must to be","have must","must been"]},
    {section:'5C', topic:'5C-vocab', type:'errorfix', level:5, prompt:"Correct the error: 'I *reckon to be* she is right.'",
      answer:"reckon", distractors:["reckon to","reckoning","reckons to"]},
    /* ---- 5A: crime & justice, relative clauses ---- */
    {section:'5A', topic:'5A-vocab', level:1, prompt:"Someone who saw the crime happen is called a ___.",
      answer:"witness", distractors:["suspect","juror","victim"]},
    {section:'5A', topic:'5A-vocab', level:2, prompt:"The twelve ordinary citizens who decide guilt are the ___.",
      answer:"jury", distractors:["bench","panel","tribunal"]},
    {section:'5A', topic:'5A-vocab', level:2, prompt:"He was held in ___ for three months before the trial.",
      answer:"custody", distractors:["captivity","arrest","seizure"]},
    {section:'5A', topic:'5A-vocab', level:3, prompt:"Unpaid work given instead of prison: ___ service.",
      answer:"community", distractors:["public","social","civil"]},
    {section:'5A', topic:'5A-vocab', level:3, prompt:"The lawyers who try to prove the accused is guilty are the ___.",
      answer:"prosecution", distractors:["prosecutor","defence","plaintiff"]},
    {section:'5A', topic:'5A-vocab', level:4, prompt:"Which word means helping offenders return to normal life in society?",
      answer:"rehabilitation", distractors:["retribution","restitution","probation"]},
    {section:'5A', topic:'5A-vocab', level:4, prompt:"'Solitary ___' — kept apart from all other prisoners.",
      answer:"confinement", distractors:["isolation","detention","seclusion"]},
    {section:'5A', topic:'5A-vocab', level:5, prompt:"'She has a solid ___' — proof that she was somewhere else.",
      answer:"alibi", distractors:["testimony","defence","affidavit"]},
    {section:'5A', topic:'5A-vocab', level:5, prompt:"The court's final decision on guilt is the ___.",
      answer:"verdict", distractors:["sentence","penalty","appeal"]},
    {section:'5A', topic:'5A-grammar', level:6, prompt:"Complete formally: 'The prison, ___ are covered in murals, opened in 2010.'",
      answer:"the walls of which", distractors:["which walls","whose the walls","the walls which"]},
    {section:'5A', topic:'5A-grammar', level:7, prompt:"Complete formally: 'Some of the inmates, ___ have committed serious crimes, work in the kitchen.'",
      answer:"many of whom", distractors:["many of who","many of them","many whom"]},
    {section:'5A', topic:'5A-vocab', level:8, prompt:"Which term means hiding where illegally-earned money came from?",
      answer:"money laundering", distractors:["money washing","money cleaning","money bleaching"]},

    /* Relative clauses, Grammar Focus 5A (p146). This is the game the page suits
       best: exercise b is already written as a four-way choice, so the distractors
       are the book's own — 'to who' for 'to whom', 'few of who' for 'few of whom'.
       Every wrong option here is an error a C1 class actually makes, which is the
       authoring rule for this bank. */
    {section:'5A', topic:'5A-grammar', level:1, prompt:"'Florida is the only place ___ I want to live.'",
      answer:"that", distractors:["wherever","what","whom"]},
    {section:'5A', topic:'5A-grammar', level:2, prompt:"'Give me one good reason ___ I should believe you.'",
      answer:"why", distractors:["which","what","how"]},
    {section:'5A', topic:'5A-grammar', level:3, prompt:"'It's up to the person ___ job it is to sort out the transport.'",
      answer:"whose", distractors:["what","which","who's"]},
    {section:'5A', topic:'5A-grammar', level:4, prompt:"'The emergency number is 999, ___ is easy to remember.'",
      answer:"which", distractors:["that","what","whom"]},
    {section:'5A', topic:'5A-grammar', level:5, prompt:"'Mrs Jackson, ___ we are very grateful, has agreed to speak.'",
      answer:"to whom", distractors:["to who","whose","that"]},
    {section:'5A', topic:'5A-grammar', level:6, prompt:"'We recruited some younger staff, ___ had any experience.'",
      answer:"few of whom", distractors:["few of who","few of which","few of whose"]},
    {section:'5A', topic:'5A-grammar', level:7, prompt:"Which sentence is correct?",
      answer:"The victim, who we cannot name, is recovering.",
      distractors:["The victim, that we cannot name, is recovering.",
                   "The victim, we cannot name, is recovering.",
                   "The victim, what we cannot name, is recovering."]},
    {section:'5A', topic:'5A-grammar', level:8, prompt:"Which sentence is correct?",
      answer:"Stealing from the kitchen is something which we will not put up with.",
      distractors:["Stealing from the kitchen is something with which we will not put up.",
                   "Stealing from the kitchen is something up with which we will not put.",
                   "Stealing from the kitchen is something which we will not put up with it."]},

    /* ---- 5B: employment, pay & benefits, obligation ---- */
    {section:'5B', topic:'5B-vocab', level:1, prompt:"Flexible working hours are known as ___.",
      answer:"flexitime", distractors:["flexihours","freetime","flexiwork"]},
    {section:'5B', topic:'5B-vocab', level:2, prompt:"A long paid career break, often six months, is a ___.",
      answer:"sabbatical", distractors:["furlough","secondment","sabbath"]},
    {section:'5B', topic:'5B-vocab', level:2, prompt:"Leave for new fathers is ___ leave.",
      answer:"paternity", distractors:["maternity","parental","fraternity"]},
    {section:'5B', topic:'5B-vocab', level:3, prompt:"Job cuts that make workers lose their jobs are called ___.",
      answer:"redundancies", distractors:["dismissals","resignations","retirements"]},
    {section:'5B', topic:'5B-vocab', level:3, prompt:"Pay linked to how well you do your job is ___-related pay.",
      answer:"performance", distractors:["production","productive","performing"]},
    {section:'5B', topic:'5B-vocab', level:4, prompt:"'Safety training is ___' — you absolutely must do it.",
      answer:"mandatory", distractors:["mandated","obliged","compulsive"]},
    {section:'5B', topic:'5B-grammar', level:4, prompt:"'Under the contract we are ___ to start work at 8:00.'",
      answer:"obliged", distractors:["obligated","obliging","obligatory"]},
    {section:'5B', topic:'5B-vocab', level:5, prompt:"'You'll be ___ to hold a diving certificate for this job.'",
      answer:"required", distractors:["requested","requisite","demanded"]},
    {section:'5B', topic:'5B-vocab', level:5, prompt:"The training and certificates a job demands are your ___.",
      answer:"qualifications", distractors:["qualities","credentials","competences"]},
    {section:'5B', topic:'5B-grammar', level:6, prompt:"Complete formally: 'Visitors are not ___ to bring food into the building.'",
      answer:"permitted", distractors:["permissible","allowance","admitted"]},
    {section:'5B', topic:'5B-vocab', level:7, prompt:"'You ___ have to pay tax on it' — meaning it isn't necessary.",
      answer:"don't", distractors:["mustn't","can't","shouldn't"]},
    {section:'5B', topic:'5B-grammar', level:8, prompt:"'You ___ to get some experience first' — mild advice, not an obligation.",
      answer:"ought", distractors:["must","have","should"]},

    /* Obligation, necessity and permission — Grammar Focus 5B (p147). The choices
       come from the page's own practice exercises, so the wrong options are the
       ones the book deliberately contrasts: needn't vs mustn't, should vs ought
       (which needs 'to'), was supposed to vs had to. */
    {section:'5B', topic:'5B-grammar', level:1, prompt:"'Maria ___ keep her promotion a secret until it's officially announced.'",
      answer:"must", distractors:["will","would","may"]},
    {section:'5B', topic:'5B-grammar', level:2, prompt:"'You ___ bring a towel for the pool — they provide them free of charge.'",
      answer:"needn't", distractors:["mustn't","can't","shouldn't"]},
    {section:'5B', topic:'5B-vocab', level:3, prompt:"'Pilots are ___ to get a medical exam every six months.'",
      answer:"required", distractors:["essential","obligatory","necessary"]},
    {section:'5B', topic:'5B-grammar', level:4, prompt:"'When we lived in the village, we ___ drive for miles to reach a supermarket.'",
      answer:"had to", distractors:["must","were allowed to","ought to"]},
    {section:'5B', topic:'5B-grammar', level:5, prompt:"'Tony ___ be taking care of that, but he's so lazy.'",
      answer:"should", distractors:["ought","had better","must"]},
    {section:'5B', topic:'5B-vocab', level:6, prompt:"'The match ___ begin at 7:00, but heavy rain delayed the start.'",
      answer:"was supposed to", distractors:["had to","was required to","must have"]},
    {section:'5B', topic:'5B-vocab', level:7, prompt:"Which is the most formal way of stating the rule?",
      answer:"Visitors are forbidden to bring food into the building.",
      distractors:["Visitors mustn't bring food into the building.",
                   "Visitors can't bring food into the building.",
                   "Visitors shouldn't bring food into the building."]},
    {section:'5B', topic:'5B-vocab', level:8, prompt:"Rewrite with 'choice': 'The only option I have is to cancel the trip.'",
      answer:"I have no choice but to cancel the trip.",
      distractors:["I have no choice to cancel the trip.",
                   "I have no choice but cancelling the trip.",
                   "I haven't any choice but cancel the trip."]},

    /* ---- 5C: recalling & speculating ---- */
    {section:'5C', topic:'5C-vocab', level:1, prompt:"'It's ___ my mind' — I've forgotten it.",
      answer:"slipped", distractors:["slid","escaped","dropped"]},
    {section:'5C', topic:'5C-vocab', level:2, prompt:"Which phrase means the same as 'if I remember rightly'?",
      answer:"if my memory serves me correctly", distractors:["if my memory stands me correctly","if my memory holds me right","if my memory works correctly"]},
    {section:'5C', topic:'5C-vocab', level:2, prompt:"'I'd ___ a guess that it cost about two thousand euros.'",
      answer:"hazard", distractors:["risk","chance","hazardous"]},
    {section:'5C', topic:'5C-vocab', level:3, prompt:"'That evening ___ out in my mind more than any other.'",
      answer:"stands", distractors:["sticks","holds","comes"]},
    {section:'5C', topic:'5C-vocab', level:3, prompt:"'I was under the ___ that the meeting had been cancelled.'",
      answer:"impression", distractors:["assumption","expression","impact"]},
    {section:'5C', topic:'5C-vocab', level:4, prompt:"Which phrase introduces something you assume the listener already knows?",
      answer:"no doubt", distractors:["no wonder","no question","without fail"]},
    {section:'5C', topic:'5C-vocab', level:4, prompt:"Which expression introduces something you are recalling, with slight uncertainty?",
      answer:"If my memory serves me correctly", distractors:["I'd hazard a guess","No doubt you heard","Presuming you're right"]},
    {section:'5C', topic:'5C-vocab', level:5, prompt:"'___ a guess, I'd say she's about forty.'",
      answer:"Hazarding", distractors:["Hazard","Hazarded","Hazardly"]},
    {section:'5C', topic:'5C-vocab', level:5, prompt:"Which phrase signals a guess rather than a memory?",
      answer:"I'd hazard a guess that…", distractors:["If my memory serves me correctly…","What stands out in my mind is…","I distinctly remember…"]},
    {section:'5C', topic:'5C-vocab', level:6, prompt:"'There's no point ___ about what might have happened.'",
      answer:"speculating", distractors:["speculate","to speculate","speculation"]},
    {section:'5C', topic:'5C-vocab', level:7, prompt:"Which of these is NOT used for recalling?",
      answer:"I'd hazard a guess", distractors:["If my memory serves me","What stands out in my mind","I think I remember"]},
    {section:'5C', topic:'5C-vocab', level:8, prompt:"'I was under the impression that…' suggests the speaker…",
      answer:"believed something that may not be true", distractors:["is certain of a fact","is recalling it exactly","is asking a question"]},
    /* ---- added later: transformation, error correction, collocation, register and
           stress, so the ladder isn't only gapped sentences ---- */
    {section:'5A', topic:'5A-vocab', level:2, prompt:"Which word means a court's formal finding that someone is guilty?",
      answer:"conviction", distractors:["indictment","acquittal","testimony"]},
    {section:'5A', topic:'5A-vocab', level:3, prompt:"Which sentence is correct?",
      answer:"He was accused of fraud.", distractors:["He was accused for fraud.","He was accused with fraud.","He was accused on fraud."]},
    {section:'5A', topic:'5A-vocab', level:4, prompt:"Which word does NOT belong with the others?",
      answer:"sabbatical", distractors:["verdict","jury","testimony"]},
    {section:'5A', topic:'5A-vocab', level:5, prompt:"Which verb goes with 'a sentence', meaning to undergo the punishment?",
      answer:"serve", distractors:["make","do","take"]},
    {section:'5A', topic:'5A-grammar', level:6, prompt:"Which is the correct formal version?",
      answer:"the prisoners, many of whom reoffend", distractors:["the prisoners, many of who reoffend","the prisoners that many reoffend","the prisoners which many of them reoffend"]},
    {section:'5B', topic:'5B-vocab', level:2, prompt:"'We are under no ___ to accept their offer.'",
      answer:"obligation", distractors:["obliged","obligatory","obliging"]},
    {section:'5B', topic:'5B-vocab', level:3, prompt:"Which sentence is correct?",
      answer:"You must wear a helmet.", distractors:["You must to wear a helmet.","You must wearing a helmet.","You must worn a helmet."]},
    {section:'5B', topic:'5B-vocab', level:4, prompt:"'She received a generous ___ payment when her job was cut.'",
      answer:"redundancy", distractors:["severance","redundant","redundancies"]},
    {section:'5B', topic:'5B-vocab', level:5, prompt:"Which sentence is correct?",
      answer:"He was made redundant.", distractors:["He was made redundancy.","He was made a redundant.","He was done redundant."]},
    {section:'5B', topic:'5B-grammar', level:6, prompt:"Which is the most formal way of refusing permission?",
      answer:"Visitors are not permitted to bring food.", distractors:["Visitors can't bring food.","Visitors mustn't bring food.","Visitors aren't allowed food."]},
    {section:'5C', topic:'5C-vocab', level:2, prompt:"'The article was dismissed as idle ___.'",
      answer:"speculation", distractors:["speculating","speculative","speculator"]},
    {section:'5C', topic:'5C-vocab', level:3, prompt:"Which one does NOT show uncertainty?",
      answer:"No doubt", distractors:["I'd hazard a guess","I'm not entirely sure","Presumably"]},
    {section:'5C', topic:'5C-vocab', level:4, prompt:"Which adjective does NOT go with 'memory'?",
      answer:"heavy", distractors:["vague","painful","lasting"]},
    {section:'5C', topic:'5C-vocab', level:5, prompt:"'You're making a lot of ___ there.'",
      answer:"assumptions", distractors:["assumes","assuming","presumptions"]},
    {section:'5C', topic:'5C-vocab', level:6, prompt:"Which sentence is correct?",
      answer:"If my memory serves me correctly…", distractors:["If my memory serves me correct…","If my memory serves to me correctly…","If my memory is serving me correct…"]},
    {section:'5C', topic:'5C-vocab', level:7, prompt:"Which syllable carries the main stress in 're-ha-bi-li-ta-tion'?",
      answer:"the 5th — TA", distractors:["the 1st — re","the 3rd — bi","the 6th — tion"]},

    /* ---- 5D: opinion essays & linking ----
       Four options suit this section particularly well: the linkers differ by
       *where they can sit in a sentence*, not by meaning, so the wrong options are
       real errors rather than different words. */
    {section:'5D', topic:'5D-grammar', level:1, prompt:"Which linker adds an idea in a NEW sentence?",
      answer:"In addition,", distractors:["as well as","in addition to","beyond"]},
    {section:'5D', topic:'5D-grammar', level:2, prompt:"'___, time saved is money saved.'",
      answer:"Besides", distractors:["Beyond","As well as","In addition to"]},
    {section:'5D', topic:'5D-vocab', level:3, prompt:"Which phrase marks your single most important argument?",
      answer:"Above all", distractors:["In particular","What's more","In addition"]},
    {section:'5D', topic:'5D-vocab', level:4, prompt:"What is the job of an opinion essay's introduction?",
      answer:"To outline the topic and interest the reader",
      distractors:["To state your final opinion","To present one side of the argument",
                   "To summarise the key points"]},
    {section:'5D', topic:'5D-vocab', level:5, prompt:"Which must NOT appear in a conclusion?",
      answer:"Interesting new information",
      distractors:["A balanced opinion of both sides","A brief summary of key points",
                   "A possible course of action"]},
    {section:'5D', topic:'5D-vocab', level:6, prompt:"'___ researching the applicant online, employers contact previous employers.'",
      answer:"Beyond", distractors:["Besides that","Moreover","Furthermore"]},
    {section:'5D', topic:'5D-grammar', level:7, prompt:"Which sentence uses the linker correctly?",
      answer:"As well as being a valuable tool for employers, social media informs applicants.",
      distractors:["As well as it is a valuable tool, social media informs applicants.",
                   "In addition being a valuable tool, social media informs applicants.",
                   "Moreover being a valuable tool, social media informs applicants."]},
    {section:'5D', topic:'5D-vocab', level:8, prompt:"'It is standard to search criminal records ___ the methods mentioned above.'",
      answer:"in addition to", distractors:["in addition of","in addition with","in addition than"]},

    /* A second question at every 5D rung, and the two 5C rungs that had only one.
       The ladder is per team, so with one question per rung both teams meet the
       identical question on the way up. */
    {section:'5D', topic:'5D-grammar', level:1, prompt:"Which one-word linker starts a new sentence and means 'what is more'?",
      answer:"Furthermore", distractors:["As well as","Beyond","In addition to"]},
    {section:'5D', topic:'5D-grammar', level:2, prompt:"'___, as well as being useful to employers, social media informs applicants.'",
      answer:"Moreover", distractors:["Whereas","However","Nevertheless"]},
    {section:'5D', topic:'5D-grammar', level:3, prompt:"Which linker narrows from a general point to one specific case?",
      answer:"In particular", distractors:["In general","In addition","In short"]},
    {section:'5D', topic:'5D-vocab', level:4, prompt:"Which is NOT a good way to open an essay introduction?",
      answer:"Stating your own final opinion",
      distractors:["Referring to facts and figures","Making a surprising statement",
                   "Clearly outlining the issue"]},
    {section:'5D', topic:'5D-vocab', level:5, prompt:"How many paragraphs does the model opinion essay use?",
      answer:"four — intro, one side, the other side, conclusion",
      distractors:["three — intro, argument, conclusion","two — for and against",
                   "five — intro, three arguments, conclusion"]},
    {section:'5D', topic:'5D-grammar', level:6, prompt:"Which spelling is correct in 'Besides / Beside actively seeking posts…'?",
      answer:"Besides", distractors:["Beside","Besides of","Beside from"]},
    {section:'5D', topic:'5D-vocab', level:7, prompt:"Which word means employers actively hunting for bad information?",
      answer:"trawling", distractors:["trailing","tracking","trialling"]},
    {section:'5D', topic:'5D-vocab', level:8, prompt:"Which sentence is correctly punctuated?",
      answer:"Moreover, employers claim the process is more efficient.",
      distractors:["Moreover employers claim the process is more efficient.",
                   "Moreover; employers claim the process is more efficient.",
                   "Moreover: employers claim the process is more efficient."]},

    {section:'5C', topic:'5C-vocab', level:1, prompt:"Which phrase introduces something you are remembering?",
      answer:"What stands out in my mind…",
      distractors:["I'd hazard a guess…","I'm presuming…","No doubt…"]},
    {section:'5C', topic:'5C-vocab', level:8, prompt:"Which is the most tentative way of putting it?",
      answer:"I'd hazard a guess that it was around 2015.",
      distractors:["It was around 2015.","I'm certain it was 2015.",
                   "It was definitely about 2015."]},
  ],

  millionaireSectionNames: {
    '5A':'5A · Crime, justice & relative clauses (26 questions)',
    '5B':'5B · Employment & obligation (26 questions)',
    '5C':'5C · Recalling & speculating (21 questions)',
    '5D':'5D · Opinion essays & linking (16 questions)',
  },

  raceSectionNames: {
    '5A':'5A · Crime, justice & relative clauses (25 words)',
    '5B':'5B · Employment & obligation (25 words)',
    '5C':'5C · Recalling & speculating (16 words)',
    '5D':'5D · Opinion essays & linking (14 words)',
  },
});
