/* ================= Content bank — Empower C1 Unit 5: Fairness =================
   Data only. Consumed by game-hub/hub-engine.js via window.UNIT.
   Authored from material/empower-c1-unit-5/ (pp.55-66 + Grammar/Vocab Focus). */
(window.UNITS = window.UNITS || []).push({
  id: "unit-5",
  label: "Cambridge Empower C1 · Unit 5 · Fairness",
  card: { num: "Unit 5", title: "Fairness", blurb: "Crime & justice, relative clauses, employment, obligation, recalling & speculating (5A–5C).", sections: "5A–5C" },
  intro: "Choose a template. You'll pick the content next — mix and match any of 5A–5C.",

  jeopardySectionLabels: {
    '5A': "5A · A place where you have to look over your shoulder",
    '5B': "5B · It's essential to have the right qualifications",
    '5C': "5C · I'd hazard a guess",
  },

  jeopardyCategories: [
    { id:'crime-justice', section:'5A', name:'Crime & Justice', clues:[
      {v:100, q:"Being kept in prison while awaiting trial: being 'held in ___'.", a:"custody"},
      {v:200, q:"'They made an ___ of fraud against him' — a formal accusation.", a:"an allegation"},
      {v:300, q:"Found by a court to have committed a crime: 'he's been ___ of murder'.", a:"convicted"},
      {v:400, q:"The formal evidence a witness gives in court.", a:"testimony"},
      {v:500, q:"'He ___ guilty to the crime' — he admitted it in court.", a:"pleaded"},
    ]},
    { id:'punishment', section:'5A', name:'Punishment & Rehab', clues:[
      {v:100, q:"Unpaid work done as a punishment: 'do ___ service'.", a:"community"},
      {v:200, q:"The most severe sentence: 'sentenced to life ___'.", a:"imprisonment"},
      {v:300, q:"Isolating a prisoner from all others: 'solitary ___'.", a:"confinement"},
      {v:400, q:"One-to-one or group sessions that support prisoners.", a:"counselling"},
      {v:500, q:"'Served a reduced sentence for good ___' — released early.", a:"behaviour"},
    ]},
    { id:'relative-clauses', section:'5A', name:'Relative Clauses', clues:[
      {v:100, q:"Relative pronoun for people: 'the officer ___ arrested him'.", a:"who"},
      {v:200, q:"Relative pronoun for a place: 'the prison ___ he was held'.", a:"where"},
      {v:300, q:"Defining or non-defining? 'Halden, which opened in 2010, is humane.'", a:"non-defining (extra info, uses commas)"},
      {v:400, q:"Complete (formal): 'the prison, the walls ___ which are covered in art'.", a:"of"},
      {v:500, q:"Make it formal: 'some of the prisoners, who have committed serious crimes' → 'some ___ ___ …'.", a:"of whom"},
    ]},
    { id:'change-the-word', section:'5A', name:'Change the Word', clues:[
      {v:100, q:"Change the verb 'to convict' into the noun for the court's decision.", a:"conviction"},
      {v:200, q:"Change 'crime' into the word for the person who commits one.", a:"criminal"},
      {v:300, q:"Change 'guilt' into the adjective a court uses in its verdict.", a:"guilty"},
      {v:400, q:"Change the verb 'to prosecute' into the noun for the lawyers doing it.", a:"the prosecution"},
      {v:500, q:"Change 'rehabilitate' into the noun for the whole process.", a:"rehabilitation"},
    ]},
    { id:'employment', section:'5B', name:'Employment & Sectors', clues:[
      {v:100, q:"A distinct area of the economy, such as retail or transport: a ___.", a:"sector"},
      {v:200, q:"Banking and investment belong to the ___ sector.", a:"financial"},
      {v:300, q:"When jobs are cut and workers lose them: ___.", a:"redundancies"},
      {v:400, q:"Farming belongs to the ___ sector.", a:"agricultural"},
      {v:500, q:"Building houses and roads: the ___ sector.", a:"construction"},
    ]},
    { id:'pay-benefits', section:'5B', name:'Pay & Benefits', clues:[
      {v:100, q:"Flexible working hours are called ___.", a:"flexitime"},
      {v:200, q:"A long paid career break, often six months: a ___.", a:"sabbatical"},
      {v:300, q:"Pay linked to how well you do your job: ___-related pay.", a:"performance"},
      {v:400, q:"Leave for new fathers: ___ leave.", a:"paternity"},
      {v:500, q:"'Four ___ days' — days off a year with no reason needed.", a:"personal"},
    ]},
    { id:'obligation', section:'5B', name:'Obligation & Permission', clues:[
      {v:100, q:"Strong obligation from a rule (modal verb): 'you ___ wear a helmet'.", a:"must"},
      {v:200, q:"Formal necessity: 'you'll be ___ to have a diving qualification'.", a:"required"},
      {v:300, q:"Not allowed (formal): 'visitors are ___ to bring food into the building'.", a:"forbidden / not permitted"},
      {v:400, q:"Lack of obligation: 'you ___ have to pay tax on it' (it isn't necessary).", a:"don't"},
      {v:500, q:"Mild advice, not 'must': 'you ___ to get some experience first'.", a:"ought / should"},
    ]},
    { id:'spot-the-error', section:'5B', name:'Spot the Error', clues:[
      {v:100, q:"Correct it: 'You must to wear a helmet on site.'", a:"you must wear (no 'to' after a modal)"},
      {v:200, q:"Correct it: 'She is obliged for provide safety gear.'", a:"obliged TO provide"},
      {v:300, q:"Correct it: 'It isn't permitted bringing food into the lab.'", a:"permitted TO BRING"},
      {v:400, q:"Correct it: 'You haven't to pay tax on that.'", a:"you don't have to pay"},
      {v:500, q:"Correct it: 'He was made redundancy last year.'", a:"he was made REDUNDANT (adjective)"},
    ]},
    { id:'recall-speculate', section:'5C', name:'Recall or Speculate?', clues:[
      {v:100, q:"Recalling or speculating? 'If my memory serves me correctly…'", a:"recalling"},
      {v:200, q:"Recalling or speculating? 'I'd hazard a guess that…'", a:"speculating"},
      {v:300, q:"Recalling or speculating? 'What stands out in my mind is…'", a:"recalling"},
      {v:400, q:"Recalling or speculating? 'I was under the impression that…'", a:"speculating"},
      {v:500, q:"Recalling or speculating? 'I think I remember her saying…'", a:"recalling"},
    ]},
    { id:'complete-expression', section:'5C', name:'Complete the Expression', clues:[
      {v:100, q:"'If my memory ___ me correctly…'", a:"serves"},
      {v:200, q:"'I'd ___ a guess that…'", a:"hazard"},
      {v:300, q:"'What ___ out in my mind is…'", a:"stands"},
      {v:400, q:"'I was under the ___ that you were writing another book.'", a:"impression"},
      {v:500, q:"'___ you're a technician, right?' — making an assumption.", a:"Presuming"},
    ]},
    { id:'meaning-match', section:'5C', name:'What Does It Mean?', clues:[
      {v:100, q:"'It's slipped my mind' means…", a:"I've forgotten it"},
      {v:200, q:"'I'd hazard a guess' means…", a:"I'll make a rough guess / estimate"},
      {v:300, q:"'No doubt you heard that from…' expresses…", a:"a confident assumption"},
      {v:400, q:"'If my memory serves me correctly' is used to…", a:"introduce something you're recalling (with slight uncertainty)"},
      {v:500, q:"'What stands out in my mind' refers to…", a:"the thing you remember most clearly"},
    ]},
    { id:'odd-one-out', section:'5C', name:'Odd One Out', clues:[
      {v:100, q:"Which is NOT about remembering? recall / remember / hazard / memory", a:"hazard (it's for guessing)"},
      {v:200, q:"Which shows you are SURE? I'd hazard a guess / I'd say roughly / no doubt / I'm not certain", a:"no doubt"},
      {v:300, q:"Which is NOT a real expression? it slipped my mind / it crossed my mind / it fell out of my mind", a:"it fell out of my mind"},
      {v:400, q:"Which adjective does NOT go with 'memory'? vague / painful / lasting / heavy", a:"heavy"},
      {v:500, q:"Which does NOT introduce something you recall? if my memory serves / what stands out in my mind / I'd hazard a guess", a:"I'd hazard a guess (that's speculating)"},
    ]},
  ],

  blockbustersBank: [
    /* ---- 5A: crime & justice (single-word answers) ---- */
    {section:'5A', letter:'F', clue:"A financial crime of deception for personal gain.", answer:"Fraud"},
    {section:'5A', letter:'M', clue:"The most serious crime — unlawful killing.", answer:"Murder"},
    {section:'5A', letter:'C', clue:"Held before trial: held in ___.", answer:"Custody"},
    {section:'5A', letter:'T', clue:"The formal evidence a witness gives in court.", answer:"Testimony"},
    {section:'5A', letter:'A', clue:"A claim that you were elsewhere when the crime happened.", answer:"Alibi"},
    {section:'5A', letter:'V', clue:"The court's decision: guilty or not guilty.", answer:"Verdict"},
    {section:'5A', letter:'J', clue:"The group of ordinary citizens who decide guilt.", answer:"Jury"},
    {section:'5A', letter:'W', clue:"Someone who saw the crime happen.", answer:"Witness"},
    {section:'5A', letter:'P', clue:"The lawyers trying to prove the accused is guilty.", answer:"Prosecution"},
    {section:'5A', letter:'S', clue:"The punishment a judge hands down.", answer:"Sentence"},
    {section:'5A', letter:'I', clue:"'Life ___' — being locked up for the rest of your life.", answer:"Imprisonment"},
    {section:'5A', letter:'R', clue:"Helping offenders return to normal life in society.", answer:"Rehabilitation"},
    {section:'5A', letter:'B', clue:"'___ from driving' — stopped from driving as a punishment.", answer:"Banned"},
    {section:'5A', letter:'L', clue:"Money ___ — hiding where illegally-earned cash came from.", answer:"Laundering"},
    {section:'5A', letter:'G', clue:"'Found ___ of the crime' — the opposite of innocent.", answer:"Guilty"},
    {section:'5A', letter:'D', clue:"The ___ lawyer argues on behalf of the accused.", answer:"Defence"},
    {section:'5A', letter:'O', clue:"The formal word for a crime or illegal act.", answer:"Offence"},
    {section:'5A', letter:'S', clue:"Kept apart from all other prisoners: '___ confinement'.", answer:"Solitary"},

    /* ---- 5B: employment & obligation (single-word answers) ---- */
    {section:'5B', letter:'F', clue:"Banking and investment belong to this sector.", answer:"Financial"},
    {section:'5B', letter:'A', clue:"Farming belongs to this sector.", answer:"Agricultural"},
    {section:'5B', letter:'C', clue:"Building houses and roads: this sector.", answer:"Construction"},
    {section:'5B', letter:'R', clue:"Shops and selling to customers: this sector.", answer:"Retail"},
    {section:'5B', letter:'M', clue:"Making goods in factories: this sector.", answer:"Manufacturing"},
    {section:'5B', letter:'T', clue:"Moving goods and people around: this sector.", answer:"Transport"},
    {section:'5B', letter:'E', clue:"Oil, gas and electricity: this sector.", answer:"Energy"},
    {section:'5B', letter:'P', clue:"Government-run services: the ___ sector.", answer:"Public"},
    {section:'5B', letter:'S', clue:"A distinct area of the economy.", answer:"Sector"},
    {section:'5B', letter:'R', clue:"Job cuts that make workers lose their jobs.", answer:"Redundancies"},
    {section:'5B', letter:'F', clue:"A benefit that lets you choose your own working hours.", answer:"Flexitime"},
    {section:'5B', letter:'S', clue:"A long paid career break, often six months.", answer:"Sabbatical"},
    {section:'5B', letter:'P', clue:"Leave for new fathers: ___ leave.", answer:"Paternity"},
    {section:'5B', letter:'M', clue:"A ___ requirement is one you absolutely MUST meet.", answer:"Mandatory"},
    {section:'5B', letter:'O', clue:"'You are ___ to wear protective clothing' — formal strong obligation (be ___).", answer:"Obliged"},
    {section:'5B', letter:'Q', clue:"The training and certificates a job requires.", answer:"Qualifications"},

    /* ---- 5C: recalling & speculating (single-word answers) ---- */
    {section:'5C', letter:'M', clue:"'If my ___ serves me correctly…'", answer:"Memory"},
    {section:'5C', letter:'I', clue:"'I was under the ___ that you were writing another book.'", answer:"Impression"},
    {section:'5C', letter:'H', clue:"'I'd ___ a guess that…' — make a rough estimate.", answer:"Hazard"},
    {section:'5C', letter:'G', clue:"'I'd hazard a ___ that…'", answer:"Guess"},
    {section:'5C', letter:'S', clue:"'What ___ out in my mind is…'", answer:"Stands"},
    {section:'5C', letter:'P', clue:"'___ you're a technician, right?' — making an assumption.", answer:"Presuming"},
    {section:'5C', letter:'D', clue:"'No ___ you heard that from…' — a confident assumption.", answer:"Doubt"},
    {section:'5C', letter:'R', clue:"To ___ something is to bring a past event back to mind.", answer:"Recall"},
    {section:'5C', letter:'S', clue:"To ___ is to guess about something you're not sure of.", answer:"Speculate"},
    {section:'5C', letter:'M', clue:"'It's slipped my ___' — I've forgotten it.", answer:"Mind"},

    /* ---- added later: transformations and opposites, to vary the clue types ---- */
    {section:'5A', letter:'C', clue:"Change the verb 'to convict' into the noun for the court's decision.", answer:"Conviction"},
    {section:'5A', letter:'C', clue:"Change 'crime' into the word for the person who commits one.", answer:"Criminal"},
    {section:'5A', letter:'I', clue:"The opposite of a guilty verdict.", answer:"Innocent"},
    {section:'5A', letter:'A', clue:"Change the noun 'accusation' into the past participle: 'he was ___ of fraud'.", answer:"Accused"},
    {section:'5B', letter:'R', clue:"Change the adjective 'redundant' into the noun for the job cuts.", answer:"Redundancy"},
    {section:'5B', letter:'O', clue:"Change the verb 'oblige' into the noun for a duty you must fulfil.", answer:"Obligation"},
    {section:'5B', letter:'P', clue:"Change the verb 'permit' into the noun for official approval.", answer:"Permission"},
    {section:'5B', letter:'M', clue:"Give another word for 'compulsory' — something you absolutely must do.", answer:"Mandatory"},
    {section:'5C', letter:'S', clue:"Change the verb 'to speculate' into the noun.", answer:"Speculation"},
    {section:'5C', letter:'A', clue:"Change the verb 'assume' into the noun for something taken for granted.", answer:"Assumption"},
    {section:'5C', letter:'I', clue:"Change the verb 'impress' into the noun used in 'I was under the ___'.", answer:"Impression"},
    {section:'5C', letter:'V', clue:"Which adjective describes a memory that is unclear or hazy?", answer:"Vague"},
  ],

  blockbustersSectionNames: {
    '5A':'5A · Crime & justice (22 clues)',
    '5B':'5B · Employment & obligation (20 clues)',
    '5C':'5C · Recalling & speculating (14 clues)',
  },

  /* ---- Race to the Board ----------------------------------------------------
     Gapped sentences, not definitions. The words themselves are on screen, so
     the prompt tests collocation and word form in context — a different angle on
     the same target language from Jeopardy's Q&A and Blockbusters' definitions.
     Distractors are not authored: every other word on the board is a real target
     word from the selected sections, so wrong taps are still teachable.
     Fields: section, prompt (use ___ for the gap), answer (one word). */
  raceBank: [
    /* ---- 5A: crime & justice ---- */
    {section:'5A', prompt:"The jury returned a ___ of not guilty after six hours.", answer:"Verdict"},
    {section:'5A', prompt:"He was held in ___ for three months before the trial began.", answer:"Custody"},
    {section:'5A', prompt:"She has a solid ___ — she was at work when the robbery happened.", answer:"Alibi"},
    {section:'5A', prompt:"The ___ lawyer argued there was no evidence against her client.", answer:"Defence"},
    {section:'5A', prompt:"He was ___ of fraud and sentenced to two years.", answer:"Convicted"},
    {section:'5A', prompt:"The judge handed down a five-year ___.", answer:"Sentence"},
    {section:'5A', prompt:"The ___ called three witnesses to prove the case.", answer:"Prosecution"},
    {section:'5A', prompt:"Instead of prison, he was ordered to do 200 hours of ___ service.", answer:"Community"},
    {section:'5A', prompt:"The prison in Norway focuses on ___ rather than punishment.", answer:"Rehabilitation"},
    {section:'5A', prompt:"Her ___ in court contradicted what she had told the police.", answer:"Testimony"},
    {section:'5A', prompt:"He was ___ from driving for eighteen months.", answer:"Banned"},
    {section:'5A', prompt:"Prisoners who attack staff can be put in ___ confinement.", answer:"Solitary"},

    /* ---- 5B: employment, pay & obligation ---- */
    {section:'5B', prompt:"After twelve years at the firm she took a six-month ___ to travel.", answer:"Sabbatical"},
    {section:'5B', prompt:"___ means staff can choose when they start and finish work.", answer:"Flexitime"},
    {section:'5B', prompt:"The company announced 200 ___ after a sharp fall in sales.", answer:"Redundancies"},
    {section:'5B', prompt:"New fathers are entitled to two weeks' ___ leave.", answer:"Paternity"},
    {section:'5B', prompt:"Safety training is ___ — every employee has to complete it.", answer:"Mandatory"},
    {section:'5B', prompt:"You'll be ___ to hold a diving certificate for this role.", answer:"Required"},
    {section:'5B', prompt:"Employers are legally ___ to provide protective clothing.", answer:"Obliged"},
    {section:'5B', prompt:"Most of the jobs lost were in the ___ sector — factories and plants.", answer:"Manufacturing"},
    {section:'5B', prompt:"Banking, insurance and investment make up the ___ sector.", answer:"Financial"},
    {section:'5B', prompt:"She didn't have the right ___, so her application was rejected.", answer:"Qualifications"},
    {section:'5B', prompt:"Bonuses here are ___-related — the better you do, the more you earn.", answer:"Performance"},
    {section:'5B', prompt:"Schools and hospitals belong to the ___ sector.", answer:"Public"},

    /* ---- 5C: recalling & speculating ---- */
    {section:'5C', prompt:"If my ___ serves me correctly, we met at a conference in Berlin.", answer:"Memory"},
    {section:'5C', prompt:"If my memory ___ me correctly, it was a Tuesday in October.", answer:"Serves"},
    {section:'5C', prompt:"I'd ___ a guess that she's about forty.", answer:"Hazard"},
    {section:'5C', prompt:"I'd hazard a ___ that it cost around two thousand euros.", answer:"Guess"},
    {section:'5C', prompt:"What ___ out in my mind is how quiet the room went.", answer:"Stands"},
    {section:'5C', prompt:"I was under the ___ that you'd already left the company.", answer:"Impression"},
    {section:'5C', prompt:"No ___ you've heard the news already.", answer:"Doubt"},
    {section:'5C', prompt:"___ you're the technician, right? The server's through there.", answer:"Presuming"},
    {section:'5C', prompt:"Sorry, his name has completely ___ my mind.", answer:"Slipped"},
    {section:'5C', prompt:"I can't ___ exactly what she said, but it was something like that.", answer:"Recall"},
    {section:'5C', prompt:"It's pointless to ___ about what might have happened.", answer:"Speculate"},
    {section:'5C', prompt:"I think I ___ her saying she'd be late.", answer:"Remember"},
    /* ---- added later: transformations, opposites and collocation, so the board
           isn't only gapped sentences. Answers are deliberately new words — two
           identical tiles on one board would be unplayable. ---- */
    {section:'5A', prompt:"Change the verb 'to convict' into the noun for the court's decision.", answer:"Conviction"},
    {section:'5A', prompt:"What is the opposite of a guilty verdict?", answer:"Innocent"},
    {section:'5A', prompt:"Change 'crime' into the word for the person who commits one.", answer:"Criminal"},
    {section:'5A', prompt:"Give the formal word for a crime or illegal act.", answer:"Offence"},
    {section:'5B', prompt:"Change the verb 'oblige' into the noun for a duty you must fulfil.", answer:"Obligation"},
    {section:'5B', prompt:"Change the verb 'permit' into the noun for official approval.", answer:"Permission"},
    {section:'5B', prompt:"Correct the error: 'He was made redundancy last year.'", answer:"Redundant"},
    {section:'5B', prompt:"Retail, transport and energy are each one of these parts of the economy.", answer:"Sector"},
    {section:'5C', prompt:"Change the verb 'to speculate' into the noun.", answer:"Speculation"},
    {section:'5C', prompt:"Change the verb 'assume' into the noun for something taken for granted.", answer:"Assumption"},
    {section:'5C', prompt:"Which adjective describes a memory that is unclear or hazy?", answer:"Vague"},
    {section:'5C', prompt:"Which noun completes both 'it slipped my ___' and 'it crossed my ___'?", answer:"Mind"},
  ],

  /* ---- Millionaire ----------------------------------------------------------
     Four options, rising difficulty. `level` 1-8 maps to the rungs of the ladder;
     each section carries 12 so a single section fills a ladder and repeat plays
     still differ (§3.4).
     Authoring note (§4.4): the distractors are the teaching. Each wrong option is
     a mistake this class would plausibly make — a real word with the wrong
     meaning, a wrong collocation, or a form error — never obvious filler.
     Fields: section, level, prompt, answer, distractors[3]. */
  millionaireBank: [
    /* ---- 5A: crime & justice, relative clauses ---- */
    {section:'5A', level:1, prompt:"Someone who saw the crime happen is called a ___.",
      answer:"witness", distractors:["suspect","juror","victim"]},
    {section:'5A', level:2, prompt:"The twelve ordinary citizens who decide guilt are the ___.",
      answer:"jury", distractors:["bench","panel","tribunal"]},
    {section:'5A', level:2, prompt:"He was held in ___ for three months before the trial.",
      answer:"custody", distractors:["captivity","arrest","seizure"]},
    {section:'5A', level:3, prompt:"Unpaid work given instead of prison: ___ service.",
      answer:"community", distractors:["public","social","civil"]},
    {section:'5A', level:3, prompt:"The lawyers who try to prove the accused is guilty are the ___.",
      answer:"prosecution", distractors:["prosecutor","defence","plaintiff"]},
    {section:'5A', level:4, prompt:"Which word means helping offenders return to normal life in society?",
      answer:"rehabilitation", distractors:["retribution","restitution","probation"]},
    {section:'5A', level:4, prompt:"'Solitary ___' — kept apart from all other prisoners.",
      answer:"confinement", distractors:["isolation","detention","seclusion"]},
    {section:'5A', level:5, prompt:"'She has a solid ___' — proof that she was somewhere else.",
      answer:"alibi", distractors:["testimony","defence","affidavit"]},
    {section:'5A', level:5, prompt:"The court's final decision on guilt is the ___.",
      answer:"verdict", distractors:["sentence","penalty","appeal"]},
    {section:'5A', level:6, prompt:"Complete formally: 'The prison, ___ are covered in murals, opened in 2010.'",
      answer:"the walls of which", distractors:["which walls","whose the walls","the walls which"]},
    {section:'5A', level:7, prompt:"Complete formally: 'Some of the inmates, ___ have committed serious crimes, work in the kitchen.'",
      answer:"many of whom", distractors:["many of who","many of them","many whom"]},
    {section:'5A', level:8, prompt:"Which term means hiding where illegally-earned money came from?",
      answer:"money laundering", distractors:["money washing","money cleaning","money bleaching"]},

    /* ---- 5B: employment, pay & benefits, obligation ---- */
    {section:'5B', level:1, prompt:"Flexible working hours are known as ___.",
      answer:"flexitime", distractors:["flexihours","freetime","flexiwork"]},
    {section:'5B', level:2, prompt:"A long paid career break, often six months, is a ___.",
      answer:"sabbatical", distractors:["furlough","secondment","sabbath"]},
    {section:'5B', level:2, prompt:"Leave for new fathers is ___ leave.",
      answer:"paternity", distractors:["maternity","parental","fraternity"]},
    {section:'5B', level:3, prompt:"Job cuts that make workers lose their jobs are called ___.",
      answer:"redundancies", distractors:["dismissals","resignations","retirements"]},
    {section:'5B', level:3, prompt:"Pay linked to how well you do your job is ___-related pay.",
      answer:"performance", distractors:["production","productive","performing"]},
    {section:'5B', level:4, prompt:"'Safety training is ___' — you absolutely must do it.",
      answer:"mandatory", distractors:["mandated","obliged","compulsive"]},
    {section:'5B', level:4, prompt:"'Employers are legally ___ to provide protective clothing.'",
      answer:"obliged", distractors:["forced","demanded","insisted"]},
    {section:'5B', level:5, prompt:"'You'll be ___ to hold a diving certificate for this job.'",
      answer:"required", distractors:["requested","requisite","demanded"]},
    {section:'5B', level:5, prompt:"The training and certificates a job demands are your ___.",
      answer:"qualifications", distractors:["qualities","credentials","competences"]},
    {section:'5B', level:6, prompt:"Complete formally: 'Visitors are not ___ to bring food into the building.'",
      answer:"permitted", distractors:["permissible","allowance","admitted"]},
    {section:'5B', level:7, prompt:"'You ___ have to pay tax on it' — meaning it isn't necessary.",
      answer:"don't", distractors:["mustn't","can't","shouldn't"]},
    {section:'5B', level:8, prompt:"'You ___ to get some experience first' — mild advice, not an obligation.",
      answer:"ought", distractors:["must","have","should"]},

    /* ---- 5C: recalling & speculating ---- */
    {section:'5C', level:1, prompt:"'It's ___ my mind' — I've forgotten it.",
      answer:"slipped", distractors:["slid","escaped","dropped"]},
    {section:'5C', level:2, prompt:"'If my memory ___ me correctly…'",
      answer:"serves", distractors:["services","serviced","helps"]},
    {section:'5C', level:2, prompt:"'I'd ___ a guess that it cost about two thousand euros.'",
      answer:"hazard", distractors:["risk","chance","hazardous"]},
    {section:'5C', level:3, prompt:"'What ___ out in my mind is how quiet the room went.'",
      answer:"stands", distractors:["stood","sticks","comes"]},
    {section:'5C', level:3, prompt:"'I was under the ___ that you'd already left the company.'",
      answer:"impression", distractors:["idea","opinion","impressive"]},
    {section:'5C', level:4, prompt:"'No ___ you've heard the news already.'",
      answer:"doubt", distractors:["question","wonder","doubtless"]},
    {section:'5C', level:4, prompt:"Which expression introduces something you are recalling, with slight uncertainty?",
      answer:"If my memory serves me correctly", distractors:["I'd hazard a guess","No doubt you heard","Presuming you're right"]},
    {section:'5C', level:5, prompt:"'___ a guess, I'd say she's about forty.'",
      answer:"Hazarding", distractors:["Hazard","Hazarded","Hazardly"]},
    {section:'5C', level:5, prompt:"Recalling or speculating? 'I'd hazard a guess that…'",
      answer:"Speculating", distractors:["Recalling","Confirming","Denying"]},
    {section:'5C', level:6, prompt:"'It's pointless to ___ about what might have happened.'",
      answer:"speculate", distractors:["spectate","specify","speculating"]},
    {section:'5C', level:7, prompt:"Which of these is NOT used for recalling?",
      answer:"I'd hazard a guess", distractors:["If my memory serves me","What stands out in my mind","I think I remember"]},
    {section:'5C', level:8, prompt:"'I was under the impression that…' suggests the speaker…",
      answer:"believed something that may not be true", distractors:["is certain of a fact","is recalling it exactly","is asking a question"]},
    /* ---- added later: transformation, error correction, collocation, register and
           stress, so the ladder isn't only gapped sentences ---- */
    {section:'5A', level:2, prompt:"Change the verb 'to convict' into the noun for the court's decision.",
      answer:"conviction", distractors:["convictment","convicture","convicting"]},
    {section:'5A', level:3, prompt:"Which sentence is correct?",
      answer:"He was accused of fraud.", distractors:["He was accused for fraud.","He was accused with fraud.","He was accused on fraud."]},
    {section:'5A', level:4, prompt:"Which word does NOT belong with the others?",
      answer:"sabbatical", distractors:["verdict","jury","testimony"]},
    {section:'5A', level:5, prompt:"Which verb goes with 'a sentence', meaning to undergo the punishment?",
      answer:"serve", distractors:["make","do","take"]},
    {section:'5A', level:6, prompt:"Which is the correct formal version?",
      answer:"the prisoners, many of whom reoffend", distractors:["the prisoners, many of who reoffend","the prisoners that many reoffend","the prisoners which many of them reoffend"]},
    {section:'5B', level:2, prompt:"Change the verb 'oblige' into the noun for a duty you must fulfil.",
      answer:"obligation", distractors:["obligement","obligeance","obligity"]},
    {section:'5B', level:3, prompt:"Which sentence is correct?",
      answer:"You must wear a helmet.", distractors:["You must to wear a helmet.","You must wearing a helmet.","You must worn a helmet."]},
    {section:'5B', level:4, prompt:"Change the adjective 'redundant' into the noun for the job cuts.",
      answer:"redundancy", distractors:["redundance","redundantness","redundation"]},
    {section:'5B', level:5, prompt:"Which sentence is correct?",
      answer:"He was made redundant.", distractors:["He was made redundancy.","He was made a redundant.","He was done redundant."]},
    {section:'5B', level:6, prompt:"Which is the most formal way of refusing permission?",
      answer:"Visitors are not permitted to bring food.", distractors:["Visitors can't bring food.","Visitors mustn't bring food.","Visitors aren't allowed food."]},
    {section:'5C', level:2, prompt:"Change the verb 'to speculate' into the noun.",
      answer:"speculation", distractors:["speculating","speculance","specularity"]},
    {section:'5C', level:3, prompt:"Which one does NOT show uncertainty?",
      answer:"No doubt", distractors:["I'd hazard a guess","I'm not entirely sure","Presumably"]},
    {section:'5C', level:4, prompt:"Which adjective does NOT go with 'memory'?",
      answer:"heavy", distractors:["vague","painful","lasting"]},
    {section:'5C', level:5, prompt:"Change the verb 'assume' into the noun.",
      answer:"assumption", distractors:["assumingness","assumance","assumal"]},
    {section:'5C', level:6, prompt:"Which sentence is correct?",
      answer:"If my memory serves me correctly…", distractors:["If my memory serves me correct…","If my memory serves to me correctly…","If my memory is serving me correct…"]},
    {section:'5C', level:7, prompt:"Which syllable carries the main stress in 're-ha-bi-li-ta-tion'?",
      answer:"the 5th — TA", distractors:["the 1st — re","the 3rd — bi","the 6th — tion"]},
  ],

  millionaireSectionNames: {
    '5A':'5A · Crime & justice (17 questions)',
    '5B':'5B · Employment & obligation (17 questions)',
    '5C':'5C · Recalling & speculating (18 questions)',
  },

  raceSectionNames: {
    '5A':'5A · Crime & justice (16 words)',
    '5B':'5B · Employment & obligation (16 words)',
    '5C':'5C · Recalling & speculating (16 words)',
  },
});
