/* ================= Content bank — Empower C1 Unit 4: Consciousness =================
   Data only. Consumed by game-hub/hub-engine.js via window.UNIT. */
(window.UNITS = window.UNITS || []).push({
  id: "unit-4",
  label: "Cambridge Empower C1 · Unit 4 · Consciousness",
  card: { num: "Unit 4", title: "Consciousness", blurb: "Instinct & reason, memory, have/get, tact and idioms, profile writing (4A–4D).", sections: "4A–4D" },
  intro: "Choose a template. You'll pick the content next — mix and match any of 4A–4D.",

  jeopardySectionLabels: {
    '4A': '4A · That little voice in your head',
    '4B': '4B · He got himself locked in a shed',
    '4C': "4C · I see where you're coming from",
    '4D': '4D · So what was her breakthrough moment?',
  },

  jeopardyCategories: [
    { id:'instinct-vocab', section:'4A', name:'Instinct Vocabulary', clues:[
      {v:100, q:"Making decisions based on logic and evidence, not emotion.", a:"rational"},
      {v:200, q:"Deciding to do something suddenly, without planning it.", a:"on impulse (or 'on a whim')"},
      {v:300, q:"Knowing something without being consciously aware of it.", a:"subconsciously"},
      {v:400, q:"Carefully considering the advantages and disadvantages before deciding.", a:"weigh up"},
      {v:500, q:"A near-synonym for 'on impulse' — doing something on a sudden idea.", a:"on a whim"},
    ]},
    { id:'noun-phrases', section:'4A', name:'Noun Phrases', clues:[
      {v:100, q:"What structure is 'a chance meeting'? (article + ? + ?)", a:"article + noun + noun"},
      {v:200, q:"Rephrase as a two-word noun phrase: 'a meeting which happens by chance'.", a:"a chance meeting"},
      {v:300, q:"'Humanity's oldest survival mechanisms' combines a possessive with which kind of adjective?", a:"a superlative (possessive + superlative + compound noun)"},
      {v:400, q:"True or false: a noun phrase can contain a whole prepositional phrase, e.g. 'a funny feeling in your stomach'.", a:"True"},
      {v:500, q:"Combine using adjective + adjective + noun: 'thoughts that are dark and secret'.", a:"dark, secret thoughts"},
    ]},
    { id:'trust-gut', section:'4A', name:'Trust Your Gut (reading)', clues:[
      {v:100, q:"According to the article, which side of the brain is home to intuition?", a:"the right hemisphere / right brain"},
      {v:200, q:"Name one physical symptom the article says signals intuition at work.", a:"clammy palms / a tingle up the spine / a funny feeling in your stomach"},
      {v:300, q:"The article says intuition is most reliable in which kind of situation — relaxed, or high-pressure?", a:"high-pressure / under stress"},
      {v:400, q:"What does the logical left brain tend to do with the right brain's urges?", a:"dismiss them as irrational"},
      {v:500, q:"What's the article's advice for decisions that could affect your whole future?", a:"use your whole brain — don't discount your gut instincts"},
    ]},
    { id:'memory-vocab', section:'4B', name:'Memory Vocabulary', clues:[
      {v:100, q:"A memory that's unclear or hazy: a ___ memory.", a:"vague memory"},
      {v:200, q:"A memory that makes you unhappy to recall: a ___ memory.", a:"painful memory"},
      {v:300, q:"A memory with clear, sharp sensations: a ___ memory.", a:"vivid memory"},
      {v:400, q:"Being able to recall things perfectly, as if from a picture: a ___ memory.", a:"photographic memory"},
      {v:500, q:"A memory of something that happened a long time ago: a ___ memory.", a:"distant memory"},
    ]},
    { id:'have-get', section:'4B', name:'Have & Get Structures', clues:[
      {v:100, q:"Complete with have or get: 'My parents ___ the kitchen renovated' (someone else did the work).", a:"had (or got)"},
      {v:200, q:"'I had my toys stolen' — is the subject responsible for the action, or on the receiving end of it?", a:"on the receiving end — something happened to them"},
      {v:300, q:"'He got himself locked in the shed' — was this on purpose or by accident?", a:"by accident, and he caused it himself"},
      {v:400, q:"Fill the gap: 'His disappearance ___ everyone looking for him.'", a:"got"},
      {v:500, q:"Explain the meaning of 'She had me sitting on my own.'", a:"she caused me to sit alone — the subject made someone else do it"},
    ]},
    { id:'have-get-uses', section:'4B', name:'Have & Get: Which Use?', clues:[
      {v:100, q:"Which use is this? 'They had their roof fixed.'", a:"the subject paid somebody else to do a job"},
      {v:200, q:"Which use is this? 'We got our car broken into.'", a:"the subject's possessions were harmed by somebody else"},
      {v:300, q:"Which use is this? 'He got me to play when nobody else could.'", a:"the subject caused somebody to do something"},
      {v:400, q:"Which use is this? 'He got himself locked in the garden shed.'", a:"the subject caused what happened to them"},
      {v:500, q:"What's the difference between 'He got locked in the shed' and 'He got himself locked in the shed'?", a:"the second says it was his own doing; the first just says it happened to him"},
    ]},
    { id:'have-get-transform', section:'4B', name:'Have & Get: Transform It', clues:[
      {v:100, q:"Rewrite with had: 'Someone stole my bike.'", a:"I had my bike stolen."},
      {v:200, q:"Rewrite with got: 'Someone broke my arm in a football match.'", a:"I got my arm broken in a football match."},
      {v:300, q:"Rewrite with had: 'She made me do all her homework.'", a:"She had me doing all her homework."},
      {v:400, q:"Rewrite with got: 'I persuaded my mum to say I was sick.'", a:"I got my mum to say I was sick."},
      {v:500, q:"Rewrite with got: 'My brother caused me to be punished unfairly.'", a:"My brother got me punished unfairly."},
    ]},
    { id:'false-memories', section:'4B', name:'False Memories & Eyewitnesses', clues:[
      {v:100, q:"Very few people can remember events before what age, according to the text?", a:"age two"},
      {v:200, q:"What do brain scans show about false memories compared to real ones?", a:"they look very similar in neural activity"},
      {v:300, q:"Name one factor the article gives for why eyewitness testimony can be unreliable.", a:"stress/trauma, time elapsed, police influence, gaze direction — any one"},
      {v:400, q:"What is a police 'line-up' used for?", a:"for a witness to try to identify a suspect among several people"},
      {v:500, q:"What's a paradoxical clue that a childhood memory might be fake, according to the text?", a:"having very complex, detailed, sensory detail actually makes it more likely to be invented"},
    ]},
    /* 4C and 4D had no categories at all, though the unit card claimed 4A-4D —
       so picking those sections gave you a board built from the other two. */
    { id:'being-tactful', section:'4C', name:'Being Tactful', clues:[
      {v:100, q:"Complete: 'I beg to ___' — a polite way of disagreeing.", a:"differ"},
      {v:200, q:"Complete: 'With all due ___, I don't think that's your decision.'", a:"respect"},
      {v:300, q:"Complete: 'No ___ intended, but I couldn't follow your argument.'", a:"offence"},
      {v:400, q:"Which softens a criticism: 'don't take this personally' or 'I beg to differ'?", a:"don't take this personally"},
      {v:500, q:"Complete the softener you add after a blunt remark: 'I mean that in the ___ possible way.'", a:"nicest"},
    ]},
    { id:'idioms-homophones', section:'4C', name:'Idioms & Homophones', clues:[
      {v:100, q:"Idiom: to say exactly the right thing is to hit the ___ on the head.", a:"nail"},
      {v:200, q:"Finish the idiom Oscar uses about Max: 'like trying to get ___ out of a stone'.", a:"blood"},
      {v:300, q:"What do we call two words that sound the same but are spelled differently?", a:"homophones"},
      {v:400, q:"Give the homophone of 'allowed'.", a:"aloud"},
      {v:500, q:"Being too forceful in your approach: '___-handed'.", a:"heavy"},
    ]},
    { id:'time-expressions', section:'4D', name:'Time Expressions', clues:[
      {v:100, q:"Time expression meaning 'right away'.", a:"immediately"},
      {v:200, q:"Time expression meaning 'slowly, over time'.", a:"gradually"},
      {v:300, q:"Complete: '___ long, she was writing her own songs.'", a:"before"},
      {v:400, q:"Complete: 'The ___ I heard her voice, I knew.'", a:"instant"},
      {v:500, q:"Complete the emphatic structure: 'It ___ until she was 17 that she performed.'", a:"wasn't"},
    ]},
    { id:'profile-writing', section:'4D', name:'Profile Writing', clues:[
      {v:100, q:"What do we call an article about a person's life and career?", a:"a profile"},
      {v:200, q:"A profile should carry at least one of these, in the subject's own words.", a:"a quote"},
      {v:300, q:"Describing this helps the reader picture where the interview took place.", a:"the setting"},
      {v:400, q:"Name one thing worth asking about in a profile interview.", a:"achievements / breakthrough moment / influences"},
      {v:500, q:"Should a profile argue the writer's own opinion of the subject?", a:"no — it reports and quotes, it doesn't argue"},
    ]},
  ],

  blockbustersBank: [
    /* ---- typed forms: the shape of the question is the task (Kit.prompt) ---- */
    {section:'4A', type:'anagram', letter:'I', clue:"Unscramble: acting suddenly, without planning it.", answer:"Impulse"},
    {section:'4B', type:'anagram', letter:'W', clue:"Unscramble: someone who saw it happen.", answer:"Witness"},
    {section:'4C', type:'anagram', letter:'T', clue:"Unscramble: skill in not causing offence.", answer:"Tact"},
    {section:'4D', type:'anagram', letter:'M', clue:"Unscramble: the point at which everything changed.", answer:"Moment"},
    {section:'4A', type:'oddoneout', letter:'K', clue:"Which does NOT belong: hunch / instinct / kettle", answer:"Kettle"},
    {section:'4B', type:'oddoneout', letter:'H', clue:"Which does NOT belong: recall / memory / hedge", answer:"Hedge"},
    {section:'4C', type:'oddoneout', letter:'S', clue:"Which does NOT belong: tactful / diplomatic / sarcastic", answer:"Sarcastic"},
    {section:'4D', type:'oddoneout', letter:'C', clue:"Which does NOT belong: eventually / meanwhile / cautious", answer:"Cautious"},
    {section:'4A', letter:'R', clue:"The opposite of emotional — deciding with your head, not your heart.", answer:"Rational"},
    {section:'4A', letter:'I', clue:"Doing something suddenly, without planning it — 'on ___'.", answer:"Impulse"},
    {section:'4A', letter:'S', clue:"'We ___ pick up on tiny changes in someone's face' — below conscious awareness.", answer:"Subconsciously"},
    {section:'4A', letter:'W', clue:"To ___ up the options is to consider the pros and cons before deciding.", answer:"Weigh"},
    {section:'4A', letter:'O', clue:"Based on facts, not feelings — the opposite of subjective.", answer:"Objective"},
    {section:'4A', letter:'D', clue:"An expression meaning 'in your heart, even if you won't admit it' — '___ down'.", answer:"Deep"},
    {section:'4A', letter:'G', clue:"Informal word for instinct — trust your ___.", answer:"Gut"},
    {section:'4A', letter:'H', clue:"A strong feeling that something is true, without proof.", answer:"Hunch"},
    {section:'4B', letter:'V', clue:"A memory that's unclear or hazy is a ___ one.", answer:"Vague"},
    {section:'4B', letter:'P', clue:"A memory that makes you unhappy to recall is a ___ one.", answer:"Painful"},
    {section:'4B', letter:'L', clue:"A memory that stays with you permanently is a ___ one.", answer:"Lasting"},
    {section:'4B', letter:'F', clue:"Capable of making mistakes — used to describe eyewitness testimony.", answer:"Fallible"},
    {section:'4B', letter:'E', clue:"Someone who saw a crime happen.", answer:"Eyewitness"},
    {section:'4B', letter:'M', clue:"Easily shaped or changed — used to describe how flexible our memories are.", answer:"Malleable"},
    {section:'4B', letter:'G', clue:"The direction someone is looking — an officer's ___ might influence a witness.", answer:"Gaze"},
    {section:'4B', letter:'E', clue:"To add invented details to a story, making it more dramatic.", answer:"Embellish"},
    {section:'4C', letter:'N', clue:"Idiom: to say exactly the right thing — hit the ___ on the head.", answer:"Nail"},
    {section:'4C', letter:'D', clue:"'I beg to ___' — a tactful way of disagreeing.", answer:"Differ"},
    {section:'4C', letter:'R', clue:"'With all due ___' — softening a criticism politely.", answer:"Respect"},
    {section:'4C', letter:'U', clue:"Feeling worried or not quite comfortable about something.", answer:"Uneasy"},
    {section:'4C', letter:'N', clue:"An adjective for a nagging feeling that won't go away.", answer:"Nagging"},
    {section:'4C', letter:'F', clue:"Someone 'not particularly ___' isn't very willing to share information.", answer:"Forthcoming"},
    {section:'4D', letter:'S', clue:"A time expression meaning 'without delay, right after' — '___ afterwards'.", answer:"Shortly"},
    {section:'4D', letter:'I', clue:"A time expression meaning 'right away'.", answer:"Immediately"},
    {section:'4D', letter:'G', clue:"A time expression meaning 'slowly, over time'.", answer:"Gradually"},
    {section:'4D', letter:'B', clue:"A word for sudden success — also the title of Noni-K's debut album.", answer:"Breakout"},

    /* ---- expansion: 4A ---- */
    {section:'4A', letter:'I', clue:"An adjective for a feeling you can't explain or account for.", answer:"Inexplicable"},
    {section:'4A', letter:'I', clue:"An ___ urge is one you simply cannot resist.", answer:"Irresistible"},
    {section:'4A', letter:'C', clue:"The part of the brain the article calls logical and coherent — the ___ left brain.", answer:"Conscious"},
    {section:'4A', letter:'P', clue:"Clammy ___ are one physical sign that intuition is at work.", answer:"Palms"},
    {section:'4A', letter:'S', clue:"The '___ sense' — a supposed extra sense beyond the usual five.", answer:"Sixth"},
    {section:'4A', letter:'C', clue:"Two events happening together by chance.", answer:"Coincidence"},
    {section:'4A', letter:'I', clue:"The formal noun for gut feeling or instinctive knowing.", answer:"Intuition"},
    {section:'4A', letter:'H', clue:"Each half of the brain is called a ___.", answer:"Hemisphere"},

    /* ---- expansion: 4B ---- */
    {section:'4B', letter:'S', clue:"Your brother or sister.", answer:"Sibling"},
    {section:'4B', letter:'P', clue:"The person who committed the crime.", answer:"Perpetrator"},
    {section:'4B', letter:'T', clue:"The formal word for evidence a witness gives in court.", answer:"Testimony"},
    {section:'4B', letter:'S', clue:"Easily influenced — our memories are ___ to suggestion.", answer:"Susceptible"},
    {section:'4B', letter:'R', clue:"'Bear little ___ to' means to be very unlike something.", answer:"Resemblance"},
    {section:'4B', letter:'T', clue:"Humankind ___ on stories, according to the reading.", answer:"Thrives"},
    {section:'4B', letter:'D', clue:"The person accused of a crime in court.", answer:"Defendant"},
    {section:'4B', letter:'J', clue:"The group of people who decide a verdict in court.", answer:"Jury"},

    /* ---- 4B: structures with have and get ---- */
    {section:'4B', letter:'H', clue:"The verb in 'They ___ their roof fixed' — paying someone else to do a job.", answer:"Had"},
    {section:'4B', letter:'G', clue:"The verb in 'We ___ our car broken into' — something bad happened to our property.", answer:"Got"},
    {section:'4B', letter:'C', clue:"'He got himself locked in the shed' — he ___ what happened to him.", answer:"Caused"},
    {section:'4B', letter:'S', clue:"In 'I had my bike stolen', which grammatical role does 'I' play — subject or object?", answer:"Subject"},
    {section:'4B', letter:'H', clue:"Fill the gap: 'She ___ me doing all her homework.'", answer:"Had"},
    {section:'4B', letter:'P', clue:"In 'My brother got me punished unfairly', what is the past participle?", answer:"Punished"},
    {section:'4B', letter:'R', clue:"'My parents were having the kitchen ___' — someone else did the work.", answer:"Renovated"},
    {section:'4B', letter:'T', clue:"In 'I got my mum to say I was sick', which one-word particle comes before 'say'?", answer:"To"},

    /* ---- expansion: 4C ---- */
    {section:'4C', letter:'T', clue:"The skill of saying difficult things without causing offence.", answer:"Tact"},
    {section:'4C', letter:'O', clue:"'No ___ intended' — said before a potentially rude remark.", answer:"Offence"},
    {section:'4C', letter:'P', clue:"'I do take your ___, but…' — acknowledging before disagreeing.", answer:"Point"},
    {section:'4C', letter:'B', clue:"Idiom: getting information from an unwilling person is like getting ___ out of a stone.", answer:"Blood"},
    {section:'4C', letter:'H', clue:"Being too forceful or harsh in your approach — '___-handed'.", answer:"Heavy"},
    {section:'4C', letter:'H', clue:"Two words that sound the same but are spelled differently.", answer:"Homophones"},
    {section:'4C', letter:'C', clue:"Criticism meant to help rather than attack is ___.", answer:"Constructive"},
    {section:'4C', letter:'P', clue:"Behaving in a professional way — Nadia values ___ in interviews.", answer:"Professionalism"},

    /* ---- expansion: 4D ---- */
    {section:'4D', letter:'P', clue:"An article describing a person's life and career.", answer:"Profile"},
    {section:'4D', letter:'Q', clue:"Someone's exact words, reproduced in an article.", answer:"Quote"},
    {section:'4D', letter:'S', clue:"A time expression meaning 'afterwards, following that'.", answer:"Subsequently"},
    {section:'4D', letter:'I', clue:"'The ___ I heard her music, I knew' — a time expression meaning 'the moment'.", answer:"Instant"},
    {section:'4D', letter:'B', clue:"'___ long, she was creating songs' — a time expression meaning 'soon after'.", answer:"Before"},
    {section:'4D', letter:'W', clue:"'It ___ until she was 17 that she felt confident' — the emphatic time structure.", answer:"Wasn't"},
    {section:'4D', letter:'S', clue:"The place and surroundings an interview happens in.", answer:"Setting"},
    {section:'4D', letter:'A', clue:"Things a person has accomplished — one thing to ask about in an interview.", answer:"Achievements"},
  ],

  blockbustersSectionNames: {
    '4A':'4A · Instinct & reason (18 clues)',
    '4B':'4B · Memory, eyewitnesses & have/get (26 clues)',
    '4C':'4C · Tact & idioms (16 clues)',
    '4D':'4D · Profile writing & time expressions (14 clues)',
  },

  /* ---- Race to the Board ----------------------------------------------------
     Gapped sentences; the answers become the words on the board, so each is a
     single word and none repeats. Distractors aren't authored — every other word
     on screen is a real target word from the chosen sections. */
  raceBank: [
    {section:'4C', type:'errorfix', prompt:"Correct it: 'She gave a very *tactic* reply.'", answer:"Tactful"},
    /* ---- 4A: instinct & reason ---- */
    {section:'4A', prompt:"She's completely ___ — she'd never decide anything on a feeling.", answer:"Rational"},
    {section:'4A', prompt:"He bought the tickets on ___, without thinking it through.", answer:"Impulse"},
    {section:'4A', prompt:"We ___ pick up on tiny changes in people's faces.", answer:"Subconsciously"},
    {section:'4A', prompt:"Take a day to ___ up the pros and cons before you decide.", answer:"Weigh"},
    {section:'4A', prompt:"A good judge stays ___ and sticks to the facts.", answer:"Objective"},
    {section:'4A', prompt:"___ down, I knew the job wasn't right for me.", answer:"Deep"},
    {section:'4A', prompt:"Trust your ___ — your first reaction is often the right one.", answer:"Gut"},
    {section:'4A', prompt:"I had a ___ she was lying, though I couldn't prove it.", answer:"Hunch"},
    {section:'4A', prompt:"They booked the flight on a ___, three hours before takeoff.", answer:"Whim"},
    {section:'4A', prompt:"Doctors often rely on ___ built up over years of practice.", answer:"Intuition"},
    {section:'4A', prompt:"Meeting her twice in one week was pure ___.", answer:"Coincidence"},
    {section:'4A', prompt:"Each ___ of the brain handles different kinds of thinking.", answer:"Hemisphere"},
    {section:'4A', prompt:"There was an ___ feeling of dread that she couldn't account for.", answer:"Inexplicable"},
    {section:'4A', prompt:"Animals rely on ___ rather than reasoning.", answer:"Instinct"},

    /* ---- 4B: memory, eyewitnesses & have/get ---- */
    {section:'4B', prompt:"I've only a ___ memory of that holiday — I was three.", answer:"Vague"},
    {section:'4B', prompt:"Talking about the accident brings back ___ memories.", answer:"Painful"},
    {section:'4B', prompt:"I have a ___ memory of the day — I can still smell the smoke.", answer:"Vivid"},
    {section:'4B', prompt:"She has a ___ memory and can recall a page after one reading.", answer:"Photographic"},
    {section:'4B', prompt:"It's a ___ memory now, faded by thirty years.", answer:"Distant"},
    {section:'4B', prompt:"That summer left a ___ impression on all of us.", answer:"Lasting"},
    {section:'4B', prompt:"Eyewitness evidence is ___ — witnesses make honest mistakes.", answer:"Fallible"},
    {section:'4B', prompt:"Memory is ___: it reshapes itself every time we recall something.", answer:"Malleable"},
    {section:'4B', prompt:"He tends to ___ the story a little more each time he tells it.", answer:"Embellish"},
    {section:'4B', prompt:"Children are especially ___ to suggestion from adults.", answer:"Susceptible"},
    {section:'4B', prompt:"The ___ was never caught, despite three witnesses.", answer:"Perpetrator"},
    {section:'4B', prompt:"They ___ their roof repaired last spring — a builder did it.", answer:"Had"},
    {section:'4B', prompt:"We ___ our car broken into while we were away.", answer:"Got"},
    {section:'4B', prompt:"My parents were having the kitchen ___ by a local firm.", answer:"Renovated"},

    /* ---- 4C: tact & idioms ---- */
    {section:'4C', prompt:"I beg to ___ — I read the situation quite differently.", answer:"Differ"},
    {section:'4C', prompt:"With all due ___, I don't think that's your decision to make.", answer:"Respect"},
    {section:'4C', prompt:"Don't take this ___, but the opening paragraph doesn't work.", answer:"Personally"},
    {section:'4C', prompt:"I do take your ___, but there was more we could have done.", answer:"Point"},
    {section:'4C', prompt:"No ___ intended, but I couldn't follow your argument at all.", answer:"Offence"},
    {section:'4C', prompt:"He wasn't particularly ___ about why he'd left his last job.", answer:"Forthcoming"},
    {section:'4C', prompt:"Saying difficult things kindly is a matter of ___.", answer:"Tact"},
    {section:'4C', prompt:"I felt ___ about the whole arrangement, though I couldn't say why.", answer:"Uneasy"},
    {section:'4C', prompt:"There was a ___ doubt at the back of my mind all week.", answer:"Nagging"},
    {section:'4C', prompt:"Getting an answer out of him was like getting ___ out of a stone.", answer:"Blood"},
    {section:'4C', prompt:"You can be a bit ___-handed with junior staff sometimes.", answer:"Heavy"},
    {section:'4C', prompt:"Criticism meant to help rather than wound is ___.", answer:"Constructive"},
    {section:'4C', prompt:"I mean that in the ___ possible way, of course.", answer:"Nicest"},
    {section:'4C', prompt:"I'm ___ I have to say this, but the plan won't work.", answer:"Afraid"},

    /* ---- 4D: profile writing & time expressions ---- */
    {section:'4D', prompt:"___ afterwards, she was offered a recording contract.", answer:"Shortly"},
    {section:'4D', prompt:"She knew ___ that this was the band she wanted to join.", answer:"Immediately"},
    {section:'4D', prompt:"___, over about two years, her confidence grew.", answer:"Gradually"},
    {section:'4D', prompt:"She toured Europe and ___ released a second album.", answer:"Subsequently"},
    {section:'4D', prompt:"The ___ I heard her voice, I knew she'd be famous.", answer:"Instant"},
    {section:'4D', prompt:"___ long, she was writing songs of her own.", answer:"Before"},
    {section:'4D', prompt:"It ___ until she was seventeen that she performed in public.", answer:"Wasn't"},
    {section:'4D', prompt:"Her debut album was called '___', and it made her name.", answer:"Breakout"},
    {section:'4D', prompt:"A ___ is an article about a person's life and career.", answer:"Profile"},
    {section:'4D', prompt:"A good profile uses at least one direct ___ from the subject.", answer:"Quote"},
    {section:'4D', prompt:"Describing the ___ of the interview helps the reader picture it.", answer:"Setting"},
    {section:'4D', prompt:"Ask about the person's ___ — what they're proudest of.", answer:"Achievements"},
    {section:'4D', prompt:"She struggled for years and ___ found her own sound.", answer:"Eventually"},
    {section:'4D', prompt:"___ she started writing, she couldn't stop.", answer:"Once"},
  ],

  raceSectionNames: {
    '4A':'4A · Instinct & reason (14 words)',
    '4B':'4B · Memory & have/get (14 words)',
    '4C':'4C · Tact & idioms (15 words)',
    '4D':'4D · Profile writing & time expressions (14 words)',
  },

  /* ---- Millionaire ----------------------------------------------------------
     `level` 1-8 maps to the rungs, and every section covers all eight so a single
     section fills a ladder. The distractors are the teaching: each wrong option is
     an error this class would plausibly make — a real word with the wrong meaning,
     a wrong collocation, or a form error — never filler. */
  millionaireBank: [
    /* ---- typed forms: error correction, marked with *asterisks* ---- */
    {section:'4A', type:'errorfix', level:3, prompt:"Correct the error: 'She decided *on impulsive*.'",
      answer:"on impulse", distractors:["in impulse","by impulsive","on the impulsive"]},
    {section:'4B', type:'errorfix', level:4, prompt:"Correct the error: 'I *had cut* my hair at the salon.'",
      answer:"had my hair cut", distractors:["have cut my hair","did cut my hair","had cutting my hair"]},
    {section:'4C', type:'errorfix', level:5, prompt:"Correct the error: 'He was very *tactic* about the news.'",
      answer:"tactful", distractors:["tactics","tactical","tacted"]},
    /* ---- 4A: instinct & reason ---- */
    {section:'4A', level:1, prompt:"An informal word for instinct: 'trust your ___'.",
      answer:"gut", distractors:["stomach","belly","heart"]},
    {section:'4A', level:2, prompt:"'He bought it on ___' — suddenly, without planning.",
      answer:"impulse", distractors:["instinct","a hunch","reflex"]},
    {section:'4A', level:3, prompt:"Which adjective means 'based on facts, not feelings'?",
      answer:"objective", distractors:["subjective","rational","impartial"]},
    {section:'4A', level:4, prompt:"A feeling that something is true, with no proof to show for it:",
      answer:"a hunch", distractors:["a hint","a whim","a guess"]},
    {section:'4A', level:5, prompt:"'They flew to Rome on a ___' — on a sudden, unplanned wish.",
      answer:"whim", distractors:["impulse","hunch","urge"]},
    {section:'4A', level:6, prompt:"Which means 'impossible to explain or account for'?",
      answer:"inexplicable", distractors:["unaccountable","implausible","indescribable"]},
    {section:'4A', level:7, prompt:"Which noun phrase is correctly ordered?",
      answer:"a surprisingly reliable gut feeling",
      distractors:["a gut reliably surprising feeling","a gut feeling surprisingly reliable",
                   "a reliable surprisingly gut feeling"]},
    {section:'4A', level:8, prompt:"Change the adjective 'intuitive' into the noun for the faculty itself.",
      answer:"intuition", distractors:["intuitiveness","intuitivity","intuitation"]},

    /* ---- 4B: memory, eyewitnesses & have/get ---- */
    {section:'4B', level:1, prompt:"A memory that is unclear or hazy is a ___ one.",
      answer:"vague", distractors:["faint","blurred","distant"]},
    {section:'4B', level:2, prompt:"A memory so detailed you can picture every part of it is ___.",
      answer:"vivid", distractors:["lasting","sharp","photographic"]},
    {section:'4B', level:3, prompt:"'They ___ their roof repaired' — they paid someone else to do it.",
      answer:"had", distractors:["got themselves","have been","did"]},
    {section:'4B', level:4, prompt:"'We ___ our car broken into' — something bad happened to us.",
      answer:"got", distractors:["had ourselves","made","have"]},
    {section:'4B', level:5, prompt:"Which means 'capable of making mistakes'?",
      answer:"fallible", distractors:["falsifiable","faulty","fallacious"]},
    {section:'4B', level:6, prompt:"Which means 'easily shaped or changed'? Memory is famously ___.",
      answer:"malleable", distractors:["mutable","pliant","manipulative"]},
    {section:'4B', level:7, prompt:"Which sentence means somebody else did the work?",
      answer:"She had her portrait painted last year.",
      distractors:["She had painted her portrait last year.",
                   "She got painting her portrait last year.",
                   "She had been painting her portrait last year."]},
    {section:'4B', level:8, prompt:"'I got my mum ___ I was ill.' Which form is correct?",
      answer:"to say", distractors:["say","saying","said"]},

    /* ---- 4C: tact & idioms ---- */
    {section:'4C', level:1, prompt:"Which phrase softens a disagreement most politely?",
      answer:"I beg to differ", distractors:["You're wrong","That's nonsense","I disagree completely"]},
    {section:'4C', level:2, prompt:"'With all due ___, I don't think that's your call.'",
      answer:"respect", distractors:["regard","politeness","courtesy"]},
    {section:'4C', level:3, prompt:"'No ___ intended, but I couldn't follow your argument.'",
      answer:"offence", distractors:["insult","offense taken","harm"]},
    {section:'4C', level:4, prompt:"Which means 'not willing to give information'?",
      answer:"not forthcoming", distractors:["not outspoken","not approachable","not upfront"]},
    {section:'4C', level:5, prompt:"Which idiom describes trying to get information from an unwilling person?",
      answer:"like getting blood out of a stone",
      distractors:["like water off a duck's back","like getting your teeth pulled",
                   "like squeezing a dry sponge"]},
    {section:'4C', level:6, prompt:"Being too forceful in your approach is being ___.",
      answer:"heavy-handed", distractors:["hard-headed","heavy-going","strong-armed"]},
    {section:'4C', level:7, prompt:"Which is used to present a contradictory opinion, not to soften criticism?",
      answer:"That's not the way I see it",
      distractors:["Don't take this personally","I mean that in the nicest possible way",
                   "If you don't mind me saying so"]},
    {section:'4C', level:8, prompt:"Which pair are homophones?",
      answer:"allowed / aloud", distractors:["accept / except","affect / effect","advice / advise"]},

    /* ---- 4D: profile writing & time expressions ---- */
    {section:'4D', level:1, prompt:"Which time expression means 'right away'?",
      answer:"immediately", distractors:["shortly","gradually","eventually"]},
    {section:'4D', level:2, prompt:"Which means 'slowly, over a period of time'?",
      answer:"gradually", distractors:["subsequently","instantly","briefly"]},
    {section:'4D', level:3, prompt:"'___ afterwards, she signed a record deal.'",
      answer:"Shortly", distractors:["Lately","Presently","Currently"]},
    {section:'4D', level:4, prompt:"Which means 'afterwards, following that'?",
      answer:"subsequently", distractors:["consequently","previously","accordingly"]},
    {section:'4D', level:5, prompt:"'___ long, she was writing her own songs.'",
      answer:"Before", distractors:["Since","After","Until"]},
    {section:'4D', level:6, prompt:"'The ___ I heard her sing, I knew.' Which completes it?",
      answer:"instant", distractors:["moment that","time when","second of"]},
    {section:'4D', level:7, prompt:"Which sentence uses the emphatic time structure correctly?",
      answer:"It wasn't until she was 17 that she performed in public.",
      distractors:["It wasn't until she was 17 when she performed in public.",
                   "It wasn't till she was 17 she performed in public.",
                   "It was not until she was 17 than she performed in public."]},
    {section:'4D', level:8, prompt:"Which does a profile article NOT normally do?",
      answer:"Argue for the writer's own opinion of the subject",
      distractors:["Quote the subject directly","Describe the setting of the interview",
                   "Trace the subject's career in order"]},

    /* A second question at every rung. With one per rung, both teams meet the
       identical question on their way up — the ladder is per-team, so the depth
       has to be too. */
    {section:'4A', level:1, prompt:"'___ down, she knew it was the wrong choice.'",
      answer:"Deep", distractors:["Far","Low","Way"]},
    {section:'4A', level:2, prompt:"Which means 'below the level of conscious awareness'?",
      answer:"subconsciously", distractors:["unconsciously","self-consciously","semi-consciously"]},
    {section:'4A', level:3, prompt:"'Take a day to ___ up the options.'",
      answer:"weigh", distractors:["weight","way","weighted"]},
    {section:'4A', level:4, prompt:"Two events happening together purely by chance:",
      answer:"a coincidence", distractors:["a consequence","a correlation","a concurrence"]},
    {section:'4A', level:5, prompt:"The supposed extra sense beyond the usual five is the ___ sense.",
      answer:"sixth", distractors:["seventh","inner","extra"]},
    {section:'4A', level:6, prompt:"Which describes an urge you simply cannot resist?",
      answer:"irresistible", distractors:["unresisting","resistless","irresistable"]},
    {section:'4A', level:7, prompt:"Which noun phrase is correctly ordered?",
      answer:"a strong initial gut reaction",
      distractors:["a gut strong initial reaction","an initial strong gut reaction",
                   "a strong gut initial reaction"]},
    {section:'4A', level:8, prompt:"Change the noun 'instinct' into the adjective.",
      answer:"instinctive", distractors:["instinctful","instinctional","instinctory"]},

    {section:'4B', level:1, prompt:"Which adjective does NOT normally go with 'memory'?",
      answer:"heavy", distractors:["vague","painful","lasting"]},
    {section:'4B', level:2, prompt:"A memory from a very long time ago is a ___ one.",
      answer:"distant", distractors:["faraway","remote","far"]},
    {section:'4B', level:3, prompt:"'She ___ me doing all her homework.' Which fits?",
      answer:"had", distractors:["got","made to","let to"]},
    {section:'4B', level:4, prompt:"Which means 'to add invented details to make a story better'?",
      answer:"embellish", distractors:["exaggerate","embroil","elaborate"]},
    {section:'4B', level:5, prompt:"'Our memories are ___ to suggestion' — easily influenced.",
      answer:"susceptible", distractors:["suspicious","receptive","subjected"]},
    {section:'4B', level:6, prompt:"Which noun completes 'the photofit bore little ___ to the suspect'?",
      answer:"resemblance", distractors:["resembling","likeliness","similitude"]},
    {section:'4B', level:7, prompt:"In 'I had my bike stolen', what grammatical role does 'I' play?",
      answer:"subject", distractors:["object","indirect object","agent"]},
    {section:'4B', level:8, prompt:"Which sentence says something bad happened to the speaker?",
      answer:"We got our windows smashed.",
      distractors:["We had our windows fitted.","We got the windows cleaned.",
                   "We had someone clean the windows."]},

    {section:'4C', level:1, prompt:"Which acknowledges the other person before you disagree?",
      answer:"I do take your point, but…",
      distractors:["I beg to differ.","That's not the way I see it.","No offence intended, but…"]},
    {section:'4C', level:2, prompt:"'Don't take this ___' — said before a criticism.",
      answer:"personally", distractors:["personal","seriously","to heart"]},
    {section:'4C', level:3, prompt:"'She handled the whole conversation with great ___.'",
      answer:"tact", distractors:["tactic","tactfulness of manner","tactility"]},
    {section:'4C', level:4, prompt:"'I see where you're ___ from, but I disagree.'",
      answer:"coming", distractors:["going","getting","arriving"]},
    {section:'4C', level:5, prompt:"Criticism intended to help rather than wound is ___.",
      answer:"constructive", distractors:["constructional","instructive","productive"]},
    {section:'4C', level:6, prompt:"Which means 'a worry that keeps returning'?",
      answer:"a nagging doubt", distractors:["a niggling nag","a naggy concern","a nagged feeling"]},
    {section:'4C', level:7, prompt:"Which is used to soften bad news rather than to disagree?",
      answer:"I'm afraid I have to say…",
      distractors:["I beg to differ.","That's not the way I see it.",
                   "I see where you're coming from, but…"]},
    {section:'4C', level:8, prompt:"Which pair are NOT homophones?",
      answer:"desert / dessert", distractors:["their / there","flour / flower","peace / piece"]},

    {section:'4D', level:1, prompt:"Which time expression means 'soon after that'?",
      answer:"shortly afterwards", distractors:["lately","at present","for now"]},
    {section:'4D', level:2, prompt:"Which means 'after a long time, in the end'?",
      answer:"eventually", distractors:["evidently","eventfully","presently"]},
    {section:'4D', level:3, prompt:"Which introduces a point after which something became continuous?",
      answer:"Once she started writing…",
      distractors:["Whenever she started writing…","By the time she started writing…",
                   "As long as she started writing…"]},
    {section:'4D', level:4, prompt:"Which links two events where the second follows the first?",
      answer:"subsequently", distractors:["simultaneously","previously","meanwhile"]},
    {section:'4D', level:5, prompt:"Her debut album, the one that made her name, was called ___.",
      answer:"Breakout", distractors:["Breakthrough","Breakaway","Breakdown"]},
    {section:'4D', level:6, prompt:"Which sentence puts the time expression in a natural place?",
      answer:"Gradually, her confidence grew.",
      distractors:["Her confidence gradually grew up.","Gradually grew her confidence.",
                   "Her gradually confidence grew."]},
    {section:'4D', level:7, prompt:"Which opening would suit a profile article best?",
      answer:"A vivid scene from the interview",
      distractors:["A list of the subject's albums","The writer's opinion of the subject",
                   "A summary of the subject's finances"]},
    {section:'4D', level:8, prompt:"'It wasn't until she was 17 ___ she performed in public.'",
      answer:"that", distractors:["when","which","then"]},
  ],

  millionaireSectionNames: {
    '4A':'4A · Instinct & reason (17 questions)',
    '4B':'4B · Memory & have/get (17 questions)',
    '4C':'4C · Tact & idioms (17 questions)',
    '4D':'4D · Profile writing & time expressions (16 questions)',
  },
});
