/* ================= Content bank — Empower C1 Unit 4: Consciousness =================
   Data only. Consumed by game-hub/hub-engine.js via window.UNIT.
   Authored from material/empower-c1-unit-4/ (pp.43-54).

   **Jeopardy and Blockbusters are all rounds**, as in unit-5.js — 100 clues in 20
   categories and 72 hexagons, five round types per section. Race and Millionaire
   are untouched (Millionaire already draws every rung as a Multiple Choice round;
   Race cannot host one at all), and `bingoBank` holds the 74 single-word calls
   that used to be the Blockbusters bank.

   **Written from the page scans rather than from the previous bank**, which is
   what Unit 5 was not. Most of what is here is the book's own material: 4A's
   synonym pairs (p44 2b) and the doubt-and-uncertainty box (p46), 4B's six
   have/get sentences with their four uses (p47 1d) and the memory collocations
   with the book's definitions (p49 4a), 4C's seven tactful expressions with their
   three uses (p50 2a) and the homophone list (p51 3a), and 4D's time expressions
   in the book's own three-way split (p53 3e-f).

   The rule to hold when editing: **every word in an ordering scale should be the
   unit's own language.** A scale of plausible C1 English the unit never teaches
   reads perfectly normally and quietly breaks the claim the games test *this*
   unit. It is the one defect no check catches. */
(window.UNITS = window.UNITS || []).push({
  id: "unit-4",
  label: "Cambridge Empower C1 · Unit 4 · Consciousness",
  card: { num: "Unit 4", title: "Consciousness", blurb: "Instinct & reason, memory, have/get, tact and idioms, profile writing (4A–4D).", sections: "4A–4D" },
  intro: "Choose a template. You'll pick the content next — mix and match any of 4A–4D.",

  jeopardySectionLabels: {
    '4A': '4A · That little voice in your head',
    '4B': '4B · He got himself locked in a shed',
    '4C': "4C · I see where you're coming from",
    '4D': '4D · So what was her breakthrough moment?',
    '4E': '4E · Sort the whole field — four groups of four',
  },

  /* Every clue on this board is a **round** — a question the room plays from their
     handsets rather than one the teacher reads out. Five categories per section,
     one per round type.

     **Authored from the page scans, not from the previous bank.** The rule this
     unit holds to and the last one did not: *every word in an ordering scale
     appears in the unit's own material.* A scale of plausible C1 English that the
     unit never teaches looks completely normal and quietly breaks the claim the
     whole project rests on — that the games test this unit's target language.
     Most of what is here is the book's own: 4A's synonym pairs (p44 2b), 4B's
     have/get sentences and memory collocations (pp47, 49), 4C's tactful
     expressions with their three uses and the homophone list (pp50, 51), and 4D's
     time expressions with the book's own three-way split (p53 3e). */
  jeopardyCategories: [
    /* ================= 4A · instinct, reason and doubt ================= */
    { id:'4a-connections', section:'4A', clues:[
      {v:100, q:"Four of these are about acting without thinking it through. Find the four.",
        group:{ pick:["impulse","whim","instinct","gut"],
                with:["rational","objective","logical","considered"] }},
      {v:200, q:"Four of these mean weighing something up properly. Find the four.",
        group:{ pick:["rational","objective","considered","deliberate"],
                with:["impulse","whim","hunch","instinct"] }},
      {v:300, q:"Four of these complete the doubt-and-uncertainty phrases. Find the four.",
        group:{ pick:["nagging","groundless","uneasy","born"],
                with:["vivid","distant","painful","lasting"] }},
      {v:400, q:"Four of these are nouns in the doubt-and-uncertainty box. Find the four.",
        group:{ pick:["doubt","feeling","anxieties","worriers"],
                with:["memory","testimony","witness","evidence"] }},
      {v:500, q:"Four of these are the ordinary senses. Find the four.",
        group:{ pick:["sight","hearing","touch","smell"],
                with:["instinct","intuition","hunch","premonition"] }},
    ]},
    { id:'4a-thermometer', section:'4A', clues:[
      {v:100, q:"Put these in order — least thought first.",
        order:{ scale:["on a whim","on impulse","gut feeling","weighing up","rational analysis"],
                low:"no thought at all", high:"worked through step by step",
                gloss:{ 'on a whim':"you did it because you felt like it, that second.",
                        'on impulse':"suddenly, without planning it.",
                        'gut feeling':"a strong sense, but you could not say why.",
                        'weighing up':"putting the advantages against the disadvantages.",
                        'rational analysis':"logic and evidence, not feeling." } }},
      {v:200, q:"Put these in order — least aware first.",
        order:{ scale:["subconsciously","deep down","instinctively","knowingly","deliberately"],
                low:"you had no idea you knew", high:"you meant to",
                gloss:{ subconsciously:"the mind knew it, you did not.",
                        'deep down':"you knew, but had not admitted it.",
                        instinctively:"you acted on it without reasoning.",
                        knowingly:"you were aware as you did it.",
                        deliberately:"you decided, then did it." } }},
      {v:300, q:"Put these in order — mildest worry first.",
        order:{ scale:["fine","uneasy","nagging","alarmed","panicking"],
                low:"nothing is wrong", high:"something is badly wrong",
                gloss:{ fine:"no sense of trouble at all.",
                        uneasy:"that feeling that something is not quite right.",
                        nagging:"it keeps coming back and will not leave you.",
                        alarmed:"you now think there really is a problem.",
                        panicking:"you can no longer think straight about it." } }},
      {v:400, q:"Put these in order — least grounded first.",
        order:{ scale:["groundless","hunch","suspicion","doubt","evidence"],
                low:"nothing behind it at all", high:"something you can point to",
                gloss:{ groundless:"the book's word for a worry with no basis.",
                        hunch:"a feeling you cannot explain.",
                        suspicion:"you have started to think it is true.",
                        doubt:"a nagging sense that all is not as it seems.",
                        evidence:"something outside your head." } }},
      {v:500, q:"Put these in order — quickest judgement first.",
        order:{ scale:["glance","first impression","gut instinct","considered view","objective assessment"],
                low:"a second", high:"weighed up properly",
                gloss:{ glance:"you barely looked.",
                        'first impression':"the book's phrase — and it is often accurate.",
                        'gut instinct':"the feeling doctors admit to following.",
                        'considered view':"you have thought about it.",
                        'objective assessment':"you have taken yourself out of it." } }},
    ]},
    /* Vocabulary 4A exercise 2b (p44): each bold expression is replaced by a word
       or phrase from the box, so the pairs are the book's own. */
    { id:'4a-choice', section:'4A', clues:[
      {v:100, q:"'It's important to be rational.' Which word from the box replaces it?",
        choice:{ options:["objective","deep down","on a whim","consider"], answer:"objective" }},
      {v:200, q:"'On impulse, I applied for a new job.' Which phrase replaces it?",
        choice:{ options:["on a whim","deep down","objective","consider"], answer:"on a whim" }},
      {v:300, q:"'I knew subconsciously that I was making a mistake.' Which phrase replaces it?",
        choice:{ options:["deep down","on a whim","objective","weigh up"], answer:"deep down" }},
      {v:400, q:"'It's important to weigh up the advantages.' Which verb replaces it?",
        choice:{ options:["consider","conclude","convince","confide"], answer:"consider" }},
      {v:500, q:"'You're left with a nagging ___ that all is not quite as it seems.'",
        choice:{ options:["doubt","feeling","pattern","anxiety"], answer:"doubt" }},
    ]},
    { id:'4a-scramble', section:'4A', clues:[
      {v:100, q:"Put the words in order — a doubt you cannot shake.",
        scramble:{ sentence:"You are left with a nagging doubt about it" }},
      {v:200, q:"Put the words in order — the book's phrase for knowing without evidence.",
        scramble:{ sentence:"Other doctors say they feel it in their bones" }},
      {v:300, q:"Put the words in order — worries with nothing behind them.",
        scramble:{ sentence:"More often than not these are groundless anxieties" }},
      {v:400, q:"Put the words in order — something is slightly off.",
        scramble:{ sentence:"This person just does not quite fit the pattern" }},
      {v:500, q:"Put the words in order — what the unit is about.",
        scramble:{ sentence:"Most doctors will admit to following their gut instincts" }},
    ]},
    { id:'4a-anagram', section:'4A', clues:[
      {v:100, q:"based on logic and evidence rather than feeling", anagram:{ word:"rational" }},
      {v:200, q:"not influenced by your own feelings about it", anagram:{ word:"objective" }},
      {v:300, q:"below the level you are aware of", anagram:{ word:"subconscious" }},
      {v:400, q:"the sixth sense the unit's quiz is about", anagram:{ word:"intuition" }},
      {v:500, q:"a worry that keeps returning, said of a doubt", anagram:{ word:"nagging" }},
    ]},

    /* ================= 4B · have, get and memory ================= */
    /* Grammar 4B (p47 1d): six sentences, four uses. The uses are the book's own
       wording, which is what makes this a grammar question rather than a guess. */
    { id:'4b-connections', section:'4B', clues:[
      {v:100, q:"Four of these are memory collocations from the unit. Find the four.",
        group:{ pick:["vague","vivid","lasting","distant"],
                with:["rational","objective","uneasy","groundless"] }},
      {v:200, q:"Four of these describe a memory you can still feel. Find the four.",
        group:{ pick:["vivid","painful","lasting","photographic"],
                with:["vague","distant","faded","forgotten"] }},
      {v:300, q:"Four of these are things done TO you, not BY you. Find the four.",
        group:{ pick:["stolen","renovated","broken","punished"],
                with:["remembered","recalled","imagined","forgot"] }},
      {v:400, q:"Four of these are from the eyewitness text. Find the four.",
        group:{ pick:["fallible","susceptible","perpetrator","line-up"],
                with:["objective","impulse","whim","hunch"] }},
      {v:500, q:"Four of these are idioms about remembering. Find the four.",
        group:{ pick:["comes to mind","cast your mind back","slipped my mind","trigger a memory"],
                with:["weigh up","deep down","on a whim","beg to differ"] }},
    ]},
    { id:'4b-thermometer', section:'4B', clues:[
      {v:100, q:"Put these in order — faintest memory first.",
        order:{ scale:["forgotten","vague","distant","vivid","photographic"],
                low:"nothing is left", high:"perfect recall",
                gloss:{ forgotten:"gone entirely.",
                        vague:"the book's word for a memory that is unclear.",
                        distant:"it happened a long time ago.",
                        vivid:"with clear sensations — you can still feel it.",
                        photographic:"you can remember anything perfectly." } }},
      {v:200, q:"Put these in order — shortest-lived first.",
        order:{ scale:["fleeting","passing","distant","lasting","permanent"],
                low:"gone in a moment", high:"never leaves you",
                gloss:{ fleeting:"there and gone.",
                        passing:"it does not stay with you.",
                        distant:"old, and faded by time.",
                        lasting:"the book's word — it stays with you.",
                        permanent:"the definition the book gives for 'lasting'." } }},
      {v:300, q:"Put these in order — least involvement first.",
        order:{ scale:["witnessed","remembered","reconstructed","assumed","imagined"],
                low:"you actually saw it", high:"your mind made it",
                gloss:{ witnessed:"you were there and saw it happen.",
                        remembered:"you brought it back, more or less intact.",
                        reconstructed:"the text's word — you fused bits together.",
                        assumed:"you filled the gap with what must have happened.",
                        imagined:"none of it happened at all." } }},
      {v:400, q:"Put these in order — least reliable first.",
        order:{ scale:["fallible","susceptible","cautious","neutral","accurate"],
                low:"gets it wrong", high:"gets it right",
                gloss:{ fallible:"the text's word — capable of being wrong.",
                        susceptible:"open to influence from what you believe.",
                        cautious:"aware it might be wrong, and careful.",
                        neutral:"not leaning either way — how a line-up should be run.",
                        accurate:"matches what actually happened." } }},
      {v:500, q:"Put these in order — how a case unfolds, earliest first.",
        order:{ scale:["crime","witness","description","line-up","court"],
                low:"it happens", high:"the jury hears it",
                gloss:{ crime:"the event itself.",
                        witness:"someone who saw it.",
                        description:"what the police ask for first.",
                        'line-up':"the witness is invited to identify the perpetrator.",
                        court:"by now, time has elapsed." } }},
    ]},
    { id:'4b-choice', section:'4B', clues:[
      {v:100, q:"'My parents were having the kitchen renovated.' Which use is it?",
        choice:{ options:["they paid somebody to do a job","their possessions were harmed",
                          "they caused somebody to do something","they caused what happened to them"],
                 answer:"they paid somebody to do a job" }},
      {v:200, q:"'I had all my toys stolen.' Which use is it?",
        choice:{ options:["my possessions were harmed by somebody else","I paid somebody to do a job",
                          "I caused somebody to do something","I caused what happened to me"],
                 answer:"my possessions were harmed by somebody else" }},
      {v:300, q:"'He got himself locked in the garden shed.' Which use is it?",
        choice:{ options:["he caused what happened to him","he paid somebody to do a job",
                          "his possessions were harmed","he caused somebody to do something"],
                 answer:"he caused what happened to him" }},
      {v:400, q:"'His disappearance got everyone looking for him.' Which use is it?",
        choice:{ options:["it caused somebody to do something","it paid somebody to do a job",
                          "his possessions were harmed","he caused what happened to him"],
                 answer:"it caused somebody to do something" }},
      {v:500, q:"Which collocation means 'you can remember anything perfectly'?",
        choice:{ options:["a photographic memory","a lasting memory","a vivid memory","a distant memory"],
                 answer:"a photographic memory" }},
    ]},
    /* The book's own pronunciation sentences (p47 2a), put back out of order. */
    { id:'4b-scramble', section:'4B', clues:[
      {v:100, q:"Put the words in order — something was done to me.",
        scramble:{ sentence:"I had my bike stolen outside the station" }},
      {v:200, q:"Put the words in order — she caused me to do it.",
        scramble:{ sentence:"They had me doing all the cleaning for weeks" }},
      {v:300, q:"Put the words in order — I caused it to happen to me.",
        scramble:{ sentence:"I got myself locked out of the house again" }},
      {v:400, q:"Put the words in order — I persuaded her.",
        scramble:{ sentence:"I got my mum to say I was sick" }},
      {v:500, q:"Put the words in order — somebody else caused it.",
        scramble:{ sentence:"My brother got me punished quite unfairly" }},
    ]},
    { id:'4b-anagram', section:'4B', clues:[
      {v:100, q:"unclear — the book's word for a memory with no detail", anagram:{ word:"vague" }},
      {v:200, q:"with clear sensations, so you can still feel it", anagram:{ word:"vivid" }},
      {v:300, q:"the person who actually committed the crime", anagram:{ word:"perpetrator" }},
      {v:400, q:"capable of being wrong — said of eyewitness testimony", anagram:{ word:"fallible" }},
      {v:500, q:"someone who saw the crime happen", anagram:{ word:"eyewitness" }},
    ]},

    /* ================= 4C · tact, idioms and homophones ================= */
    /* Useful Language 4C (p50 2a): seven expressions, three uses, all the book's. */
    { id:'4c-connections', section:'4C', clues:[
      {v:100, q:"Four of these soften a disagreement. Find the four.",
        group:{ pick:["differ","respect","offence","personally"],
                with:["stolen","renovated","punished","locked"] }},
      {v:200, q:"Four of these are homophone pairs the book corrects. Find the four.",
        group:{ pick:["due","way","fair","pair"],
                with:["dew","weigh","fare","pear"] }},
      {v:300, q:"Four of these express agreement. Find the four.",
        group:{ pick:["exactly","precisely","absolutely","quite"],
                with:["however","nevertheless","conversely","whereas"] }},
      {v:400, q:"Four of these are ways of being critical. Find the four.",
        group:{ pick:["heavy-handed","blunt","tactless","harsh"],
                with:["tactful","diplomatic","constructive","considerate"] }},
      {v:500, q:"Four of these begin a tactful disagreement. Find the four.",
        group:{ pick:["Well","Look","Actually","Honestly"],
                with:["Subsequently","Gradually","Shortly","Immediately"] }},
    ]},
    { id:'4c-thermometer', section:'4C', clues:[
      {v:100, q:"Put these in order — most tactful first.",
        order:{ scale:["I see where you're coming from","I do take your point","I beg to differ",
                       "That's not the way I see it","With all due respect"],
                low:"gentlest disagreement", high:"bluntest disagreement",
                gloss:{ "I see where you're coming from":"you accept their view before you differ.",
                        'I do take your point':"you concede something first.",
                        'I beg to differ':"formal, and openly a disagreement.",
                        "That's not the way I see it":"you are contradicting them directly.",
                        'With all due respect':"the politest words, and everyone hears the criticism coming." } }},
      {v:200, q:"Put these in order — least direct criticism first.",
        order:{ scale:["constructive","tactful","frank","blunt","heavy-handed"],
                low:"meant to help", high:"the book's word for too much force",
                gloss:{ constructive:"what Nadia says she is trying to be.",
                        tactful:"you soften it so it can be heard.",
                        frank:"honest, and not softened.",
                        blunt:"no softening at all.",
                        'heavy-handed':"the criticism lands harder than it needed to." } }},
      {v:300, q:"Put these in order — least forthcoming first.",
        order:{ scale:["silent","guarded","reserved","open","forthcoming"],
                low:"like getting blood out of a stone", high:"tells you everything",
                gloss:{ silent:"says nothing at all.",
                        guarded:"answers, but gives nothing away.",
                        reserved:"holds back by nature.",
                        open:"willing to say what they think.",
                        forthcoming:"the book's word — offers it before you ask." } }},
      {v:400, q:"Put these in order — weakest agreement first.",
        order:{ scale:["I suppose so","Fair enough","Exactly","Tell me about it","You've hit the nail on the head"],
                low:"grudging", high:"complete agreement",
                gloss:{ 'I suppose so':"you are not really convinced.",
                        'Fair enough':"you accept the point.",
                        Exactly:"you agree fully.",
                        'Tell me about it':"the idiom — you agree from experience.",
                        "You've hit the nail on the head":"they have said it precisely right." } }},
      {v:500, q:"Put these in order — softest opening first.",
        order:{ scale:["No offence intended","Don't take this personally","If you don't mind me saying so",
                       "I'm afraid I have to say","With all due respect"],
                low:"barely a warning", high:"brace yourself",
                gloss:{ 'No offence intended':"you say in advance that none is meant.",
                        "Don't take this personally":"the criticism is of the work, not them.",
                        "If you don't mind me saying so":"you ask permission first.",
                        "I'm afraid I have to say":"you present it as something you must say.",
                        'With all due respect':"the strongest warning of all." } }},
    ]},
    { id:'4c-choice', section:'4C', clues:[
      {v:100, q:"Which expression softens a strong or unpopular opinion?",
        choice:{ options:["I'm afraid I have to say","I beg to differ",
                          "I see where you're coming from","Tell me about it"],
                 answer:"I'm afraid I have to say" }},
      {v:200, q:"Correct the homophone: 'with all dew respect'.",
        choice:{ options:["due","do","due to","doe"], answer:"due" }},
      {v:300, q:"Correct the homophones: 'I can still see the hole seen'.",
        choice:{ options:["the whole scene","the hole scene","the whole seen","the hol scene"],
                 answer:"the whole scene" }},
      {v:400, q:"Correct the homophones: 'eyewitness testimony carries grate wait'.",
        choice:{ options:["great weight","grate weight","great wait","greate weight"],
                 answer:"great weight" }},
      {v:500, q:"Complete the idiom: 'You've ___ the nail on the head!'",
        choice:{ options:["hit","struck","banged","knocked"], answer:"hit" }},
    ]},
    { id:'4c-scramble', section:'4C', clues:[
      {v:100, q:"Put the words in order — asking permission to criticise.",
        scramble:{ sentence:"Well if you don't mind me saying so" }},
      {v:200, q:"Put the words in order — accepting their view, then differing.",
        scramble:{ sentence:"I see where you are coming from but" }},
      {v:300, q:"Put the words in order — softening the criticism.",
        scramble:{ sentence:"Look don't take this personally I'm being constructive" }},
      {v:400, q:"Put the words in order — saying no offence is meant.",
        scramble:{ sentence:"I mean that in the nicest possible way" }},
      {v:500, q:"Put the words in order — the politest warning there is.",
        scramble:{ sentence:"With all due respect I don't think so" }},
    ]},
    { id:'4c-anagram', section:'4C', clues:[
      {v:100, q:"the skill of saying a hard thing without wounding", anagram:{ word:"tact" }},
      {v:200, q:"willing to say what you think without being asked", anagram:{ word:"forthcoming" }},
      {v:300, q:"criticism meant to help rather than to wound", anagram:{ word:"constructive" }},
      {v:400, q:"two words that sound the same but are spelt differently", anagram:{ word:"homophone" }},
      {v:500, q:"upset caused by something that was said", anagram:{ word:"offence" }},
    ]},

    /* ================= 4D · profile writing and time expressions ================= */
    /* Writing 4D (p53 3e/3f): the book sorts its time expressions into three
       groups — immediately, after a short time, some time later — which is
       exactly a scale, and it is the book's own. */
    { id:'4d-connections', section:'4D', clues:[
      {v:100, q:"Four of these mean 'immediately'. Find the four.",
        group:{ pick:["the moment","the instant","no sooner","as soon as"],
                with:["subsequently","gradually","in time","before long"] }},
      {v:200, q:"Four of these mean 'some time later'. Find the four.",
        group:{ pick:["subsequently","gradually","in time","eventually"],
                with:["the moment","the instant","immediately","instantly"] }},
      {v:300, q:"Four of these are from the profile article. Find the four.",
        group:{ pick:["breakthrough","trademark","sensation","outsider"],
                with:["perpetrator","line-up","testimony","eyewitness"] }},
      {v:400, q:"Four of these open a sentence by inverting it. Find the four.",
        group:{ pick:["No sooner","Not until","Only when","Never before"],
                with:["Gradually","Subsequently","Shortly","Before"] }},
      {v:500, q:"Four of these are parts of a profile article. Find the four.",
        group:{ pick:["quotes","background","achievements","plans"],
                with:["verdict","testimony","line-up","sentence"] }},
    ]},
    { id:'4d-thermometer', section:'4D', clues:[
      {v:100, q:"Put these in order — soonest first.",
        order:{ scale:["the instant","shortly afterwards","before long","subsequently","gradually"],
                low:"immediately", high:"over a long stretch of time",
                gloss:{ 'the instant':"the book files this under 'immediately'.",
                        'shortly afterwards':"after a short time.",
                        'before long':"also after a short time, but vaguer.",
                        subsequently:"some time later — and formal.",
                        gradually:"over a period, not at one moment." } }},
      {v:200, q:"Put these in order — earliest in her story first.",
        order:{ scale:["outsider","breakthrough","sensation","waning","forgotten"],
                low:"nobody knows her", high:"nobody remembers her",
                gloss:{ outsider:"how Noni-K says she felt as a teenager.",
                        breakthrough:"the moment it changes.",
                        sensation:"the article's word once the album lands.",
                        waning:"popularity beginning to fade — the article says hers is not.",
                        forgotten:"the end of the arc, which is not hers." } }},
      {v:300, q:"Put these in order — most formal last.",
        order:{ scale:["then","after that","later","afterwards","subsequently"],
                low:"how you would say it", high:"how the article writes it",
                gloss:{ then:"speech, and the plainest of the five.",
                        'after that':"still spoken English.",
                        later:"neutral — fine anywhere.",
                        afterwards:"leaning formal.",
                        subsequently:"the article's own word." } }},
      {v:400, q:"Put these in order — shortest span first.",
        order:{ scale:["the moment","immediately","before long","in time","eventually"],
                low:"no gap at all", high:"after everything else",
                gloss:{ 'the moment':"at the very instant it happened.",
                        immediately:"with no delay.",
                        'before long':"soon, but not at once.",
                        'in time':"after a while has passed.",
                        eventually:"in the end, after a long wait." } }},
      {v:500, q:"Put these in order — the order a profile article puts them in.",
        order:{ scale:["hook","background","breakthrough","achievements","plans"],
                low:"the opening line", high:"the closing line",
                gloss:{ hook:"the most interesting part, used to begin.",
                        background:"where she came from and how it started.",
                        breakthrough:"the moment everything changed.",
                        achievements:"what she has done since.",
                        plans:"what comes next — where a profile ends." } }},
    ]},
    { id:'4d-choice', section:'4D', clues:[
      {v:100, q:"'___ had I started singing than I realised what I wanted.'",
        choice:{ options:["No sooner","Not until","The instant","Before long"], answer:"No sooner" }},
      {v:200, q:"'___ many years later did she become famous.'",
        choice:{ options:["Not until","No sooner","The moment","Subsequently"], answer:"Not until" }},
      {v:300, q:"Which one means 'immediately'?",
        choice:{ options:["the instant","in time","before long","subsequently"], answer:"the instant" }},
      {v:400, q:"'They moved first to Bristol and ___ to London.'",
        choice:{ options:["subsequently","the instant","no sooner","gradually"], answer:"subsequently" }},
      {v:500, q:"What is unusual about 'Not until many years later did she become famous'?",
        choice:{ options:["the subject and verb are inverted","it has no main verb",
                          "the tense is wrong","it is a question"],
                 answer:"the subject and verb are inverted" }},
    ]},
    { id:'4d-scramble', section:'4D', clues:[
      {v:100, q:"Put the words in order — some time later.",
        scramble:{ sentence:"They moved first to Bristol and subsequently to London" }},
      {v:200, q:"Put the words in order — after a short time.",
        scramble:{ sentence:"Before long she was creating songs in a new style" }},
      {v:300, q:"Put the words in order — the inversion after 'not until'.",
        scramble:{ sentence:"Not until many years later did she become famous" }},
      {v:400, q:"Put the words in order — at the very moment.",
        scramble:{ sentence:"The instant I heard her music I knew" }},
      {v:500, q:"Put the words in order — the article's closing idea.",
        scramble:{ sentence:"Her popularity shows no sign of waning any time soon" }},
    ]},
    { id:'4d-anagram', section:'4D', clues:[
      {v:100, q:"the moment everything changed for her", anagram:{ word:"breakthrough" }},
      {v:200, q:"some time later — the article's formal word", anagram:{ word:"subsequently" }},
      {v:300, q:"slowly, over a period rather than at one moment", anagram:{ word:"gradually" }},
      {v:400, q:"the clothes she always wears, so people know her by them", anagram:{ word:"trademark" }},
      {v:500, q:"someone who never quite belongs to the group", anagram:{ word:"outsider" }},
    ]},

    /* ================= 4E · Connections 4×4 — sort the whole field =================
       The `connections` round (sixteen words, four hidden groups of four), built
       from the vocabulary 4A–4D already teach so the puzzle is revision, not new
       words. Each group sits in the same field as its neighbours — that is the
       trap: `considered` weighs a decision, `considerate` spares someone's feelings;
       `the instant` is immediate, `subsequently` is later. Naming the group is the
       payoff. Its own section so the four themed columns above keep their length; a
       teacher who wants the flick/tap physics picks it here. */
    { id:'4e-connections', section:'4E', clues:[
      {v:100, q:"The mind at work — sort the sixteen into four groups of four.",
        connections:{ groups:[
          { label:"Trusting your gut",          words:["gut","hunch","instinct","intuition"] },
          { label:"Acting on a sudden urge",    words:["whim","impulse","snap","spur"] },
          { label:"Thinking it through",        words:["rational","objective","considered","deliberate"] },
          { label:"A doubt with nothing behind it", words:["nagging","groundless","uneasy","lingering"] } ] }},
      {v:200, q:"Memory and evidence — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"A memory you can still feel", words:["vivid","painful","lasting","photographic"] },
          { label:"A memory that has faded",     words:["vague","distant","faded","dim"] },
          { label:"From the eyewitness account", words:["witness","perpetrator","testimony","line-up"] },
          { label:"Something you had done",       words:["stolen","broken","renovated","fixed"] } ] }},
      {v:300, q:"How it comes across — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Handling it with tact",   words:["tactful","diplomatic","considerate","sensitive"] },
          { label:"Saying it too bluntly",   words:["blunt","harsh","tactless","abrupt"] },
          { label:"Giving nothing away",     words:["guarded","reserved","reticent","withdrawn"] },
          { label:"Words that mark a contrast", words:["however","although","whereas","nevertheless"] } ] }},
      {v:400, q:"When things happen — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"Straight away",             words:["the moment","the instant","immediately","instantly"] },
          { label:"Some time later",           words:["subsequently","gradually","eventually","before long"] },
          { label:"These invert what follows", words:["no sooner","not until","only when","never before"] },
          { label:"Parts of a profile article", words:["background","achievements","quotes","plans"] } ] }},
      {v:500, q:"Corners of the whole unit — sort the sixteen into four groups.",
        connections:{ groups:[
          { label:"The five senses",              words:["sight","hearing","touch","smell"] },
          { label:"Ways of agreeing",             words:["exactly","precisely","absolutely","quite"] },
          { label:"The correctly-spelled homophone", words:["whole","scene","weight","bear"] },
          { label:"Words from the profile article", words:["breakthrough","trademark","sensation","outsider"] } ] }},
    ]},
  ],

  /* What a teacher can tick in Race, Blockbusters and Millionaire. Each section
     splits into the two strands the coursebook itself uses — the vocabulary and
     the grammar/skill focus — so "just the relative clauses" is now selectable.
     Counts are computed from the banks at render time, never written here. */
  topicNames: {
    '4A-grammar': '4A · Noun phrases',
    '4A-vocab': '4A · Instinct & reason',
    '4B-grammar': '4B · have / get something done',
    '4B-vocab': '4B · Memory & eyewitnesses',
    '4C-grammar': '4C · Idioms & homophones',
    '4C-vocab': '4C · Being tactful',
    '4D-grammar': '4D · Time expressions',
    '4D-vocab': '4D · Profile writing',
  },

  /* ---- Bingo calls ----------------------------------------------------------
     These were the Blockbusters bank until that board went all-rounds. A bingo
     call is a clue with one single-word answer, which is exactly what a round
     hexagon is not, so the two could not stay one list. See the note on
     `bingoBank` in unit-5.js. */
  bingoBank: [
    {section:'4A', topic:'4A-vocab', type:'anagram', letter:'I', clue:"Unscramble: acting suddenly, without planning it.", answer:"Impulse"},
    {section:'4B', topic:'4B-vocab', type:'anagram', letter:'W', clue:"Unscramble: someone who saw it happen.", answer:"Witness"},
    {section:'4C', topic:'4C-vocab', type:'anagram', letter:'T', clue:"Unscramble: skill in not causing offence.", answer:"Tact"},
    {section:'4D', topic:'4D-vocab', type:'anagram', letter:'M', clue:"Unscramble: the point at which everything changed.", answer:"Moment"},
    {section:'4A', topic:'4A-vocab', type:'oddoneout', letter:'K', clue:"Which does NOT belong: hunch / instinct / kettle", answer:"Kettle"},
    {section:'4B', topic:'4B-vocab', type:'oddoneout', letter:'H', clue:"Which does NOT belong: recall / memory / hedge", answer:"Hedge"},
    {section:'4C', topic:'4C-vocab', type:'oddoneout', letter:'S', clue:"Which does NOT belong: tactful / diplomatic / sarcastic", answer:"Sarcastic"},
    {section:'4D', topic:'4D-vocab', type:'oddoneout', letter:'C', clue:"Which does NOT belong: eventually / meanwhile / cautious", answer:"Cautious"},
    {section:'4A', topic:'4A-vocab', letter:'R', clue:"The opposite of emotional — deciding with your head, not your heart.", answer:"Rational"},
    {section:'4A', topic:'4A-vocab', letter:'I', clue:"Doing something suddenly, without planning it — 'on ___'.", answer:"Impulse"},
    {section:'4A', topic:'4A-vocab', letter:'S', clue:"'We ___ pick up on tiny changes in someone's face' — below conscious awareness.", answer:"Subconsciously"},
    {section:'4A', topic:'4A-vocab', letter:'W', clue:"To ___ up the options is to consider the pros and cons before deciding.", answer:"Weigh"},
    {section:'4A', topic:'4A-vocab', letter:'O', clue:"Based on facts, not feelings — the opposite of subjective.", answer:"Objective"},
    {section:'4A', topic:'4A-vocab', letter:'D', clue:"An expression meaning 'in your heart, even if you won't admit it' — '___ down'.", answer:"Deep"},
    {section:'4A', topic:'4A-vocab', letter:'G', clue:"Informal word for instinct — trust your ___.", answer:"Gut"},
    {section:'4A', topic:'4A-vocab', letter:'H', clue:"A strong feeling that something is true, without proof.", answer:"Hunch"},
    {section:'4B', topic:'4B-vocab', letter:'V', clue:"A memory that's unclear or hazy is a ___ one.", answer:"Vague"},
    {section:'4B', topic:'4B-vocab', letter:'P', clue:"A memory that makes you unhappy to recall is a ___ one.", answer:"Painful"},
    {section:'4B', topic:'4B-vocab', letter:'L', clue:"A memory that stays with you permanently is a ___ one.", answer:"Lasting"},
    {section:'4B', topic:'4B-vocab', letter:'F', clue:"Capable of making mistakes — used to describe eyewitness testimony.", answer:"Fallible"},
    {section:'4B', topic:'4B-vocab', letter:'E', clue:"Someone who saw a crime happen.", answer:"Eyewitness"},
    {section:'4B', topic:'4B-vocab', letter:'M', clue:"Easily shaped or changed — used to describe how flexible our memories are.", answer:"Malleable"},
    {section:'4B', topic:'4B-vocab', letter:'G', clue:"The direction someone is looking — an officer's ___ might influence a witness.", answer:"Gaze"},
    {section:'4B', topic:'4B-vocab', letter:'E', clue:"To add invented details to a story, making it more dramatic.", answer:"Embellish"},
    {section:'4C', topic:'4C-grammar', letter:'N', clue:"Idiom: to say exactly the right thing — hit the ___ on the head.", answer:"Nail"},
    {section:'4C', topic:'4C-vocab', letter:'D', clue:"'I beg to ___' — a tactful way of disagreeing.", answer:"Differ"},
    {section:'4C', topic:'4C-vocab', letter:'R', clue:"'With all due ___' — softening a criticism politely.", answer:"Respect"},
    {section:'4C', topic:'4C-vocab', letter:'U', clue:"Feeling worried or not quite comfortable about something.", answer:"Uneasy"},
    {section:'4C', topic:'4C-vocab', letter:'N', clue:"An adjective for a nagging feeling that won't go away.", answer:"Nagging"},
    {section:'4C', topic:'4C-vocab', letter:'F', clue:"Someone 'not particularly ___' isn't very willing to share information.", answer:"Forthcoming"},
    {section:'4D', topic:'4D-grammar', letter:'S', clue:"A time expression meaning 'without delay, right after' — '___ afterwards'.", answer:"Shortly"},
    {section:'4D', topic:'4D-grammar', letter:'I', clue:"A time expression meaning 'right away'.", answer:"Immediately"},
    {section:'4D', topic:'4D-grammar', letter:'G', clue:"A time expression meaning 'slowly, over time'.", answer:"Gradually"},
    {section:'4D', topic:'4D-vocab', letter:'B', clue:"A word for sudden success — also the title of Noni-K's debut album.", answer:"Breakout"},
    {section:'4A', topic:'4A-vocab', letter:'I', clue:"An adjective for a feeling you can't explain or account for.", answer:"Inexplicable"},
    {section:'4A', topic:'4A-vocab', letter:'I', clue:"An ___ urge is one you simply cannot resist.", answer:"Irresistible"},
    {section:'4A', topic:'4A-vocab', letter:'C', clue:"The part of the brain the article calls logical and coherent — the ___ left brain.", answer:"Conscious"},
    {section:'4A', topic:'4A-vocab', letter:'P', clue:"Clammy ___ are one physical sign that intuition is at work.", answer:"Palms"},
    {section:'4A', topic:'4A-vocab', letter:'S', clue:"The '___ sense' — a supposed extra sense beyond the usual five.", answer:"Sixth"},
    {section:'4A', topic:'4A-vocab', letter:'C', clue:"Two events happening together by chance.", answer:"Coincidence"},
    {section:'4A', topic:'4A-vocab', letter:'I', clue:"The formal noun for gut feeling or instinctive knowing.", answer:"Intuition"},
    {section:'4A', topic:'4A-vocab', letter:'H', clue:"Each half of the brain is called a ___.", answer:"Hemisphere"},
    {section:'4B', topic:'4B-vocab', letter:'S', clue:"Your brother or sister.", answer:"Sibling"},
    {section:'4B', topic:'4B-vocab', letter:'P', clue:"The person who committed the crime.", answer:"Perpetrator"},
    {section:'4B', topic:'4B-vocab', letter:'T', clue:"The formal word for evidence a witness gives in court.", answer:"Testimony"},
    {section:'4B', topic:'4B-vocab', letter:'S', clue:"Easily influenced — our memories are ___ to suggestion.", answer:"Susceptible"},
    {section:'4B', topic:'4B-vocab', letter:'R', clue:"'Bear little ___ to' means to be very unlike something.", answer:"Resemblance"},
    {section:'4B', topic:'4B-vocab', letter:'T', clue:"Humankind ___ on stories, according to the reading.", answer:"Thrives"},
    {section:'4B', topic:'4B-vocab', letter:'D', clue:"The person accused of a crime in court.", answer:"Defendant"},
    {section:'4B', topic:'4B-vocab', letter:'J', clue:"The group of people who decide a verdict in court.", answer:"Jury"},
    {section:'4B', topic:'4B-grammar', letter:'H', clue:"The verb in 'They ___ their roof fixed' — paying someone else to do a job.", answer:"Had"},
    {section:'4B', topic:'4B-grammar', letter:'G', clue:"The verb in 'We ___ our car broken into' — something bad happened to our property.", answer:"Got"},
    {section:'4B', topic:'4B-grammar', letter:'C', clue:"'He got himself locked in the shed' — he ___ what happened to him.", answer:"Caused"},
    {section:'4B', topic:'4B-grammar', letter:'S', clue:"In 'I had my bike stolen', which grammatical role does 'I' play — subject or object?", answer:"Subject"},
    {section:'4B', topic:'4B-grammar', letter:'H', clue:"Fill the gap: 'She ___ me doing all her homework.'", answer:"Had"},
    {section:'4B', topic:'4B-grammar', letter:'P', clue:"In 'My brother got me punished unfairly', what is the past participle?", answer:"Punished"},
    {section:'4B', topic:'4B-grammar', letter:'R', clue:"'My parents were having the kitchen ___' — someone else did the work.", answer:"Renovated"},
    {section:'4B', topic:'4B-vocab', letter:'T', clue:"In 'I got my mum to say I was sick', which one-word particle comes before 'say'?", answer:"To"},
    {section:'4C', topic:'4C-vocab', letter:'T', clue:"The skill of saying difficult things without causing offence.", answer:"Tact"},
    {section:'4C', topic:'4C-vocab', letter:'O', clue:"'No ___ intended' — said before a potentially rude remark.", answer:"Offence"},
    {section:'4C', topic:'4C-vocab', letter:'P', clue:"'I do take your ___, but…' — acknowledging before disagreeing.", answer:"Point"},
    {section:'4C', topic:'4C-grammar', letter:'B', clue:"Idiom: getting information from an unwilling person is like getting ___ out of a stone.", answer:"Blood"},
    {section:'4C', topic:'4C-vocab', letter:'H', clue:"Being too forceful or harsh in your approach — '___-handed'.", answer:"Heavy"},
    {section:'4C', topic:'4C-vocab', letter:'H', clue:"Two words that sound the same but are spelled differently.", answer:"Homophones"},
    {section:'4C', topic:'4C-vocab', letter:'C', clue:"Criticism meant to help rather than attack is ___.", answer:"Constructive"},
    {section:'4C', topic:'4C-vocab', letter:'P', clue:"Behaving in a professional way — Nadia values ___ in interviews.", answer:"Professionalism"},
    {section:'4D', topic:'4D-vocab', letter:'P', clue:"An article describing a person's life and career.", answer:"Profile"},
    {section:'4D', topic:'4D-vocab', letter:'Q', clue:"Someone's exact words, reproduced in an article.", answer:"Quote"},
    {section:'4D', topic:'4D-grammar', letter:'S', clue:"A time expression meaning 'afterwards, following that'.", answer:"Subsequently"},
    {section:'4D', topic:'4D-grammar', letter:'I', clue:"'The ___ I heard her music, I knew' — a time expression meaning 'the moment'.", answer:"Instant"},
    {section:'4D', topic:'4D-grammar', letter:'B', clue:"'___ long, she was creating songs' — a time expression meaning 'soon after'.", answer:"Before"},
    {section:'4D', topic:'4D-vocab', letter:'W', clue:"'It ___ until she was 17 that she felt confident' — the emphatic time structure.", answer:"Wasn't"},
    {section:'4D', topic:'4D-vocab', letter:'S', clue:"The place and surroundings an interview happens in.", answer:"Setting"},
    {section:'4D', topic:'4D-vocab', letter:'A', clue:"Things a person has accomplished — one thing to ask about in an interview.", answer:"Achievements"},
  ],

  /* Every hexagon is a **round**, and every question here is a *different*
     question from the Jeopardy column on the same language — the per-game rule,
     which the content gate enforces. The letter is the hexagon's name, not a
     constraint on the answer. Eighteen per section, because eighteen is the
     board. */
  blockbustersBank: [
    /* ---- 4A: instinct, reason and doubt ---- */
    {section:'4A', topic:'4A-vocab', letter:'G', clue:"Four of these are the book's words for intuition. Find the four.",
      group:{ pick:["gut","hunch","instinct","intuition"], with:["logic","evidence","analysis","reasoning"] }},
    {section:'4A', topic:'4A-vocab', letter:'W', clue:"Four of these describe a decision nobody thought about. Find the four.",
      group:{ pick:["whim","impulse","snap","spur"], with:["measured","weighed","reasoned","planned"] }},
    {section:'4A', topic:'4A-vocab', letter:'U', clue:"Four of these go with the word 'doubt'. Find the four.",
      group:{ pick:["nagging","lingering","serious","reasonable"], with:["vivid","distant","photographic","lasting"] }},
    {section:'4A', topic:'4A-vocab', letter:'B', clue:"Four of these are body words in gut-feeling idioms. Find the four.",
      group:{ pick:["gut","bones","head","heart"], with:["pattern","doubt","whim","impulse"] }},
    {section:'4A', topic:'4A-vocab', letter:'C', clue:"Four of these mean you took your feelings out of it. Find the four.",
      group:{ pick:["objective","detached","impartial","neutral"], with:["instinctive","impulsive","emotional","subjective"] }},
    {section:'4A', topic:'4A-vocab', letter:'S', clue:"Put these in order — least certain first.",
      order:{ scale:["hunch","feeling","impression","conviction","certainty"],
              low:"barely anything", high:"you have no doubt",
              gloss:{ hunch:"a guess you cannot explain.",
                      feeling:"the book's word in 'an uneasy feeling'.",
                      impression:"what you took away from it.",
                      conviction:"you are firmly persuaded.",
                      certainty:"no room left for doubt." } }},
    {section:'4A', topic:'4A-vocab', letter:'T', clue:"Put these in order — quickest decision first.",
      order:{ scale:["snap","impulsive","instinctive","considered","calculated"],
              low:"no time at all", high:"worked out in advance",
              gloss:{ snap:"made in a second.",
                      impulsive:"the book's 'on impulse' — sudden and unplanned.",
                      instinctive:"you followed your gut.",
                      considered:"you thought about it first.",
                      calculated:"you worked it out deliberately." } }},
    {section:'4A', topic:'4A-vocab', letter:'A', clue:"Put these in order — mildest first.",
      order:{ scale:["unbothered","uneasy","anxious","alarmed","terrified"],
              low:"perfectly comfortable", high:"cannot function",
              gloss:{ unbothered:"nothing registers as wrong.",
                      uneasy:"the book's word — something is not quite right.",
                      anxious:"worry you cannot put down.",
                      alarmed:"you now believe there is a real problem.",
                      terrified:"fear has taken over completely." } }},
    {section:'4A', topic:'4A-grammar', letter:'N', clue:"'On impulse' and 'on a ___' mean the same thing.",
      choice:{ options:["whim","hunch","gut","doubt"], answer:"whim" }},
    {section:'4A', topic:'4A-vocab', letter:'D', clue:"'I knew ___ that it was a mistake' — the book's phrase for subconsciously.",
      choice:{ options:["deep down","on a whim","weighing up","objectively"], answer:"deep down" }},
    {section:'4A', topic:'4A-vocab', letter:'E', clue:"Which one is NOT about intuition?",
      choice:{ options:["objective","gut","hunch","sixth sense"], answer:"objective" }},
    {section:'4A', topic:'4A-vocab', letter:'F', clue:"'Something that just doesn't quite ___ together.'",
      choice:{ options:["fit","sit","go","come"], answer:"fit" }},
    {section:'4A', topic:'4A-vocab', letter:'X', clue:"Put the words in order — worries with no basis.",
      scramble:{ sentence:"These are groundless anxieties that many of us have" }},
    {section:'4A', topic:'4A-vocab', letter:'Y', clue:"Put the words in order — knowing without being able to say why.",
      scramble:{ sentence:"Deep down I knew I was making a mistake" }},
    {section:'4A', topic:'4A-vocab', letter:'I', clue:"the sixth sense the unit's opening quiz is about", anagram:{ word:"instinct" }},
    {section:'4A', topic:'4A-vocab', letter:'O', clue:"to put the advantages against the disadvantages", anagram:{ word:"consider" }},
    {section:'4A', topic:'4A-vocab', letter:'P', clue:"the regular shape a thing normally follows", anagram:{ word:"pattern" }},
    {section:'4A', topic:'4A-vocab', letter:'H', clue:"a feeling you cannot back up with anything", anagram:{ word:"hunch" }},

    /* ---- 4B: have, get and memory ---- */
    {section:'4B', topic:'4B-vocab', letter:'M', clue:"Four of these describe a memory that has faded. Find the four.",
      group:{ pick:["vague","distant","faded","dim"], with:["vivid","photographic","lasting","sharp"] }},
    {section:'4B', topic:'4B-vocab', letter:'R', clue:"Four of these are what a witness does. Find the four.",
      group:{ pick:["identify","describe","recall","testify"], with:["renovate","punish","steal","lock"] }},
    {section:'4B', topic:'4B-grammar', letter:'H', clue:"Four of these can follow 'I had my …'. Find the four.",
      group:{ pick:["bike stolen","arm broken","hair cut","roof fixed"],
              with:["mind made","gut told","whim followed","doubt nagged"] }},
    {section:'4B', topic:'4B-vocab', letter:'T', clue:"Four of these come from the eyewitness text. Find the four.",
      group:{ pick:["trauma","shock","gaze","line-up"], with:["whim","impulse","pattern","bones"] }},
    {section:'4B', topic:'4B-vocab', letter:'K', clue:"Four of these mean you forgot. Find the four.",
      group:{ pick:["slipped","escaped","blank","lost"], with:["treasured","triggered","recalled","retained"] }},
    {section:'4B', topic:'4B-vocab', letter:'V', clue:"Put these in order — least detail first.",
      order:{ scale:["blank","dim","vague","clear","vivid"],
              low:"nothing at all", high:"you can still feel it",
              gloss:{ blank:"nothing comes at all.",
                      dim:"you know something is there.",
                      vague:"the outline, and no more.",
                      clear:"you could describe it.",
                      vivid:"with clear sensations, as the book defines it." } }},
    {section:'4B', topic:'4B-vocab', letter:'L', clue:"Put these in order — shortest ago first.",
      order:{ scale:["just now","earlier","recently","long ago","distant"],
              low:"a moment back", high:"a lifetime back",
              gloss:{ 'just now':"seconds.",
                      earlier:"today.",
                      recently:"in the last while.",
                      'long ago':"years back.",
                      distant:"the book's word — it happened a long time ago." } }},
    {section:'4B', topic:'4B-vocab', letter:'W', clue:"Put these in order — least sure of what you saw first.",
      order:{ scale:["guessing","assuming","recalling","recognising","certain"],
              low:"you are filling gaps", high:"you know it was them",
              gloss:{ guessing:"you have nothing to go on.",
                      assuming:"the text's word — you decide it must be so.",
                      recalling:"you are bringing back what you saw.",
                      recognising:"you can pick them out.",
                      certain:"you would swear to it in court." } }},
    {section:'4B', topic:'4B-grammar', letter:'C', clue:"'They had me doing all the cleaning.' Which use?",
      choice:{ options:["they caused somebody to do something","they paid somebody to do a job",
                        "their possessions were harmed","they caused what happened to them"],
               answer:"they caused somebody to do something" }},
    {section:'4B', topic:'4B-grammar', letter:'B', clue:"'I had my arm broken in a match.' Which use?",
      choice:{ options:["it happened to me, not by me","I paid somebody to do a job",
                        "I caused somebody to do something","I did it deliberately"],
               answer:"it happened to me, not by me" }},
    {section:'4B', topic:'4B-vocab', letter:'D', clue:"Which collocation means 'it happened a long time ago'?",
      choice:{ options:["a distant memory","a lasting memory","a painful memory","a vivid memory"],
               answer:"a distant memory" }},
    {section:'4B', topic:'4B-vocab', letter:'P', clue:"Which collocation means 'permanent'?",
      choice:{ options:["a lasting memory","a distant memory","a vague memory","a painful memory"],
               answer:"a lasting memory" }},
    {section:'4B', topic:'4B-grammar', letter:'X', clue:"Put the words in order — the homework was not hers.",
      scramble:{ sentence:"She had me doing all her homework every evening" }},
    {section:'4B', topic:'4B-grammar', letter:'Y', clue:"Put the words in order — it caused me to think.",
      scramble:{ sentence:"It got me thinking about what I had done wrong" }},
    {section:'4B', topic:'4B-vocab', letter:'S', clue:"open to influence from what you already believe", anagram:{ word:"susceptible" }},
    {section:'4B', topic:'4B-vocab', letter:'G', clue:"a long steady look, which can give a suspect away", anagram:{ word:"gaze" }},
    {section:'4B', topic:'4B-vocab', letter:'A', clue:"a shock so severe it damages how you remember", anagram:{ word:"trauma" }},
    {section:'4B', topic:'4B-vocab', letter:'N', clue:"a memory that still makes you unhappy", anagram:{ word:"painful" }},

    /* ---- 4C: tact, idioms and homophones ---- */
    {section:'4C', topic:'4C-vocab', letter:'T', clue:"Four of these are ways of being diplomatic. Find the four.",
      group:{ pick:["tactful","diplomatic","considerate","sensitive"], with:["blunt","harsh","tactless","abrupt"] }},
    {section:'4C', topic:'4C-grammar', letter:'W', clue:"Four of these are the correct homophones. Find the four.",
      group:{ pick:["whole","scene","weight","bear"], with:["hole","seen","wait","bare"] }},
    {section:'4C', topic:'4C-vocab', letter:'O', clue:"Four of these introduce a disagreement. Find the four.",
      group:{ pick:["however","although","whereas","nevertheless"], with:["exactly","precisely","absolutely","indeed"] }},
    {section:'4C', topic:'4C-vocab', letter:'B', clue:"Four of these mean somebody will not open up. Find the four.",
      group:{ pick:["guarded","reserved","reticent","withdrawn"], with:["forthcoming","open","frank","candid"] }},
    {section:'4C', topic:'4C-grammar', letter:'I', clue:"Four of these are idioms that express agreement. Find the four.",
      group:{ pick:["exactly","absolutely","precisely","quite"], with:["hardly","scarcely","barely","rarely"] }},
    {section:'4C', topic:'4C-vocab', letter:'S', clue:"Put these in order — gentlest first.",
      order:{ scale:["hint","suggest","point out","criticise","attack"],
              low:"they may not notice", high:"nobody could miss it",
              gloss:{ hint:"you barely say it at all.",
                      suggest:"you put it as a possibility.",
                      'point out':"you name the problem.",
                      criticise:"you say plainly it was wrong.",
                      attack:"the person, not just the work." } }},
    {section:'4C', topic:'4C-vocab', letter:'F', clue:"Put these in order — most willing to talk first.",
      order:{ scale:["forthcoming","open","reserved","guarded","silent"],
              low:"tells you everything", high:"like getting blood out of a stone",
              gloss:{ forthcoming:"the book's word — offers it before you ask.",
                      open:"answers honestly when asked.",
                      reserved:"holds back by nature.",
                      guarded:"answers, but gives nothing away.",
                      silent:"says nothing at all." } }},
    {section:'4C', topic:'4C-vocab', letter:'H', clue:"Put these in order — softest criticism first.",
      order:{ scale:["gentle","tactful","frank","blunt","brutal"],
              low:"barely felt", high:"leaves a mark",
              gloss:{ gentle:"said kindly, and easy to hear.",
                      tactful:"softened so it can be taken in.",
                      frank:"honest, with the softening removed.",
                      blunt:"no softening at all.",
                      brutal:"true, and said to wound." } }},
    {section:'4C', topic:'4C-vocab', letter:'A', clue:"Which one presents a contradictory opinion?",
      choice:{ options:["I beg to differ","No offence intended",
                        "Don't take this personally","I mean that in the nicest possible way"],
               answer:"I beg to differ" }},
    {section:'4C', topic:'4C-grammar', letter:'D', clue:"Correct the homophone: 'I mean it in the nicest possible weigh'.",
      choice:{ options:["way","weigh","wei","whey"], answer:"way" }},
    {section:'4C', topic:'4C-grammar', letter:'N', clue:"Correct the homophones: \"it's knot about being fare\".",
      choice:{ options:["not / fair","knot / fair","not / fare","nought / fair"], answer:"not / fair" }},
    {section:'4C', topic:'4C-grammar', letter:'E', clue:"Complete the idiom: '___ me about it!'",
      choice:{ options:["Tell","Say","Speak","Talk"], answer:"Tell" }},
    {section:'4C', topic:'4C-vocab', letter:'X', clue:"Put the words in order — conceding before you differ.",
      scramble:{ sentence:"I do take your point but I disagree" }},
    {section:'4C', topic:'4C-vocab', letter:'Y', clue:"Put the words in order — a formal disagreement.",
      scramble:{ sentence:"That is not the way I see it" }},
    {section:'4C', topic:'4C-vocab', letter:'C', clue:"the opposite of tactful, when you say it too hard", anagram:{ word:"tactless" }},
    {section:'4C', topic:'4C-vocab', letter:'P', clue:"easily upset by what people say about them", anagram:{ word:"sensitive" }},
    {section:'4C', topic:'4C-vocab', letter:'R', clue:"treating a delicate matter with too much force", anagram:{ word:"clumsy" }},
    {section:'4C', topic:'4C-vocab', letter:'G', clue:"handling people and disagreements well", anagram:{ word:"diplomatic" }},

    /* ---- 4D: profile writing and time expressions ---- */
    {section:'4D', topic:'4D-grammar', letter:'M', clue:"Four of these mean 'after a short time'. Find the four.",
      group:{ pick:["before long","shortly","soon","presently"], with:["the instant","immediately","at once","instantly"] }},
    {section:'4D', topic:'4D-grammar', letter:'L', clue:"Four of these mean 'at that very moment'. Find the four.",
      group:{ pick:["the moment","the instant","immediately","at once"], with:["gradually","subsequently","eventually","in time"] }},
    {section:'4D', topic:'4D-vocab', letter:'K', clue:"Four of these describe becoming well known. Find the four.",
      group:{ pick:["breakthrough","sensation","famous","recognised"], with:["outsider","unknown","obscure","overlooked"] }},
    {section:'4D', topic:'4D-vocab', letter:'Q', clue:"Four of these belong in a profile article. Find the four.",
      group:{ pick:["quotes","background","influences","achievements"],
              with:["homophones","idioms","collocations","inversions"] }},
    {section:'4D', topic:'4D-grammar', letter:'V', clue:"Four of these force the verb before the subject. Find the four.",
      group:{ pick:["No sooner","Not until","Only then","Rarely"], with:["Shortly","Gradually","Eventually","Afterwards"] }},
    {section:'4D', topic:'4D-grammar', letter:'O', clue:"Put these in order — the longest wait last.",
      order:{ scale:["at once","shortly","soon","in time","eventually"],
              low:"no gap at all", high:"after a very long while",
              gloss:{ 'at once':"with no delay whatever.",
                      shortly:"a short time afterwards.",
                      soon:"before long, but vaguer.",
                      'in time':"after a while has gone by.",
                      eventually:"in the end, after everything else." } }},
    {section:'4D', topic:'4D-vocab', letter:'W', clue:"Put these in order — least known first.",
      order:{ scale:["unknown","noticed","recognised","famous","legendary"],
              low:"nobody has heard of her", high:"everybody has",
              gloss:{ unknown:"where the article's subject begins.",
                      noticed:"a few people start to pay attention.",
                      recognised:"people know the name.",
                      famous:"widely known.",
                      legendary:"known long after the fact." } }},
    {section:'4D', topic:'4D-vocab', letter:'P', clue:"Put these in order — the article's own sequence.",
      order:{ scale:["shy","outsider","confident","performing","sensation"],
              low:"how she started", high:"where she ended up",
              gloss:{ shy:"how she describes herself as a young teenager.",
                      outsider:"how the moves left her feeling.",
                      confident:"what returning to South Africa gave her.",
                      performing:"regularly, with two other musicians.",
                      sensation:"the article's word once the album lands." } }},
    {section:'4D', topic:'4D-grammar', letter:'A', clue:"Which one means 'some time later'?",
      choice:{ options:["subsequently","the instant","immediately","at once"], answer:"subsequently" }},
    {section:'4D', topic:'4D-grammar', letter:'B', clue:"'It wasn't ___ she moved back that she felt confident.'",
      choice:{ options:["until","before","after","since"], answer:"until" }},
    {section:'4D', topic:'4D-vocab', letter:'C', clue:"Her popularity shows no sign of ___.",
      choice:{ options:["waning","waxing","winning","warning"], answer:"waning" }},
    {section:'4D', topic:'4D-vocab', letter:'D', clue:"What makes a good opening for a profile article?",
      choice:{ options:["the most interesting part of their story","a list of dates",
                        "the writer's own opinion","a summary of the ending"],
               answer:"the most interesting part of their story" }},
    {section:'4D', topic:'4D-grammar', letter:'X', clue:"Put the words in order — the inversion after 'no sooner'.",
      scramble:{ sentence:"No sooner had I started than I realised something" }},
    {section:'4D', topic:'4D-grammar', letter:'Y', clue:"Put the words in order — over a period, not at once.",
      scramble:{ sentence:"Gradually they got better known around the city" }},
    {section:'4D', topic:'4D-vocab', letter:'S', clue:"causing great excitement the moment it appears", anagram:{ word:"sensation" }},
    {section:'4D', topic:'4D-vocab', letter:'T', clue:"becoming weaker, said of fame or light", anagram:{ word:"waning" }},
    {section:'4D', topic:'4D-vocab', letter:'E', clue:"a piece of writing about one person's life and work", anagram:{ word:"profile" }},
    {section:'4D', topic:'4D-vocab', letter:'F', clue:"the style of clothing people always know her by", anagram:{ word:"trademark" }},
  ],
  blockbustersSectionNames: {
    '4A':'4A · Instinct & reason (18 rounds)',
    '4B':'4B · Memory, eyewitnesses & have/get (18 rounds)',
    '4C':'4C · Tact & idioms (18 rounds)',
    '4D':'4D · Profile writing & time expressions (18 rounds)',
  },

  /* ---- Race to the Board ----------------------------------------------------
     Gapped sentences; the answers become the words on the board, so each is a
     single word and none repeats. Distractors aren't authored — every other word
     on screen is a real target word from the chosen sections. */
  raceBank: [
    {section:'4C', topic:'4C-vocab', type:'errorfix', prompt:"Correct it: 'She gave a very *tactic* reply.'", answer:"Tactful"},
    /* ---- 4A: instinct & reason ---- */
    {section:'4A', topic:'4A-vocab', prompt:"She's completely ___ — she'd never decide anything on a feeling.", answer:"Rational"},
    {section:'4A', topic:'4A-vocab', prompt:"He bought the tickets on ___, without thinking it through.", answer:"Impulse"},
    {section:'4A', topic:'4A-vocab', prompt:"We ___ pick up on tiny changes in people's faces.", answer:"Subconsciously"},
    {section:'4A', topic:'4A-vocab', prompt:"Take a day to ___ up the pros and cons before you decide.", answer:"Weigh"},
    {section:'4A', topic:'4A-vocab', prompt:"A good judge stays ___ and sticks to the facts.", answer:"Objective"},
    {section:'4A', topic:'4A-vocab', prompt:"___ down, I knew the job wasn't right for me.", answer:"Deep"},
    {section:'4A', topic:'4A-vocab', prompt:"Trust your ___ — your first reaction is often the right one.", answer:"Gut"},
    {section:'4A', topic:'4A-vocab', prompt:"I had a ___ she was lying, though I couldn't prove it.", answer:"Hunch"},
    {section:'4A', topic:'4A-vocab', prompt:"They booked the flight on a ___, three hours before takeoff.", answer:"Whim"},
    {section:'4A', topic:'4A-vocab', prompt:"Doctors often rely on ___ built up over years of practice.", answer:"Intuition"},
    {section:'4A', topic:'4A-vocab', prompt:"Meeting her twice in one week was pure ___.", answer:"Coincidence"},
    {section:'4A', topic:'4A-vocab', prompt:"Each ___ of the brain handles different kinds of thinking.", answer:"Hemisphere"},
    {section:'4A', topic:'4A-vocab', prompt:"There was an ___ feeling of dread that she couldn't account for.", answer:"Inexplicable"},
    {section:'4A', topic:'4A-vocab', prompt:"Animals rely on ___ rather than reasoning.", answer:"Instinct"},

    /* ---- 4B: memory, eyewitnesses & have/get ---- */
    {section:'4B', topic:'4B-vocab', prompt:"I've only a ___ memory of that holiday — I was three.", answer:"Vague"},
    {section:'4B', topic:'4B-vocab', prompt:"Talking about the accident brings back ___ memories.", answer:"Painful"},
    {section:'4B', topic:'4B-vocab', prompt:"I have a ___ memory of the day — I can still smell the smoke.", answer:"Vivid"},
    {section:'4B', topic:'4B-vocab', prompt:"She has a ___ memory and can recall a page after one reading.", answer:"Photographic"},
    {section:'4B', topic:'4B-vocab', prompt:"It's a ___ memory now, faded by thirty years.", answer:"Distant"},
    {section:'4B', topic:'4B-vocab', prompt:"That summer left a ___ impression on all of us.", answer:"Lasting"},
    {section:'4B', topic:'4B-vocab', prompt:"Eyewitness evidence is ___ — witnesses make honest mistakes.", answer:"Fallible"},
    {section:'4B', topic:'4B-vocab', prompt:"Memory is ___: it reshapes itself every time we recall something.", answer:"Malleable"},
    {section:'4B', topic:'4B-vocab', prompt:"He tends to ___ the story a little more each time he tells it.", answer:"Embellish"},
    {section:'4B', topic:'4B-vocab', prompt:"Children are especially ___ to suggestion from adults.", answer:"Susceptible"},
    {section:'4B', topic:'4B-vocab', prompt:"The ___ was never caught, despite three witnesses.", answer:"Perpetrator"},
    {section:'4B', topic:'4B-grammar', prompt:"They ___ their roof repaired last spring — a builder did it.", answer:"Had"},
    {section:'4B', topic:'4B-grammar', prompt:"We ___ our car broken into while we were away.", answer:"Got"},
    {section:'4B', topic:'4B-grammar', prompt:"My parents were having the kitchen ___ by a local firm.", answer:"Renovated"},

    /* ---- 4C: tact & idioms ---- */
    {section:'4C', topic:'4C-vocab', prompt:"I beg to ___ — I read the situation quite differently.", answer:"Differ"},
    {section:'4C', topic:'4C-vocab', prompt:"With all due ___, I don't think that's your decision to make.", answer:"Respect"},
    {section:'4C', topic:'4C-vocab', prompt:"Don't take this ___, but the opening paragraph doesn't work.", answer:"Personally"},
    {section:'4C', topic:'4C-vocab', prompt:"I do take your ___, but there was more we could have done.", answer:"Point"},
    {section:'4C', topic:'4C-vocab', prompt:"No ___ intended, but I couldn't follow your argument at all.", answer:"Offence"},
    {section:'4C', topic:'4C-vocab', prompt:"He wasn't particularly ___ about why he'd left his last job.", answer:"Forthcoming"},
    {section:'4C', topic:'4C-vocab', prompt:"Saying difficult things kindly is a matter of ___.", answer:"Tact"},
    {section:'4C', topic:'4C-vocab', prompt:"I felt ___ about the whole arrangement, though I couldn't say why.", answer:"Uneasy"},
    {section:'4C', topic:'4C-vocab', prompt:"There was a ___ doubt at the back of my mind all week.", answer:"Nagging"},
    {section:'4C', topic:'4C-vocab', prompt:"Getting an answer out of him was like getting ___ out of a stone.", answer:"Blood"},
    {section:'4C', topic:'4C-vocab', prompt:"You can be a bit ___-handed with junior staff sometimes.", answer:"Heavy"},
    {section:'4C', topic:'4C-vocab', prompt:"Criticism meant to help rather than wound is ___.", answer:"Constructive"},
    {section:'4C', topic:'4C-vocab', prompt:"I mean that in the ___ possible way, of course.", answer:"Nicest"},
    {section:'4C', topic:'4C-vocab', prompt:"I'm ___ I have to say this, but the plan won't work.", answer:"Afraid"},

    /* ---- 4D: profile writing & time expressions ---- */
    {section:'4D', topic:'4D-vocab', prompt:"___ afterwards, she was offered a recording contract.", answer:"Shortly"},
    {section:'4D', topic:'4D-vocab', prompt:"She knew ___ that this was the band she wanted to join.", answer:"Immediately"},
    {section:'4D', topic:'4D-vocab', prompt:"___, over about two years, her confidence grew.", answer:"Gradually"},
    {section:'4D', topic:'4D-grammar', prompt:"She toured Europe and ___ released a second album.", answer:"Subsequently"},
    {section:'4D', topic:'4D-vocab', prompt:"The ___ I heard her voice, I knew she'd be famous.", answer:"Instant"},
    {section:'4D', topic:'4D-vocab', prompt:"___ long, she was writing songs of her own.", answer:"Before"},
    {section:'4D', topic:'4D-vocab', prompt:"It ___ until she was seventeen that she performed in public.", answer:"Wasn't"},
    {section:'4D', topic:'4D-vocab', prompt:"Her debut album was called '___', and it made her name.", answer:"Breakout"},
    {section:'4D', topic:'4D-vocab', prompt:"A ___ is an article about a person's life and career.", answer:"Profile"},
    {section:'4D', topic:'4D-vocab', prompt:"A good profile uses at least one direct ___ from the subject.", answer:"Quote"},
    {section:'4D', topic:'4D-vocab', prompt:"Describing the ___ of the interview helps the reader picture it.", answer:"Setting"},
    {section:'4D', topic:'4D-vocab', prompt:"Ask about the person's ___ — what they're proudest of.", answer:"Achievements"},
    {section:'4D', topic:'4D-grammar', prompt:"She struggled for years and ___ found her own sound.", answer:"Eventually"},
    {section:'4D', topic:'4D-vocab', prompt:"___ she started writing, she couldn't stop.", answer:"Once"},
  ],

  raceSectionNames: {
    '4A':'4A · Instinct & reason (14 words)',
    '4B':'4B · Memory & have/get (14 words)',
    '4C':'4C · Tact & idioms (15 words)',
    '4D':'4D · Profile writing & time expressions (14 words)',
  },

  /* ---- Millionaire ----------------------------------------------------------
     `level` 1-8 maps to the rungs, and every section covers all eight so a single
     section fills a ladder. The distractors are the teaching: each wrong option is
     an error this class would plausibly make — a real word with the wrong meaning,
     a wrong collocation, or a form error — never filler. */
  millionaireBank: [
    /* ---- typed forms: error correction, marked with *asterisks* ---- */
    {section:'4A', topic:'4A-vocab', type:'errorfix', level:3, prompt:"Correct the error: 'She decided *on impulsive*.'",
      answer:"on impulse", distractors:["in impulse","by impulsive","on the impulsive"]},
    {section:'4B', topic:'4B-grammar', type:'errorfix', level:4, prompt:"Correct the error: 'I *had cut* my hair at the salon.'",
      answer:"had my hair cut", distractors:["have cut my hair","did cut my hair","had cutting my hair"]},
    {section:'4C', topic:'4C-vocab', type:'errorfix', level:5, prompt:"Correct the error: 'He was very *tactic* about the news.'",
      answer:"tactful", distractors:["tactics","tactical","tacted"]},
    /* ---- 4A: instinct & reason ---- */
    {section:'4A', topic:'4A-vocab', level:1, prompt:"An informal word for instinct: 'trust your ___'.",
      answer:"gut", distractors:["stomach","belly","heart"]},
    {section:'4A', topic:'4A-vocab', level:2, prompt:"'He bought it on ___' — suddenly, without planning.",
      answer:"impulse", distractors:["instinct","a hunch","reflex"]},
    {section:'4A', topic:'4A-vocab', level:3, prompt:"Which adjective means 'based on facts, not feelings'?",
      answer:"objective", distractors:["subjective","rational","impartial"]},
    {section:'4A', topic:'4A-vocab', level:4, prompt:"A feeling that something is true, with no proof to show for it:",
      answer:"a hunch", distractors:["a hint","a whim","a guess"]},
    {section:'4A', topic:'4A-vocab', level:5, prompt:"'They flew to Rome on a ___' — on a sudden, unplanned wish.",
      answer:"whim", distractors:["impulse","hunch","urge"]},
    {section:'4A', topic:'4A-vocab', level:6, prompt:"Which means 'impossible to explain or account for'?",
      answer:"inexplicable", distractors:["unaccountable","implausible","indescribable"]},
    {section:'4A', topic:'4A-grammar', level:7, prompt:"Which noun phrase is correctly ordered?",
      answer:"a surprisingly reliable gut feeling",
      distractors:["a gut reliably surprising feeling","a gut feeling surprisingly reliable",
                   "a reliable surprisingly gut feeling"]},
    {section:'4A', topic:'4A-vocab', level:8, prompt:"Change the adjective 'intuitive' into the noun for the faculty itself.",
      answer:"intuition", distractors:["intuitiveness","intuitivity","intuitation"]},

    /* ---- 4B: memory, eyewitnesses & have/get ---- */
    {section:'4B', topic:'4B-vocab', level:1, prompt:"A memory that is unclear or hazy is a ___ one.",
      answer:"vague", distractors:["faint","blurred","distant"]},
    {section:'4B', topic:'4B-vocab', level:2, prompt:"A memory so detailed you can picture every part of it is ___.",
      answer:"vivid", distractors:["lasting","sharp","photographic"]},
    {section:'4B', topic:'4B-grammar', level:3, prompt:"'They ___ their roof repaired' — they paid someone else to do it.",
      answer:"had", distractors:["got themselves","have been","did"]},
    {section:'4B', topic:'4B-grammar', level:4, prompt:"'We ___ our car broken into' — something bad happened to us.",
      answer:"got", distractors:["had ourselves","made","have"]},
    {section:'4B', topic:'4B-vocab', level:5, prompt:"Which means 'capable of making mistakes'?",
      answer:"fallible", distractors:["falsifiable","faulty","fallacious"]},
    {section:'4B', topic:'4B-vocab', level:6, prompt:"Which means 'easily shaped or changed'? Memory is famously ___.",
      answer:"malleable", distractors:["mutable","pliant","manipulative"]},
    {section:'4B', topic:'4B-grammar', level:7, prompt:"Which sentence means somebody else did the work?",
      answer:"She had her portrait painted last year.",
      distractors:["She had painted her portrait last year.",
                   "She got painting her portrait last year.",
                   "She had been painting her portrait last year."]},
    {section:'4B', topic:'4B-grammar', level:8, prompt:"'I got my mum ___ I was ill.' Which form is correct?",
      answer:"to say", distractors:["say","saying","said"]},

    /* ---- 4C: tact & idioms ---- */
    {section:'4C', topic:'4C-vocab', level:1, prompt:"Which phrase softens a disagreement most politely?",
      answer:"I beg to differ", distractors:["You're wrong","That's nonsense","I disagree completely"]},
    {section:'4C', topic:'4C-vocab', level:2, prompt:"'With all due ___, I don't think that's your call.'",
      answer:"respect", distractors:["regard","politeness","courtesy"]},
    {section:'4C', topic:'4C-vocab', level:3, prompt:"'No ___ intended, but I couldn't follow your argument.'",
      answer:"offence", distractors:["insult","offense taken","harm"]},
    {section:'4C', topic:'4C-vocab', level:4, prompt:"Which means 'not willing to give information'?",
      answer:"not forthcoming", distractors:["not outspoken","not approachable","not upfront"]},
    {section:'4C', topic:'4C-grammar', level:5, prompt:"Which idiom describes trying to get information from an unwilling person?",
      answer:"like getting blood out of a stone",
      distractors:["like water off a duck's back","like getting your teeth pulled",
                   "like squeezing a dry sponge"]},
    {section:'4C', topic:'4C-vocab', level:6, prompt:"Being too forceful in your approach is being ___.",
      answer:"heavy-handed", distractors:["hard-headed","heavy-going","strong-armed"]},
    {section:'4C', topic:'4C-vocab', level:7, prompt:"Which is used to present a contradictory opinion, not to soften criticism?",
      answer:"That's not the way I see it",
      distractors:["Don't take this personally","I mean that in the nicest possible way",
                   "If you don't mind me saying so"]},
    {section:'4C', topic:'4C-grammar', level:8, prompt:"Which pair are homophones?",
      answer:"allowed / aloud", distractors:["accept / except","affect / effect","advice / advise"]},

    /* ---- 4D: profile writing & time expressions ---- */
    {section:'4D', topic:'4D-grammar', level:1, prompt:"Which time expression means 'right away'?",
      answer:"immediately", distractors:["shortly","gradually","eventually"]},
    {section:'4D', topic:'4D-vocab', level:2, prompt:"Which means 'slowly, over a period of time'?",
      answer:"gradually", distractors:["subsequently","instantly","briefly"]},
    {section:'4D', topic:'4D-vocab', level:3, prompt:"'___ afterwards, she signed a record deal.'",
      answer:"Shortly", distractors:["Lately","Presently","Currently"]},
    {section:'4D', topic:'4D-grammar', level:4, prompt:"Which means 'afterwards, following that'?",
      answer:"subsequently", distractors:["consequently","previously","accordingly"]},
    {section:'4D', topic:'4D-vocab', level:5, prompt:"'___ long, she was writing her own songs.'",
      answer:"Before", distractors:["Since","After","Until"]},
    {section:'4D', topic:'4D-vocab', level:6, prompt:"'The ___ I heard her sing, I knew.' Which completes it?",
      answer:"instant", distractors:["moment that","time when","second of"]},
    {section:'4D', topic:'4D-vocab', level:7, prompt:"Which sentence uses the emphatic time structure correctly?",
      answer:"It wasn't until she was 17 that she performed in public.",
      distractors:["It wasn't until she was 17 when she performed in public.",
                   "It wasn't till she was 17 she performed in public.",
                   "It was not until she was 17 than she performed in public."]},
    {section:'4D', topic:'4D-vocab', level:8, prompt:"Which does a profile article NOT normally do?",
      answer:"Argue for the writer's own opinion of the subject",
      distractors:["Quote the subject directly","Describe the setting of the interview",
                   "Trace the subject's career in order"]},

    /* A second question at every rung. With one per rung, both teams meet the
       identical question on their way up — the ladder is per-team, so the depth
       has to be too. */
    {section:'4A', topic:'4A-vocab', level:1, prompt:"'___ down, she knew it was the wrong choice.'",
      answer:"Deep", distractors:["Far","Low","Way"]},
    {section:'4A', topic:'4A-vocab', level:2, prompt:"Which means 'below the level of conscious awareness'?",
      answer:"subconsciously", distractors:["unconsciously","self-consciously","semi-consciously"]},
    {section:'4A', topic:'4A-vocab', level:3, prompt:"'Take a day to ___ up the options.'",
      answer:"weigh", distractors:["weight","way","weighted"]},
    {section:'4A', topic:'4A-vocab', level:4, prompt:"Two events happening together purely by chance:",
      answer:"a coincidence", distractors:["a consequence","a correlation","a concurrence"]},
    {section:'4A', topic:'4A-vocab', level:5, prompt:"The supposed extra sense beyond the usual five is the ___ sense.",
      answer:"sixth", distractors:["seventh","inner","extra"]},
    {section:'4A', topic:'4A-vocab', level:6, prompt:"Which describes an urge you simply cannot resist?",
      answer:"irresistible", distractors:["unresisting","resistless","irresistable"]},
    {section:'4A', topic:'4A-grammar', level:7, prompt:"Which noun phrase is correctly ordered?",
      answer:"a strong initial gut reaction",
      distractors:["a gut strong initial reaction","an initial strong gut reaction",
                   "a strong gut initial reaction"]},
    {section:'4A', topic:'4A-vocab', level:8, prompt:"Change the noun 'instinct' into the adjective.",
      answer:"instinctive", distractors:["instinctful","instinctional","instinctory"]},

    {section:'4B', topic:'4B-vocab', level:1, prompt:"Which adjective does NOT normally go with 'memory'?",
      answer:"heavy", distractors:["vague","painful","lasting"]},
    {section:'4B', topic:'4B-vocab', level:2, prompt:"A memory from a very long time ago is a ___ one.",
      answer:"distant", distractors:["faraway","remote","far"]},
    {section:'4B', topic:'4B-grammar', level:3, prompt:"'She ___ me doing all her homework.' Which fits?",
      answer:"had", distractors:["got","made to","let to"]},
    {section:'4B', topic:'4B-vocab', level:4, prompt:"Which means 'to add invented details to make a story better'?",
      answer:"embellish", distractors:["exaggerate","embroil","elaborate"]},
    {section:'4B', topic:'4B-vocab', level:5, prompt:"'Our memories are ___ to suggestion' — easily influenced.",
      answer:"susceptible", distractors:["suspicious","receptive","subjected"]},
    {section:'4B', topic:'4B-vocab', level:6, prompt:"Which noun completes 'the photofit bore little ___ to the suspect'?",
      answer:"resemblance", distractors:["resembling","likeliness","similitude"]},
    {section:'4B', topic:'4B-grammar', level:7, prompt:"In 'I had my bike stolen', what grammatical role does 'I' play?",
      answer:"subject", distractors:["object","indirect object","agent"]},
    {section:'4B', topic:'4B-vocab', level:8, prompt:"Which sentence says something bad happened to the speaker?",
      answer:"We got our windows smashed.",
      distractors:["We had our windows fitted.","We got the windows cleaned.",
                   "We had someone clean the windows."]},

    {section:'4C', topic:'4C-vocab', level:1, prompt:"Which acknowledges the other person before you disagree?",
      answer:"I do take your point, but…",
      distractors:["I beg to differ.","That's not the way I see it.","No offence intended, but…"]},
    {section:'4C', topic:'4C-vocab', level:2, prompt:"'Don't take this ___' — said before a criticism.",
      answer:"personally", distractors:["personal","seriously","to heart"]},
    {section:'4C', topic:'4C-vocab', level:3, prompt:"'She handled the whole conversation with great ___.'",
      answer:"tact", distractors:["tactic","tactfulness of manner","tactility"]},
    {section:'4C', topic:'4C-vocab', level:4, prompt:"'I see where you're ___ from, but I disagree.'",
      answer:"coming", distractors:["going","getting","arriving"]},
    {section:'4C', topic:'4C-vocab', level:5, prompt:"Criticism intended to help rather than wound is ___.",
      answer:"constructive", distractors:["constructional","instructive","productive"]},
    {section:'4C', topic:'4C-vocab', level:6, prompt:"Which means 'a worry that keeps returning'?",
      answer:"a nagging doubt", distractors:["a niggling nag","a naggy concern","a nagged feeling"]},
    {section:'4C', topic:'4C-vocab', level:7, prompt:"Which is used to soften bad news rather than to disagree?",
      answer:"I'm afraid I have to say…",
      distractors:["I beg to differ.","That's not the way I see it.",
                   "I see where you're coming from, but…"]},
    {section:'4C', topic:'4C-grammar', level:8, prompt:"Which pair are NOT homophones?",
      answer:"desert / dessert", distractors:["their / there","flour / flower","peace / piece"]},

    {section:'4D', topic:'4D-grammar', level:1, prompt:"Which time expression means 'soon after that'?",
      answer:"shortly afterwards", distractors:["lately","at present","for now"]},
    {section:'4D', topic:'4D-grammar', level:2, prompt:"Which means 'after a long time, in the end'?",
      answer:"eventually", distractors:["evidently","eventfully","presently"]},
    {section:'4D', topic:'4D-vocab', level:3, prompt:"Which introduces a point after which something became continuous?",
      answer:"Once she started writing…",
      distractors:["Whenever she started writing…","By the time she started writing…",
                   "As long as she started writing…"]},
    {section:'4D', topic:'4D-grammar', level:4, prompt:"Which links two events where the second follows the first?",
      answer:"subsequently", distractors:["simultaneously","previously","meanwhile"]},
    {section:'4D', topic:'4D-vocab', level:5, prompt:"Her debut album, the one that made her name, was called ___.",
      answer:"Breakout", distractors:["Breakthrough","Breakaway","Breakdown"]},
    {section:'4D', topic:'4D-grammar', level:6, prompt:"Which sentence puts the time expression in a natural place?",
      answer:"Gradually, her confidence grew.",
      distractors:["Her confidence gradually grew up.","Gradually grew her confidence.",
                   "Her gradually confidence grew."]},
    {section:'4D', topic:'4D-vocab', level:7, prompt:"Which opening would suit a profile article best?",
      answer:"A vivid scene from the interview",
      distractors:["A list of the subject's albums","The writer's opinion of the subject",
                   "A summary of the subject's finances"]},
    {section:'4D', topic:'4D-vocab', level:8, prompt:"'It wasn't until she was 17 ___ she performed in public.'",
      answer:"that", distractors:["when","which","then"]},
  ],

  millionaireSectionNames: {
    '4A':'4A · Instinct & reason (17 questions)',
    '4B':'4B · Memory & have/get (17 questions)',
    '4C':'4C · Tact & idioms (17 questions)',
    '4D':'4D · Profile writing & time expressions (16 questions)',
  },
});
