window.TOPIC_INDEX = [
  {
    id: 'present-simple',
    title: 'Present Simple',
    category: 'Grammar',
    level: 'A2-B1',
    summary: 'Daily routines, habits, and general truths with present simple forms.',
    tags: ['grammar', 'core tense'],
    path: 'topics/grammar/present-simple.js',
  },
  {
    id: 'present-perfect',
    title: 'Present Perfect',
    category: 'Grammar',
    level: 'B1',
    summary: 'Life experience, unfinished time, already / yet, and since / for.',
    tags: ['grammar', 'review'],
    path: 'topics/grammar/present-perfect.js',
  },
  {
    id: 'jobs-and-workplaces',
    title: 'Jobs & Workplaces',
    category: 'Vocabulary',
    level: 'B1',
    summary: 'Common job titles, workplace roles, and professional vocabulary.',
    tags: ['vocabulary', 'careers'],
    path: 'topics/vocabulary/jobs-and-workplaces.js',
  },
  {
    id: 'technology-support',
    title: 'Technology Support',
    category: 'Functional Language',
    level: 'B1',
    summary: 'Describing common tech problems, troubleshooting, and support language.',
    tags: ['functional-language', 'technology'],
    path: 'topics/functional/technology-support.js',
  },
];
